### ISSUE TITLE
CUDA/OptiX not detected on windows

### ISSUE THREAD

**Issue by mmp** [mmp/pbrt-v4#1]
The cmake script seems to have trouble finding OptiX, even when pointed at it, and I'm not enough of a cmake/windows expert to get it working...

**Comment by tototuo** [comment]
yes, when camke executed to line 114 "enable_language (CUDA)" in CMakeLists.txt ,  always get  No CUDA toolset found.

**Comment by mmp** [comment]
Superseded by #20. (And things should be in pretty good shape now...)
