### ISSUE TITLE
std::isinf may not return correct result when running with cuda on windows

### ISSUE THREAD

**Issue by zpxgdev** [mmp/pbrt-v4#104]
Test environment:
Windows10, MSVS  Version 16.8.4, Cuda 11.2

```cpp
template <typename T>
inline PBRT_CPU_GPU typename std::enable_if_t<std::is_floating_point<T>::value, bool>
IsInf(T v) {
    return std::isinf(v);
}
```

code 'IsInf(-0.765753f)' returns true.
if I change std::isinf to isinf from cuda math, the same code returns false.

if I change PBRT_CPU_GPU to PBRT_GPU the compiler will cause a error: can't call host function in device function.
so I guess std::isinf is a host function and can be called in PBRT_CPU_GPU  function, but the behavior maybe not correct.

**Comment by mmp** [comment]
Thank you for reporting this! It should be fixed now, but please let me know.
