### ISSUE TITLE
GPU vs CPU AreaLightSources

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#112]
## Preamble

Before the issue, a question.

What material should be on the shapes that make up an AreaLightSource?
* `Material "none"`
* `Material "diffuse"`
* In a quick glance at pbrt-v4-scenes no material is applied, which implies the default `Material "diffuse"` is used.

## Issue

When rendering an AreaLightSource with a `Material "none"` applied you get a different result in GPU vs CPU mode.

#### CPU
`pbrt --outfile sphere_light.png  sphere_light.pbrt`
![sphere_light](https://user-images.githubusercontent.com/2104033/108294946-a9c9e980-714b-11eb-93a7-46f18019f138.png)

#### GPU
`pbrt --gpu --outfile sphere_light_gpu.png  sphere_light.pbrt`
![sphere_light_gpu](https://user-images.githubusercontent.com/2104033/108294961-b2babb00-714b-11eb-9231-17759b1d2633.png)

Admittedly the GPU version is what I was expecting (the light being invisible). But this is partly me bringing my tainted VFX mindset to the party. Regardless of which is right, they should probably be consistent. :)

## Environment
* Cuda 11.1
* Optix 7.2
* pbrt 3839c90

## Scene
```
Film "rgb" 
    "integer xresolution" [ 400 ]
    "integer yresolution" [ 300 ]
    "string filename" [ "sphere_light.exr" ]

PixelFilter "gaussian" 
    "float yradius" [ 2 ]
    "float xradius" [ 2 ]

Sampler "pmj02bn"
    "integer pixelsamples" [ 64 ]

Integrator "volpath"
    "integer maxdepth" [ 5 ]

Accelerator "bvh"

LookAt  0 20 -50
        0 5 0
        0 1 0

Camera "perspective"
        "float fov" [ 45 ]
        "float screenwindow" [ -1 1 -0.75 0.75 ]

WorldBegin

# Light
AttributeBegin
	AreaLightSource "diffuse" "bool twosided" [ false ] "float scale" [ 10 ]
	AttributeBegin
		Material "none"
		Translate 0 10 0
		Shape "sphere" "float radius" [ 5 ]
	AttributeEnd
AttributeEnd

# Ground
AttributeBegin
    Material "diffuse"
    Rotate 90 1 0 0 
    Shape "disk" "float radius" [ 100 ]
AttributeEnd
```

**Comment by shadeops** [comment]
As a point of comparison here is how having different materials assigned to the AreaLightSource shape affects the render 

Column on the right is a `abs(diff) * 2` against the `Material "none"` render.

![diff](https://user-images.githubusercontent.com/2104033/108300043-6fb11580-7154-11eb-8cb9-215c472fbc52.png)

**Comment by mmp** [comment]
Thanks for reporting this--it's an interesting case!

The intent of the "none" material really is just for specifying interfaces between different participating media (and having no further effect to the scene.) Thus, I've gone ahead and renamed "none" to be "interface", to better express that intent (though "none" is still supported for backwards compatibility.) Further, any area lights specified with "interface" materials are now ignored (and a warning is issued) so now CPU and GPU both agree in their results on this front...
