### ISSUE TITLE
Error while trying to display a pbrt file with tev

### ISSUE THREAD

**Issue by AvanteElectro** [mmp/pbrt-v4#116]
Hi !

I can't figure out how to make pbrt work...

I typed `$ ./pbrt --display-server localhost:14158 teapot.pbrt` like it is mentionned in the README but it doesn't work.

Here is the error message :
```
pbrt version 4 (built Mar 20 2021 at 22:29:29)
Copyright (c)1998-2020 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Error: teapot.pbrt:6:0: Scene description must be inside world block; "AttributeBegin" is not allowed.
```

I tried with another pbrt file but got another error :

```
$ ./pbrt --display-server localhost:14158 bathroom/bathroom.pbrt
pbrt version 4 (built Mar 20 2021 at 22:29:29)
Copyright (c)1998-2020 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Warning: bathroom/bathroom.pbrt:60:0: TransformBegin/End are deprecated and should be replaced with AttributeBegin/End
Error: bathroom/bathroom.pbrt:71:0: color: texture type unknown. Must be "float" or "spectrum".
Error: bathroom/bathroom.pbrt:103:6: color: unknown parameter type
```

Could someone help me ?

**Comment by mmp** [comment]
From that error it looks like you're trying to render a pbrt-v3 scene. Try running it through `pbrt --upgrade` (as described in the README.md file.)

**Comment by AvanteElectro** [comment]
Thanks for the answer !

I tried with a file from the `pbrt-v4-scenes` repository and it worked well.

Thx !

**Comment by hugege1123** [comment]
你好，我在用vs2017运行代码时，在控制台出现了，以下几行话之后，就什么也没出现了?想请问以下，我该怎么操作

pbrt version 3 (built Mar 29 2022 at 22:03:37) [Detected 8 cores]
*** DEBUG BUILD ***
Copyright (c)1998-2018 Matt Pharr, Greg Humphreys, and Wenzel Jakob.
The source code to pbrt (but *not* the book contents) is covered by the BSD License.
See the file LICENSE.txt for the conditions of the license.
