### ISSUE TITLE
Question about Comparison between Floating-Point Number

### ISSUE THREAD

**Issue by kanition** [mmp/pbrt-v4#120]
Thank you for your amazing work! I'm learning it by myself. 

I find there are different ways to compare floating-point numbers:

1. Using function `CHECK_NE` or others like it:
https://github.com/mmp/pbrt-v4/blob/6fe4ab741e0bd5cdf3dddaafc8641dc6c9812030/src/pbrt/util/transform.h#L396
According to its definetion, it compares the numbers directly:
https://github.com/mmp/pbrt-v4/blob/1eea91e36989b9f5d5f5fe5069b2b8259bedade6/src/pbrt/util/check.h#L27
https://github.com/mmp/pbrt-v4/blob/1eea91e36989b9f5d5f5fe5069b2b8259bedade6/src/pbrt/util/check.h#L24

2. Using `==` or `!=` directly:
https://github.com/mmp/pbrt-v4/blob/6fe4ab741e0bd5cdf3dddaafc8641dc6c9812030/src/pbrt/util/transform.h#L397
Why not use the common way below here? Is there any special reason?
What's the scope of application of the strict equality and approximate equality in pbrt?
Many thanks!
```c
#define EPSILON 0.000000000001
Float f = 0.0;
if (f < EPSILON && f > -EPSILON)
{
    //f == 0, do something
}
else
{
   //f != 0, do something
}
```

**Comment by webanck** [comment]
From my understanding, the `CHECK_NE` construct is used extensively for debugging purposes and to add specific outputs when a numerical condition is violated.

**Comment by mmp** [comment]
Yep!

Also, regarding tests with epsilons, it depends on the circumstances; sometimes exact equality is what is needed. For example, for https://github.com/mmp/pbrt-v4/blob/6fe4ab741e0bd5cdf3dddaafc8641dc6c9812030/src/pbrt/util/transform.h#L396, the only concern is dividing by zero-there's no problem dividing by any non-zero number.
