### ISSUE TITLE
Dose pbr-book.org crash?

### ISSUE THREAD

**Issue by kanition** [mmp/pbrt-v4#121]
Excuse me.  The web page [http://www.pbr-book.org](http://www.pbr-book.org) can not be displayed. Error 522 for more than 10 hours. Is the service normal?

**Comment by mmp** [comment]
We made some changes to the hosting that necessitated DNS changes, which may have caused some problems.

It seems fine for me now, but a number of people have reported issues. Would you mind checking again? I am hopeful that everything is good now as old DNS entries have expired...

**Comment by povmaniaco** [comment]
FYI, I have tried the link up to 5 times.. without luck. I always get the same 522 error

**Comment by knightcrawler25** [comment]
http://www.pbr-book.org/ doesn't work for me, however http://pbr-book.org/ works fine.

**Comment by pierremoreau** [comment]
And it even has HTTPS now (which I’m quite sure it did not have before).

**Comment by mmp** [comment]
Indeed, https was one of the reasons for this change!

I believe that the www.pbr-book.org version of the site is now back, both for http and https but would be glad to know if that is the case for other folks as well.

**Comment by pierremoreau** [comment]
www.pbr-book.org works for me again, and I get automatically upgrade to https there as well. :+1:

**Comment by mmp** [comment]
Great!!
