### ISSUE TITLE
Imgtool is not compatible with OptiX 7.30 due 'OptixDenoiserModelKind' and 'OptixDenoiserOptions' changes

### ISSUE THREAD

**Issue by povmaniaco** [mmp/pbrt-v4#123]
After updating to OptiX 7.30 I have discovered that the changes introduced in this version make it incompatible with the current code of imgtool.cpp. If you don't want or don't have time to update the imgtool code, it might be a good idea to add some kind of warning about this incompatibility into README file or into CMakeLists.txt
Cheers..

**Comment by mmp** [comment]
Thanks for reporting this! I *think* I have gotten things wired up correctly but am unable to test it (I need to update my driver, etc.) If you have a chance to test it I'd be interested to know if it works, but at minimum the build is fixed now.

**Comment by mmp** [comment]
...now confirmed that it works, so closing this out.
