### ISSUE TITLE
Rotation value to 'Infinite' light type affect different in CPU mode that in GPU mode

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#126]
Trying to export my own version of the Barcelona Pavilion scene I have found that the rotation value of the 'Infinite' light does not cause any effect in the render mode on GPU. This is the result in CPU mode..
![pavilion_sky_cpu](https://user-images.githubusercontent.com/73945652/116808178-b39e9e80-ab37-11eb-8e06-f34839f4e350.png)

And this in GPU..
![pavilion_sky_rotate_gpu_mode](https://user-images.githubusercontent.com/73945652/116808197-cadd8c00-ab37-11eb-8ac5-993b6b8fec81.png)

Cheers..

**Comment by mmp** [comment]
Can you send a test case? If I try rendering `pavilion-day.pbrt` from the pbrt-v4-scenes distribution (which does have a number of rotations applied to the env map), it renders the same on both CPU and GPU.

**Comment by pbrt4bounty** [comment]
> 
> 
> Can you send a test case? If I try rendering `pavilion-day.pbrt` from the pbrt-v4-scenes distribution (which does have a number of rotations applied to the env map), it renders the same on both CPU and GPU.

Sure.. You only need to drop the necessary textures from the distribution folder into 'my_pavilion/textures' folder.
[my_pavilion.zip](https://github.com/mmp/pbrt-v4/files/6418283/my_pavilion.zip)
Cheers..

**Comment by pbrt4bounty** [comment]
@mmp The problem seems solved here in the last build.  I'm sorry for the noise.
