### ISSUE TITLE
Missing code indents on pbr-book.org

### ISSUE THREAD

**Issue by kirill146** [mmp/pbrt-v4#127]
Indentation is broken throughout the whole book:
![image](https://user-images.githubusercontent.com/19841109/116815393-cf756500-ab76-11eb-8024-3d64f6231ebc.png)

**Comment by mmp** [comment]
Fixed now; thanks for reporting this!

(Amusingly, we started using a CDN for the site and it was "helpfully" stripping whitespace from our HTML, which broke that...)
