### ISSUE TITLE
Any plan to add GPU support for 'curve' shape ?

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#135]
I am adding support for hair in the integration project in Blender and I got this warning when I tried to render using the GPU:
``Warning: E:\tmp\ParticleSystem.pbrt:5:0: "curve" shape is not yet supported on the GPU.``
Any plan to add GPU support for 'curve' shape ?
Cheers..

**Comment by mmp** [comment]
Yep. Issue #7. Implementing it is not currently high priority since the book won't discuss the corresponding code, so barring a PR (which would be welcome), it won't be implemented until the book writing is done.
