### ISSUE TITLE
non-class template has already been declared in GPU compilation

### ISSUE THREAD

**Issue by chursinm** [mmp/pbrt-v4#140]
I have nvcc compiler error in pstd.h line 350:

error C2990: 'unnamed': non-class template has already been declared as a class template

```
    template <typename V, typename = EnableIfConvertibleFrom<V>,
              typename = EnableIfMutableView<V>>    
    PBRT_CPU_GPU explicit span(V &v) noexcept : span(v.data(), v.size()) {}
```

CPU version is compiled fine.

This is the whole nvcc command-line: 

D:\pbrt\pbrt-v4\build>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc.exe" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64" -x cu -rdc=true  -I"D:\pbrt\pbrt-v4\src" -I"D:\pbrt\pbrt-v4\src\ext" -I"D:\pbrt\pbrt-v4\src\ext\stb" -I"D:\pbrt\pbrt-v4\src\ext\openexr\IlmBase\Imath" -I"D:\pbrt\pbrt-v4\src\ext\openexr\IlmBase\Half" -I"D:\pbrt\pbrt-v4\src\ext\openexr\IlmBase\Iex" -I"D:\pbrt\pbrt-v4\src\ext\openexr\OpenEXR\IlmImf" -I"D:\pbrt\pbrt-v4\build\src\ext\openexr\IlmBase\config" -I"D:\pbrt\pbrt-v4\build\src\ext\openexr\OpenEXR\config" -I"D:\pbrt\pbrt-v4\src\ext\zlib" -I"D:\pbrt\pbrt-v4\build\src\ext\zlib" -I"D:\pbrt\pbrt-v4\src\ext\filesystem" -I"D:\pbrt\pbrt-v4\src\ext\ptex\src\ptex" -I"D:\pbrt\pbrt-v4\src\ext\double-conversion" -I"D:\pbrt\pbrt-v4\src\ext\openvdb\nanovdb" -I"D:\pbrt\pbrt-v4\build" -I"C:\ProgramData\NVIDIA Corporation\OptiX SDK 7.3.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include"  -G   --keep-dir x64\Debug -use_fast_math -maxrregcount=0  --machine 64 --compile -cudart static -Xnvlink -suppress-stack-size-warning -Xcudafe --diag_suppress=partial_override -Xcudafe --diag_suppress=virtual_function_decl_hidden -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=declared_but_not_referenced -Xcudafe --diag_suppress=implicit_return_from_non_void_function --std=c++17 --expt-relaxed-constexpr --extended-lambda --forward-unknown-to-host-compiler -Xcompiler="/EHsc -Zi -Ob0 /wd4244 /wd4267 /wd4305 /wd4552 /wd4838 /wd4843 /wd26451 /wd26495" -g  -D_WINDOWS -DPBRT_IS_MSVC -D_CRT_SECURE_NO_WARNINGS -DPBRT_IS_WINDOWS -DNOMINMAX -DPBRT_BUILD_GPU_RENDERER -DPBRT_HAS_INTRIN_H -D"PBRT_NOINLINE=__declspec(noinline)" -DPBRT_RESTRICT=__restrict -DPBRT_HAVE__ALIGNED_MALLOC -DPTEX_STATIC -DPBRT_DEBUG_BUILD -D"CMAKE_INTDIR=\"Debug\"" -DWIN32 -D_WINDOWS -DPBRT_IS_MSVC -D_CRT_SECURE_NO_WARNINGS -DPBRT_IS_WINDOWS -DNOMINMAX -DPBRT_BUILD_GPU_RENDERER -DPBRT_HAS_INTRIN_H -D"PBRT_NOINLINE=__declspec(noinline)" -DPBRT_RESTRICT=__restrict -DPBRT_HAVE__ALIGNED_MALLOC -DPTEX_STATIC -DPBRT_DEBUG_BUILD -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /FdD:\pbrt\pbrt-v4\build\Debug\libpbrt_d.pdb /FS /Zi /RTC1 /MDd /GR" -o pbrt_lib.dir\Debug\textures.obj "D:\pbrt\pbrt-v4\src\pbrt\textures.cpp"

I have cuda version v11.3, Windows 10.

**Comment by pierremoreau** [comment]
I am guessing you are using Visual Studio 2019 >=v16.10? Given that span code has been around for nearly a year now and I have only seen this issue pop up after updating to Visual Studio 2019 v16.11 Preview 1.0, and that the C++ spec does not seem to disallow having multiple unnamed template parameters, I think this is a compiler regression introduced in the latest C++ compiler version of Visual Studio.

I worked around it by doing:
```diff
diff --git a/src/pbrt/util/pstd.h b/src/pbrt/util/pstd.h
index 80479f7..a28a5e7 100644
--- a/src/pbrt/util/pstd.h
+++ b/src/pbrt/util/pstd.h
@@ -347,13 +347,13 @@ class span {
 
     // Explicit reference constructor for a mutable `span<T>` type. Can be
     // replaced with Makespan() to infer the type parameter.
-    template <typename V, typename = EnableIfConvertibleFrom<V>,
-              typename = EnableIfMutableView<V>>
+    template <typename V, typename X = EnableIfConvertibleFrom<V>,
+              typename Y = EnableIfMutableView<V>>
     PBRT_CPU_GPU explicit span(V &v) noexcept : span(v.data(), v.size()) {}

     // Implicit reference constructor for a read-only `spanMconst T>` type
-    template <typename V, typename = EnableIfConvertibleFrom<V>,
-              typename = EnableIfConstView<V>>
+    template <typename V, typename X = EnableIfConvertibleFrom<V>,
+              typename Y = EnableIfConstView<V>>
     PBRT_CPU_GPU constexpr span(const V &v) noexcept : span(v.data(), v.size()) {}
 
     PBRT_CPU_GPU
```

**Comment by chursinm** [comment]
Wow, the workaround works fine! Thank you!!!

The original error message was from nvcc. 

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:41:42_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0`

I have VS 2019 Version 16.9.6, Win SDK 10.0.19041.0, platform toolset VS2019 v142 (at least for pbrt_lib project)

The other info: 
Microsoft Visual Studio Professional 2019
Version 16.9.6
VisualStudio.16.Release/16.9.6+31313.79
Installed Version: Professional
Microsoft Visual C++ 2019
NVIDIA CUDA 11.3 Wizards   11.3
Visual Studio Tools for CMake   1.0

**Comment by mmp** [comment]
Thanks, @pierremoreau!

**Comment by pierremoreau** [comment]
> The original error message was from nvcc.

The error code is from Microsoft's C++ compiler: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2990?view=msvc-160.

Bear in mind that when you compile CUDA code using nvcc, nvcc will only compile the device-relevant bits (code running on the GPU) and will forward the host bits (code running on the CPU) to the C++ compiler so even if only the nvcc invocation is visible in the logs, underneath the C++ compiler is being invoked by nvcc. That's why you have options like `-ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64"` (in the command line you shared) to select where the C++ compiler lives, and things like `-Xcompiler "/EHsc /W3 /nologo /Od /FdD:\pbrt\pbrt-v4\build\Debug\libpbrt_d.pdb /FS /Zi /RTC1 /MDd /GR"` to specify the flags to be passed along to the C++ compiler.

**Comment by chursinm** [comment]
@pierremoreau, thank you for your explanation. It clears a lot. And the build works fine now.

**Comment by pierremoreau** [comment]
No problems 🙂
