### ISSUE TITLE
"latitude-longitude" parameterization of envmap in infinite area light

### ISSUE THREAD

**Issue by f1shel** [mmp/pbrt-v4#142]
Since there is no documentation about v4 yet, I refer to v3 which said:

> It takes an environment map with a "latitude-longitude" parameterization, where given a direction vector w, the spherical (theta, phi) coordinates are found, and then the u coordinate of the environment map is indexed by the phi value and v is indexed by theta

However, most of environment maps that I found are like:
![HDRI](https://user-images.githubusercontent.com/83902932/122207592-e1b42400-ced4-11eb-8fa6-45114804c6d7.jpg)

> The best known spherical mapping method is the latitude/longitude-format. The depiction
is twice as wide as high. The X-axis of the depiction directly corresponds to the Heading/
Yaw-angle (0…360) and the Y-axis corresponds to the Pitch-angle (-90…0…90 degrees).
The horizontal center line represents the equator of the sphere, and the top & bottom lines
will translate into the poles. Due to distortions, and the concentration of pixel near the
poles, a re-editing of the picture is possible only to a limited extent.

This resulting an image of which the height is not equal to its width and pbrt-v4 will report error in this case. So, my question is, does pbrt-v4 really use "latitude-longitude" parameterization environment map?

Following is an example envmap used in pbrt-v4-scenes/sssdragon
![QQ截图20210616190329](https://user-images.githubusercontent.com/83902932/122208171-8fbfce00-ced5-11eb-8362-7e374dad3fe9.jpg)

**Comment by f1shel** [comment]
update: The parameterization method of environment map used in pbrt-v4-scenes/sssdragon seems to be [Peirce quincuncial projection](https://en.m.wikipedia.org/wiki/Peirce_quincuncial_projection), rather than lat/lon projection.

**Comment by mmp** [comment]
Close! Pbrt-v4 actually uses this mapping:
https://core.ac.uk/download/pdf/204967097.pdf, which has the useful
property of preserving area. (This is helpful for importance sampling.)

The imgtool program that comes with pbrt has a mode that converts lat-long
environment maps to that representation: “imgtool makerquiarea”

(Sorry all that isn’t documented yet…)

Thanks,
Matt

**Comment by f1shel** [comment]
Thanks for your kind reply!
