### ISSUE TITLE
Multi-GPU Rendering??? HOW

### ISSUE THREAD

**Issue by nospitters** [mmp/pbrt-v4#148]
Hi,
i sucessfully builded pbrt-v4 with gpu support on windows 10...
but when i use the --gpu option the renderer ist a bit slow...
when i add also the option --gpu-device 0, ie. it is really fast... :-)

But how can make use of multiple GPUs? when providing --gpu-device 0 ----gpu-device 1 then it always takes only one gpu...
is this supported yet?

**Comment by mmp** [comment]
Multi-GPU rendering is not supported and there are currently no plans to implement it. PRs are welcome, however. :-)

**Comment by nospitters** [comment]
i see. thanx for the quick reply...
