### ISSUE TITLE
Interface Materials Occluding with Wavefront

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#150]
It appears that when rendering via wavefront/gpu Shapes that have a Interface material occlude light.

Here are some example renders and the commands that generated them. 

Rendered with - 7d52153

#### pbrt wavefront.pbrt --outfile cpu.png
(Expected behavior)
![cpu](https://user-images.githubusercontent.com/2104033/126547945-a62a9a69-d223-48f1-8bac-a64223ecba46.png)

#### pbrt --wavefront wavefront.pbrt --outfile wavefront.png
![wavefront](https://user-images.githubusercontent.com/2104033/126548095-e6d8614c-bc77-452f-bc1b-f2e7270bb81d.png)

#### pbrt --gpu wavefront.pbrt --outfile gpu.png
![gpu](https://user-images.githubusercontent.com/2104033/126548134-59ea0e85-ca1c-4202-928a-7833ddaf4a84.png)

#### Scene
```
Film "rgb" 
    "integer xresolution" [ 400 ]
    "integer yresolution" [ 300 ]
    "string filename" [ "example.exr" ]

PixelFilter "gaussian" 
    "float yradius" [ 2 ]
    "float xradius" [ 2 ]

Sampler "pmj02bn"
    "integer pixelsamples" [ 64 ]

Integrator "volpath"
    "integer maxdepth" [ 5 ]

Accelerator "bvh"

LookAt  0 20 -50
        0 5 0
        0 1 0

Camera "perspective"
        "float fov" [ 45 ]
        "float screenwindow" [ -1 1 -0.75 0.75 ]

WorldBegin

# Light
AttributeBegin
    AreaLightSource "diffuse" "bool twosided" [ false ] "float scale" [ 10 ]
    AttributeBegin
        Translate 0 10 0
        Shape "sphere" "float radius" [ 2.5 ]
    AttributeEnd
AttributeEnd

# Interface
AttributeBegin
    Material "interface"
    Translate 5 10 -5
    Scale 5 9 1
    Shape "trianglemesh"
          "integer indices" [ 1 5 4 2 6 5 3 7 6 0 4 7 2 1 0 5 6 7
                              7 4 5 0 3 2 7 3 0 6 2 3 5 1 2 4 0 1 ]
          "point3 P" [ -1 -1 -1  1 -1 -1  1 -1 1  -1 -1 1
                       -1  1 -1  1  1 -1  1  1 1  -1  1 1 ]
AttributeEnd


# Ground
AttributeBegin
    Material "diffuse"
    Rotate 90 1 0 0 
    Shape "disk" "float radius" [ 100 ]
AttributeEnd
```

**Comment by mmp** [comment]
Good one--thanks for reporting it! It should be fixed now.
