### ISSUE TITLE
GPU compilation failed

### ISSUE THREAD

**Issue by jakoaltrd** [mmp/pbrt-v4#160]
<pre>-- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
-- Found CUDA: /usr/local/cuda (found version &quot;11.4&quot;) 
-- Found CUDA: 11.4.100
<font color="#AA5500">CMake Warning at CMakeLists.txt:174 (message):</font>
<font color="#AA5500">  Found CUDA but PBRT_OPTIX7_PATH is not set.  Disabling GPU compilation.</font>

</pre>

I try to set the enviroment in cmake, but it still throw this error, anybody knows why?

**Comment by mmp** [comment]
How are you specifying `PBRT_OPTIX7_PATH`? With command-line cmake it should be something like `cmake -DPBRT_OPTIX7_PATH=/path/to/optix/ ...`

**Comment by jakoaltrd** [comment]
I set it in cmake-gui, in the environment dialog. BTW, I am not sure whether I installed optix7.3 incorrectly, the optix dir has three folders, which are doc, include, SDK, the SDK dir has CMakeLists file inside, do I have to compile it before using it?

**Comment by jakoaltrd** [comment]
and if I use cmd to set the optix7.3 environment , it get more errors, I posted the error log
and my cmake options are :
cmake -S /home/jakoaltrd/Desktop/pbrt-v4 -B /home/jakoaltrd/Desktop/pbrt-v4/build1 -G 'CodeBlocks - Unix Makefiles' -DPBRT_OPTIX7_PATH=/home/jakoaltrd/Downloads/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64 -DPBRT_GPU_SHADER_MODEL=sm_80 ..


[CMakeError.log](https://github.com/mmp/pbrt-v4/files/6944306/CMakeError.log)

**Comment by mmp** [comment]
You don't need to compile anything in the optix folder after unzipping it.

If cmake is saying that `PBRT_OPTIX7_PATH` has not been set, then you have apparently not set it successfully. That command line you pasted above looks correct to me, however.

**Comment by jakoaltrd** [comment]
> You don't need to compile anything in the optix folder after unzipping it.
> 
> If cmake is saying that `PBRT_OPTIX7_PATH` has not been set, then you have apparently not set it successfully. That command line you pasted above looks correct to me, however.
I still can't successfully build the project with GPU

**Comment by mmp** [comment]
I'm not sure what to tell you. This is the source of the error message you are seeing:

```
    if ("${PBRT_OPTIX7_PATH}" STREQUAL "")
        message (WARNING "Found CUDA but PBRT_OPTIX7_PATH is not set. Disabling GPU compilation.")
```

ergo, you are not successfully setting PBRT_OPTIX7_PATH. This hasn't been a problem for anyone else, so I don't think there is evidence that there is a pbrt bug here. I suggest further perusal of the cmake documentation.

**Comment by jakoaltrd** [comment]
I am sure I set the optix, then I got another error like this:more than one conversation function from "__half" to a built-in type applies:function "__half::operator short() const"and then it stopped building . can you help me solve this issue?tell me if you need more info with it .
    On Saturday, August 7, 2021, 10:24:29 PM GMT+8, Matt Pharr ***@***.***> wrote:  
 
 


I'm not sure what to tell you. This is the source of the error message you are seeing:
    if ("${PBRT_OPTIX7_PATH}" STREQUAL "")
        message (WARNING "Found CUDA but PBRT_OPTIX7_PATH is not set. Disabling GPU compilation.")

ergo, you are not successfully setting PBRT_OPTIX7_PATH. This hasn't been a problem for anyone else, so I don't think there is evidence that there is a pbrt bug here. I suggest further perusal of the cmake documentation.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
