### ISSUE TITLE
Shouldn't `Midpoint(Sqrt(Interval i)) == std::sqrt(Midpoint(i))` be `true`?

### ISSUE THREAD

**Issue by germolinal** [mmp/pbrt-v4#161]
Hi, so I have been looking at your `Interval` class and, when testing, I realized the following: Let's say I define an `Interval a = {low: 0.1, high: 0.3}`. Since it has a `Midpoint = 0.2`, I would expect that `Midpoint(Sqrt(a)) == std::sqrt(0.2)` . However, it leads to some other value. Is this the expected behaviour? 

Shouldn't we do something like the following??? (sorry, I am not a C++ programmer)

```c++
PBRT_CPU_GPU inline Interval Sqrt(Interval i) {
    float correct_sqrt = std::sqrt(Midpoint(i));
    float err_high = SqrtRoundUp(i.UpperBound()) - correct_sqrt;
    float err_low = correct_sqrt - SqrtRoundDown(i.LowerBound());
    float err = std::max(err_high, err_low);

    return {
        correct_sqrt - err
        , 
        correct_sqrt + err
    };
}
```
https://github.com/mmp/pbrt-v4/blob/7740d7d6bbc4e8a5afc1aecea43900db552c60f8/src/pbrt/util/math.h#L1049

**Comment by mmp** [comment]
The idea of interval arithmetic is that you really don't know what 'correct' is; all you have is an interval that contains the correct answer. In that sense, `Midpoint()` is not useful for much and the midpoint value has no special importance (and is definitely not expected to be "correct".)

`Interval::Sqrt()`'s job is to return an interval that bounds the square root of the given interval (to maintain the invariant that the correct result is somewhere inside the interval.) If I'm reading it correctly, your change would lead to intervals that are wider than they need to be.
