### ISSUE TITLE
still have some issue with GPU！

### ISSUE THREAD

**Issue by jakoaltrd** [mmp/pbrt-v4#162]
and if I use cmd to set the optix7.3 environment , it get more errors, I posted the error log
and my cmake options are :
**cmake -S /home/jakoaltrd/Desktop/pbrt-v4 -B /home/jakoaltrd/Desktop/pbrt-v4/build1 -G 'CodeBlocks - Unix Makefiles' -DPBRT_OPTIX7_PATH=/home/jakoaltrd/Downloads/NVIDIA-OptiX-SDK-7.3.0-linux64-x86_64 -DPBRT_GPU_SHADER_MODEL=sm_80 ..**

can you help me solve this issue, please?

[CMakeError.log](https://github.com/mmp/pbrt-v4/files/6944306/CMakeError.log)

> How are you specifying `PBRT_OPTIX7_PATH`? With command-line cmake it should be something like `cmake -DPBRT_OPTIX7_PATH=/path/to/optix/ ...`

_Originally posted by @jakoaltrd in https://github.com/mmp/pbrt-v4/issues/160#issuecomment-894103061_

**Comment by mmp** [comment]
There's no need to open a second issue.

The errors in that `CMakeError.log` are all benign; it's just checking to see if various features are available so it knows what to try to try to include when it builds the system.

**Comment by jakoaltrd** [comment]
/home/jakoaltrd/Desktop/pbrt-v4/src/pbrt/util/float.h(507): error: more than one conversion function from "__half" to a built-in type applies:
            function "__half::operator float() const"
/usr/local/cuda/targets/x86_64-linux/include/cuda_fp16.hpp(204): here
            function "__half::operator short() const"
but when I build the project, there are some errors that it can't be successfully made, I try to build it with codeblocks , it can't make all run files successfully, just three of them, 'soac , rgb2spec_opt , cyhair2pbrt, the errors are in the CMakeError.log I sent to you before, then I try to use make to build it, it yeild the errors I pasted here. can you help me sovle this issue?
    On Saturday, August 7, 2021, 7:14:52 AM GMT+8, Matt Pharr ***@***.***> wrote:  
 
 


There's no need to open a second issue.

The errors in that CMakeError.log are all benign; it's just checking to see if various features are available so it knows what to try to try to include when it builds the system.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
