### ISSUE TITLE
Incomplete/partial initialization of SurfaceInteraction in wavefront/surfscatter.cpp

### ISSUE THREAD

**Issue by kontramind** [mmp/pbrt-v4#166]
Hi,

SurfaceInteraction has material as data member. However, it seems that this one is not being initialized in surfscatter.cpp (see lines after if statement at 144).
`           if (w.depth == 0 && initializeVisibleSurface) {
                SurfaceInteraction isect;
                isect.pi = w.pi;
                isect.n = w.n;
                isect.shading.n = ns;
                isect.uv = w.uv;
                isect.wo = w.wo;
                isect.time = w.time;
                isect.dpdx = dpdx;
                isect.dpdy = dpdy;`

Is this intentional or a bug?
If intentional, why?
If bug, adding a line like below would help:
`isect.material = w.material`

**Comment by kontramind** [comment]
A side question: How can one obtain which shape object (as defined in input pbrt file) was hit during intersection?

Many thanks.

**Comment by mmp** [comment]
It admittedly appears a bit questionable but in the end that `SurfaceInteraction` is only used to initialize a `VisibleSurface`, which doesn't access `SurfaceInteraction::material` in its constructor, so there's no bug in that regard.

There is currently no support for finding the intersected shape. It gets messy in the presence of object instancing (knowing which shape you hit isn't necessarily enough); the goal of what's stored in `SurfaceInteraction` is to provide all of the necessary information without having to worry about which shape you hit. So depending on what you're doing, your best bet is probably to add the information you need to `SurfaceInteraction` at intersection time, for later use...

**Comment by kontramind** [comment]
Many thanks. I added information that I needed for later use and it works as expected.
