### ISSUE TITLE
Objects with a conductor material are rendered too dark 

### ISSUE THREAD

**Issue by dkzivid** [mmp/pbrt-v4#168]
When trying to render conductor objects specifying spectra as
"spectrum eta" [ "metal-Au-eta" ]
"spectrum k" [ "metal-Au-k" ]
I get some dark objects that look nothing like gold. 
![image](https://user-images.githubusercontent.com/83456892/129569462-33eae1ad-fdea-41ce-bf6e-866d8aad58d8.png)

Similarly dark objects are rendered when using any available spectra for metals in pbrtv4 (aluminium, magnesium oxide etc).
Not clear whether there are some options in the sampling or the integrator that may provide a difference in getting a reasonable appearance. 

Edit

It seems that adding roughness specification fixes this issue. Is it the expected behaviour, that roughness should be explicitly specified?

**Comment by mmp** [comment]
The default roughness is zero, which corresponds to a perfectly smooth surface (and so there is only perfect specular reflection.) Are you rendering with a point or directional light source? In that case, pbrt (like all path tracers) is unable to successfully sample a path from a specular surface to the light. As you saw, increasing the roughness can help, or you could use an area or infinite area light source.

**Comment by dkzivid** [comment]
Thanks for your clarification, it all works as you explained. Closing the issue.
