### ISSUE TITLE
Dieletric Material Tint

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#182]
Howdy, quick question -

In a00d43b a `spectrum tint` parameter was added to the Dielectric Material

However in 44eaab0 the `spectrum tint` parameter was removed with a comment message of `Update from book source. No functional changes.`

Just confirming whether or not removal of the tint parameter was intentional or not given the "No functional changes" comment.

Thanks!

**Comment by mmp** [comment]
That was an intentional removal (that should have gotten more advertising in the commit message.)

Basically it was a hack that isn't going to be discussed in the book so it came out...
