### ISSUE TITLE
Unnatural image when using matte materials

### ISSUE THREAD

**Issue by GCLemon** [mmp/pbrt-v4#207]
I have got an unnatural image while using measured material and image based lighting. It often occures when I use diffuse materials. I am wondering whether this is an expected output.

The material is available at [EPFL RGL Material Database](http://rgl.epfl.ch/materials), and the original of environment map is available at [ICT Graphics Lab](https://vgl.ict.usc.edu/Data/HighResProbes/).

![sample](https://user-images.githubusercontent.com/49716948/142715987-764530d8-9a81-43d7-b2bd-c00e29070d70.png)

## Example Scene
```
LookAt -10 0 0 0 0 0 0 0 1
Camera "perspective"
    "float fov" [ 35 ]

Sampler "halton"
    "integer pixelsamples" [ 128 ]
Integrator "path"
Film "rgb"
    "integer yresolution" [ 512 ]
    "integer xresolution" [ 512 ]
    "string filename" [ "sample.exr" ]

WorldBegin

LightSource "infinite"
    "string filename" [ "grace-cathedral.exr" ]

MakeNamedMaterial "material"
    "string type" [ "measured" ]
    "string filename" [ "cm_white_spec.bsdf" ]

AttributeBegin
    NamedMaterial "material"
    Rotate 180 0 0 1
    Rotate 0 0 1 0
    Shape "plymesh"
        "string filename" [ "sphere.ply" ]
AttributeEnd
```

## Example Files
[https://drive.google.com/drive/folders/1QoVoJJMArnmBVE13RaSGB7pVYz2Z9N94?usp=sharing](https://drive.google.com/drive/folders/1QoVoJJMArnmBVE13RaSGB7pVYz2Z9N94?usp=sharing)

**Comment by mmp** [comment]
That material isn't particularly close to matte / diffuse; here is a visualization of its distribution for a low-elevation incident angle (from the visualizer on that material database page):

<img width="727" alt="image" src="https://user-images.githubusercontent.com/102567/142931015-4abce134-9fac-4c02-b25c-011c45552ecf.png">

Thus, given a fairly glossy/specular BRDF, that seems not unreasonable to me...
