### ISSUE TITLE
image difference when calling pbrt from different folder than description file location.

### ISSUE THREAD

**Issue by mserquet** [mmp/pbrt-v4#210]
When I was rendering the bistro scenes from the examples scenes, I got different results depending from where i called pbrt. If I call pbrt from a different folder, it looks like the normal-mapping is missing.

`pbrt-v4 --spp 4 --outfile parent-folder.png bistro/bistro_boulangerie.pbrt`
![parent-folder](https://user-images.githubusercontent.com/8088862/143033430-f4f52d8d-7259-46b8-af9d-e3ef3a585ecf.png)

`pbrt-v4 --spp 4 --outfile ../same-folder.png bistro_boulangerie.pbrt`
![same-folder](https://user-images.githubusercontent.com/8088862/143033442-23eea72b-f918-42b1-b23a-e60567d9fddd.png)

pbrt-v4 is a symbolic link in /usr/bin pointing to the compiled executable inside the build folder.

#### Additional info
OS: Ubuntu 20.04.3 LTS
Release build
built using Visual Studio Code with C/C++ extension pack
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
cmake version 3.16.3

**Comment by mmp** [comment]
Thanks for reporting this!

**Comment by mmp** [comment]
...and part 2 now fixed, thanks to @shadeops. (Good thing someone's paying attention here!)
