### ISSUE TITLE
Broken debug build for the GPU path

### ISSUE THREAD

**Issue by harrytodorov** [mmp/pbrt-v4#216]
When trying to compile the debug version `pbrt` with the GPU path enabled (using `nvcc V11.5.50` and `OptiX SDK V7.4.0` on Windows 10 using `MSVC`) I got the following error message:

> pbrt-v4\src\pbrt\gpu\aggregate.cpp(1041): error: identifier "OPTIX_COMPILE_DEBUG_LEVEL_LINEINFO" is undefined

After looking around for a bit, I saw in the [release notes](https://developer.download.nvidia.com/designworks/optix/secure/7.4.0/OptiX_Release_Notes_7.4_01.pdf?5DHxaayzywNiOoGssflssDHMEWo2QGbtwl0tyQCJzQbuE0S1dkWXiAQ1L3ETvOXQZUVnoVbTKYOL8i0OzQqDRdVPLpkgP59Szy9K9j1JAsG6XK8WUEJDnCS776mED9iCmNEmq_tUXZfuS5BHTmKCHPv-AadlUSaTDb_iWQ&t=eyJscyI6InJlZiIsImxzZCI6IlJFRi13d3cucmVuZGVyLWJsb2cuY29tXC8iLCJuY2lkIjoiZW0tbnVydC05MDA2NyJ9) for Optix 7.4 that the `OPTIX_COMPILE_DEBUG_LEVEL_LINEINFO` flag is replaced by two new flags:

>  - Removed `OPTIX_COMPILE_DEBUG_LEVEL_LINEINFO`
>  - Added
>     - `OPTIX_COMPILE_DEBUG_LEVEL_MINIMAL` - generate information that does not
> impact performance (currently generates line information useful for profiling)
>     - `OPTIX_COMPILE_DEBUG_LEVEL_MODERATE` - generate some debug information
> with slight performance costs (currently generates a debug frame necessary to show a
> backtrace)

P.S. I just saw the _TODO: REVIEW THIS_ comment couple of lines above the problematic define, so I guess you are already planning to fix this, but I didn't see an issue mentioning the problem so far, that's why I post it. 

In the meantime, for me switching from `OPTIX_COMPILE_DEBUG_LEVEL_LINEINFO` to `OPTIX_COMPILE_DEBUG_LEVEL_MINIMAL` solves the problem.

**Comment by mmp** [comment]
Thanks for reporting this! Fixed now.

(The "TODO: REVIEW THIS" was actually about setting `moduleCompileOptions.maxRegisterCount`, so the optix 7.4 issue wasn't already known, so thanks again.)

**Comment by harrytodorov** [comment]
Glad I could help!
