### ISSUE TITLE
Performance issue on Windows with multiple GPUs visible

### ISSUE THREAD

**Issue by Mike-Leo-Smith** [mmp/pbrt-v4#217]
Hi, Matt! Really nice work of pbrt-v4! However, I encountered some performance issues with the GPU mode.

I am using a Windows PC with two GPUs: RTX2080Ti + RTX2080. When rendering with the `--gpu` option, if the `CUDA_VISIBLE_DEVICES` environment variable is not set, or is set as `CUDA_VISIBLE_DEVICES=0,1` (i.e., both GPUs visible), there could be a ~100x performance slowdown. However, if it's set that only one device is visible (i.e., with either `CUDA_VISIBLE_DEVICES=0` or `CUDA_VISIBLE_DEVICES=1`), the performance is good, as expected.

So, likely this issue relates to some (possibly implicit and unexpected) cross-device synchronization? I am still looking into it to see if I could find any more clues.

**Comment by pierremoreau** [comment]
9be5258cb4a56464f7e2450bb6d7ad5fac5c8b69 did define `CUDA_VISIBLE_DEVICES` to only the GPU to be used, as a result of #29, and that code is still present so it is surprising you are running into it.

**Comment by Mike-Leo-Smith** [comment]
Seems the problem is because I didn't pass the `--gpu-device` argument to pbrt, and the `if` [condition](https://github.com/mmp/pbrt-v4/blob/c4cfd6679e436d512bed5b03fed33a1971d8ee6d/src/pbrt/pbrt.cpp#L67) to add the env is therefore not hit:
```cpp
if (Options->useGPU && Options->gpuDevice && !getenv("CUDA_VISIBLE_DEVICES")) {
```

Maybe a default value should be given to `Options->gpuDevice` if it is not present when the GPU mode is on? For example, change the lines to something like
```cpp
if (Options->useGPU && !getenv("CUDA_VISIBLE_DEVICES")) { // not checking `Options->gpuDevice` here
    std::string env = StringPrintf(
        "CUDA_VISIBLE_DEVICES=%d",
        Options->gpuDevice.value_or(0)); // the `value_or` method gives a default device id if not specified
    _putenv(env.c_str());
     Options->gpuDevice = 0;
}
```

**Comment by pierremoreau** [comment]
Ah, it's because the error message one gets if `--gpu-device` wasn't passed, is only printed if the devices do not have [the same major SM version](https://github.com/mmp/pbrt-v4/blob/b6a3f681108d5ebd414b0aa0a5d4ba4c99eca8e4/src/pbrt/gpu/util.cpp#L68-L75). The logic could probably be simplified to always requiring `--gpu-device` to be specified when on Windows and there being more than one device. Or selecting a default device, as you suggested. I am not sure which one is best.

**Comment by mmp** [comment]
Thanks for reporting this and for all of the detective work. I've just pushed a change that (should) issue an error if multiple GPUs are detected on Windows. I'm wary of selecting one by default for fear of, for example, inadvertently choosing the slow one that is only being used for the display.

Though as I write that, I suppose that on Linux it does just pick the first device if one isn't specified... Hmm.

**Comment by Mike-Leo-Smith** [comment]
Thanks for the quick fix!

I've tested with it on Windows, and pbrt just printed the nice new error messages as expected.

**Comment by Mike-Leo-Smith** [comment]
> Thanks for the quick fix!
> 
> I've tested with it on Windows, and pbrt printed the nice new error messages just as expected.

Ah, I also tested it on Linux, and it just picked the first device even if I don't pass the `--gpu-device` option.

So now it seems good on both Windows and Linux!
