### ISSUE TITLE
Scene Parsing Performance with Many Animated Transforms

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#219]
I was playing around with a lot, (1,000,000+), shapes that each have a unique animated transform and noticed pbrt-v4 was very slow to start rendering.

Looking at the verbose logging the slow down is happening here -
```
[ tid 136069 @     0.071s scene.cpp:773 ] Finished creating camera
[ tid 136007 @     911.28s parser.cpp:638 ] Finished parsing scene.pbrt
```
Without the animated transforms the timings look like 
```
[ tid 136069 @     0.068s scene.cpp:773 ] Finished creating camera
[ tid 136007 @     2.819s parser.cpp:638 ] Finished parsing scene.pbrt
```

A couple of manually interrupts in gdb showed it was constantly doing transform cache look-ups for -
https://github.com/mmp/pbrt-v4/blob/64c0a5cc0b29d6c6ffdacc53f93bc714e047e3b0/src/pbrt/scene.cpp#L275

That's a lot of work for an identity matrix!

As a quick hack I created a `const class Transform identityTransform = pbrt::Transform();` at the file scope and used that instead of  running the Lookup constantly.
```
        AnimatedShapeSceneEntity entity(
            {name, std::move(dict), loc, renderFromShape, &identityTransform,
             graphicsState.reverseOrientation, graphicsState.currentMaterialIndex,
             graphicsState.currentMaterialName, areaLightIndex,
             graphicsState.currentInsideMedium, graphicsState.currentOutsideMedium});
```
Doing so resulted in -
```
[ tid 136069 @     0.070s scene.cpp:773 ] Finished creating camera
[ tid 136007 @     3.921s parser.cpp:638 ] Finished parsing scene.pbrt
```

**Comment by shadeops** [comment]
My helper when testing this -
```python
import math


def make_spheres(spheres=1000, animated=False):
    cos = math.cos
    sin = math.sin
    sqrt = math.sqrt

    sphere_radius = sqrt(3 * math.pi / spheres) / 2.0

    phi = math.pi * (3.0 - sqrt(5.0))

    for i in range(spheres):
        y = 1 - (i / float(spheres - 1)) * 2
        radius = sqrt(1 - y * y)

        theta = phi * i

        x = cos(theta) * radius
        z = sin(theta) * radius

        print("AttributeBegin")
        if animated:
            print("ActiveTransform StartTime")
            print("Translate {} {} {}".format(x, y, z))
            print("ActiveTransform EndTime")
            print("Translate {} {} {}".format(x * 1.2, y * 1.2, z * 1.2))
            print("ActiveTransform All")
        else:
            print("Translate {} {} {}".format(x, y, z))
        print('Shape "sphere" "float radius" [ {} ]'.format(sphere_radius))
        print("AttributeEnd")


print(
    """
Film "rgb"
    "string filename" [ "spheres.exr" ]
    "integer xresolution" [ 512 ]
    "integer yresolution" [ 512 ]
Camera "perspective"
    "float fov" [ 45 ]
    "float screenwindow" [ -1 1 -1 1 ]
Sampler "zsobol"
    "integer pixelsamples" [ 128 ]

WorldBegin

LightSource "infinite"

"""
)


make_spheres(spheres=1000000, animated=True)
```

pbrt-v4 master with `make_spheres(spheres=1000000, animated=False)`
```bash
python3 spheres.py  | pbrt --quick --log-level verbose |& grep "Finished parsing"
[ tid 19703 @     5.241s parser.cpp:638 ] Finished parsing <stdin>
```

pbrt-v4 master with `make_spheres(spheres=1000000, animated=True)`
```bash
python3 spheres.py  | pbrt --quick --log-level verbose |& grep "Finished parsing"
[ tid 19786 @   931.500s parser.cpp:638 ] Finished parsing <stdin>
```

pbrt-v4 with a global identity transform with `make_spheres(spheres=1000000, animated=True)`
```bash
python3 spheres.py  | pbrt --quick --log-level verbose |& grep "Finished parsing"
[ tid 19925 @     8.941s parser.cpp:638 ] Finished parsing <stdin>
```

**Comment by mmp** [comment]
Very interesting! I had tried to reproduce this without success and was about to write a similar python program to spit out a bunch of random moving spheres, so thanks for that as well.

Most interestingly, this doesn't reproduce on OS X, but I can now reproduce it on Linux. (On OS X it's around 2x slower, so the bug may still be there but less severe, or maybe that 2x is a reasonable cost for animated shapes.) Your workaround seems reasonable but I'd like to figure out what the underlying issue is, since that lookup shouldn't be a bottleneck and now I'm wondering if that transform cache is causing trouble elsewhere...

**Comment by shadeops** [comment]
Oh boy.

I recompiled with Clang v12 and it only takes about 3 seconds on the same system.
`[ tid 37950 @     3.624s parser.cpp:640 ] Finished parsing <stdin>`

Just to make 100% sure I re-re-compiled  with gcc 9.3.0 and it is slow.

**Comment by mmp** [comment]
Continuing the holiday fun...
- Does not reproduce with a debug build (so debug is faster than release, for startup at least)
- Does not reproduce with an optimized build with debugging symbols included
- None of the assorted sanitizers (UBSan, ASan, etc.) find anything.

Printf logging indicates that it is not doing anything silly like unnecessarily growing the hash table all the time.

I did notice that the value returned for hashing the identity matrix is `0xdf3de588 565350ce`, which has that high bit set. So I wondered whether there is some undefined signed integer thing going on when the hash value is taken mod the hash table size. A point in favor of that is that casting the value returned by `Hash()` from `size_t` to `uint64_t` in the places where `Hash()` is called in `InternCache` makes things speedy again.

However, AFAIK with modern versions of g++ `size_t` is unsigned. I tried adding:
```c++
        static_assert(!std::is_signed<size_t>::value, "wtf");
```
to confirm that and indeed, that assert doesn't hit.

So... I'm not confident whether those `uint64_t` casts are actually fixing anything or just hiding something else.

**Comment by mmp** [comment]
Scratch that on `size_t`. This seems to fix it, but still for reasons unknown:

```diff
diff --git a/src/pbrt/util/transform.h b/src/pbrt/util/transform.h
index 3f36d0db..a1a8a549 100644
--- a/src/pbrt/util/transform.h
+++ b/src/pbrt/util/transform.h
@@ -544,7 +544,7 @@ struct hash<pbrt::Transform> {
     PBRT_CPU_GPU
     size_t operator()(const pbrt::Transform &t) const {
         pbrt::SquareMatrix<4> m = t.GetMatrix();
-        return pbrt::HashBuffer<sizeof(m)>(&m);
+        return pbrt::Hash(m);
     }
 };
```

**Comment by shadeops** [comment]
Compiling with g++ 10.3.0 makes it fast too.

**Comment by mmp** [comment]
After doing some more experiments and calling that hash from a standalone function, g++ offered the following complaint. (Not sure why it wasn't printed normally.)

```
../pbrt/util/hash.h: In function ‘size_t pbrt::TESTHASH(const pbrt::Transform&)’:
../pbrt/util/hash.h:36:13: warning: ‘m’ is used uninitialized in this function [-Wuninitialized]
   36 |             k = *data++;
      |             ^
../pbrt/util/hash.h:36:13: warning: ‘*((void*)& m +8)’ is used uninitialized in this function [-Wuninitialized]
../pbrt/util/hash.h:36:13: warning: ‘*((void*)& m +16)’ is used uninitialized in this function [-Wuninitialized]
../pbrt/util/hash.h:36:13: warning: ‘*((void*)& m +24)’ is used uninitialized in this function [-Wuninitialized]
../pbrt/util/hash.h:36:13: warning: ‘*((void*)& m +32)’ is used uninitialized in this function [-Wuninitialized]
../pbrt/util/hash.h:36:13: warning: ‘*((void*)& m +40)’ is used uninitialized in this function [-Wuninitialized]
../pbrt/util/hash.h:36:13: warning: ‘*((void*)& m +48)’ is used uninitialized in this function [-Wuninitialized]
../pbrt/util/hash.h:36:13: warning: ‘*((void*)& m +56)’ is used uninitialized in this function [-Wuninitialized]
```

Upon further review, I think that the (legit) issue is that the hashing code casts `SquareMatrix<4> *` -> `void *` -> `uint64_t *` and then loads using that last pointer. That's not legit given C++'s strict aliasing rules. (And so, going via `Hash()` is fine since that copies everything into a uint64_t buffer first.) Now, why it would run so slowly in that case I have no idea, but as far as UB goes, that's fair game. Anyway, I will land a fix, though likely tomorrow when it's all said and done.

**Comment by mmp** [comment]
Should be fixed now (but please confirm)--thanks for reporting this!!

**Comment by shadeops** [comment]
Looks good!
Test scenes are loading up nice and fast now! Comparable to the non-animated versions of them.

Back to rendering millions ~grains~ spheres ..
![sandtimer](https://user-images.githubusercontent.com/2104033/147505099-fdf29531-71ab-4598-a808-8ee9dba49c15.png)


As an aside, between this and #107 / #118 I've learned that hashing functions are fraught with peril.

**Comment by mmp** [comment]
That is indeed a lot of animated spheres--looking good!
