### ISSUE TITLE
pbrt_exe (debug) crashes after driver upgrade

### ISSUE THREAD

**Issue by kyamant** [mmp/pbrt-v4#226]
Following an upgrade of Nvidia driver to 511.65, pbrt_exe (**debug version**) crashes on the call:
```
OPTIX_CHECK_WITH_LOG(optixModuleCreateFromPTX(
                             optixContext, &moduleCompileOptions, &pipelineCompileOptions,
                             ptx, strlen(ptx), log, &logSize, &optixModule),
                         log);
```
in `OptixModule OptiXAggregate::createOptiXModule()` of aggregate.cpp.
**Release** version works.

**Comment by mmp** [comment]
Confirmed here as well, both on Windows with 511.65 and on Linux with 510.47.03. :-(. I've filed a bug internally at nvidia about this.

It's possible to workaround the issue by adding the line
```
    moduleCompileOptions.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_NONE;
```
in `OptiXAggregate::createOptiXModule()` in `src/pbrt/gpu/aggregate.cpp` though admittedly that is defeating the purpose of compiling with debugging information...

**Comment by mmp** [comment]
There is indeed a bug in the driver and a fix will be forthcoming in a future driver release. Sorry for the trouble. In the meantime I've pushed that workaround...
