### ISSUE TITLE
Caustics doesn't work 

### ISSUE THREAD

**Issue by AnasFX** [mmp/pbrt-v4#228]
I tried to convert a simple caustics example from a pbrt-v3 example to pbrt-v4. Unfortunately it didn't work and the caustics didn't show at all.
I checked the files and they seems ok, but the caustics doesn't show.
The test scene is (f16-11a.pbrt), here are the results :
V3
![111f16-11a](https://user-images.githubusercontent.com/77914725/152701756-d4ada34b-9ddf-4c3b-b940-4adce47a3cca.JPG)

V4
![test](https://user-images.githubusercontent.com/77914725/152701786-1ba8ae23-95bf-46bb-8eb8-d5073d6eff14.jpg)

V4 - --spp=8192
![8000](https://user-images.githubusercontent.com/77914725/152701894-4a814bee-e5a6-4be1-bfa7-e89e699c2fc7.jpg)

**Comment by shadeops** [comment]
Which integrator are you using?

Can you try something like 
```
LookAt -5.5 7 -5.5
    -4.75 2.25 0
    0 1 0
Camera "perspective"
    "float fov" [ 30 ]
Film "rgb"
    "float cropwindow" [ 0.3 0.7 0.4 0.7 ]
    "string filename" [ "f16-11a.exr" ]
    "integer yresolution" [ 2000 ]
    "integer xresolution" [ 1400 ]
Sampler "halton"
    "integer pixelsamples" [ 2048 ]
Integrator "sppm"
    "integer maxdepth" [ 10 ]
    "integer photonsperiteration" [ 500000 ]
    "float radius" [ 0.05 ]


WorldBegin

LightSource "spot"
    "float scale" [ 125 ]
    "blackbody I" [ 5500 ]
    "point3 to" [ -5 2.75 0 ]
    "point3 from" [ 0 5 9 ]

AttributeBegin
    LightSource "infinite"
        "rgb L" [ 0.1 0.1 0.1 ]
AttributeEnd

AttributeBegin
    Material "dielectric"
        "rgb eta" [ 1.25 1.25 1.25 ]
    Shape "plymesh"
        "string filename" [ "geometry/mesh_00001.ply" ]
AttributeEnd

AttributeBegin
    Shape "plymesh"
        "string filename" [ "geometry/mesh_00002.ply" ]
AttributeEnd
```

**Comment by AnasFX** [comment]
Hi thanks for the reply.
The file code that I used is the original from pbrt-v3, which is this:
`#LookAt -5 9 -5  -4.75 2.75 0   0 1 0
LookAt -5.5 7 -5.5
    -4.75 2.25 0
    0 1 0
Camera "perspective"
    "float fov" [ 30 ]
Film "rgb"
    "float iso" [ 150 ]
    "float cropwindow" [ 0.3 0.7 0.4 0.7 ]
    "string filename" [ "f16-11a.exr" ]
    "integer yresolution" [ 2000 ]
    "integer xresolution" [ 1400 ]
Integrator "sppm"
    "integer photonsperiteration" [ 100000 ]
    "float radius" [ 0.075 ]


WorldBegin

LightSource "spot"
    "float scale" [125]
    "blackbody I" [ 5500 ]
    "point3 to" [ -5 2.75 0 ]
    "point3 from" [ 0 5 9 ]

AttributeBegin
    LightSource "infinite"
        "rgb L" [ 0.1 0.1 0.1 ]
AttributeEnd

AttributeBegin
    Material "dielectric"
        "float eta" [ 1.25 ]
    Shape "plymesh"
        "string filename" [ "geometry/mesh_00001.ply" ]
AttributeEnd

AttributeBegin
    Material "coateddiffuse"
        "rgb reflectance" [ 0.64 0.64 0.64 ]
        "float roughness" [ 0.010408 ]
    Shape "plymesh"
        "string filename" [ "geometry/mesh_00002.ply" ]
AttributeEnd
`

When I changed this code `Integrator "sppm"
    "integer photonsperiteration" [ 100000 ]
    "float radius" [ 0.075 ]` to this `Sampler "halton"
    "integer pixelsamples" [ 2048 ]
Integrator "sppm"
    "integer maxdepth" [ 10 ]
    "integer photonsperiteration" [ 500000 ]
    "float radius" [ 0.05 ]` (like the code that you provided kindly) I face this error : 

pbrt-v4\src\pbrt\pbrt.cpp:51 ] ERROR Program generated exception -1073741818--terminating execution

Same thing happens when I use all of the code that you provided kindly.

**Comment by shadeops** [comment]
Are you using the latest commit c7e3879?
Are you on Windows?
Are you rendering to tev or just directly to an image? If rendering to a display server can you try without?

**Comment by AnasFX** [comment]
- I don't know how to get a certain commit, but I am on the latest version, unless there were some breaking changes in the last couple of days. I will try to rebuild it one more time with the latest git clone.
- I am on Win11
- I am rendering to a tev

Ps: I am rendering on the GPU, when I try to render on CPU it works

**Comment by shadeops** [comment]
GPU only supports volume path tracing, ie the volapth integrator. The other integrators like sppm, bdpt, mlt which can capture more difficult light paths aren't supported on the GPU.

**Comment by AnasFX** [comment]
oh 😢 , I thought when I read this (These requirements are effectively what makes it possible to bring pbrt to the GPU with limited changes to the core system.) that the code was implemented in its full glory power without limitations 😢 😢

**Comment by mmp** [comment]
Note that pbrt prints a warning message like:

Warning: glass.pbrt:17:0: Ignoring specified integrator "sppm": the wavefront integrator always uses a "volpath" integrator.

When rendering that scene on the GPU. It may not be immediately clear that the "volpath" integrator has quite different capabilities than the "sppm" integrator. One option would be to change that warning to a fatal error and require that the scene file be fixed, but I don't know if that would be too inflexible for cases where the user knows and doesn't care...

**Comment by alan-ramsay** [comment]
I've been struggling with this same issue, first with this scene in various guises, then I tried with the water-caustics scene from Benedict Bitterli's resources, hoping I had missed something in bringing the caustic-glass scene from v3... It also loses caustics when running on cpu with --wavefront option. I'm intrigued to know is this a fundamental thing lacking from the way GPUs are able to process paths, or just this integrator implementation?

**Comment by mmp** [comment]
@alan-ramsay as explained above, both pbrt's GPU integrator (and `--wavefront` on the CPU, which runs the same code) use volumetric path tracing, which does not sample caustics effectively.
