### ISSUE TITLE
Compiling instructions for multiple installed CUDA versions on (Ubuntu) Linux

### ISSUE THREAD

**Issue by olegded** [mmp/pbrt-v4#23]
Dear All,

Not sure whether it is worth to be mentioned in the compiling instructions/README or not, for the GPU-enabled build on Linux systems with multiple installed CUDA versions, you need to modify the `PATH` environment variable to contain the `v11` binaries first, e.g.:
``` bash
export PATH=/usr/local/cuda/bin:$PATH
```
Otherwise compiling will fail even after manual change of all corresponding CUDA-related `CMake` variables (including erroneous and lengthy `CMake` hacking/debugging).

In my case, there are two installed versions on Ubuntu 20.04:
- `v10` coming with system
- `v11` installed as described here [Download Installer for Linux Ubuntu 20.04 x86_64](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=deblocal)

Regards,
Oleg

**Comment by mmp** [comment]
Sorry for the bother! I've added a check to the cmake script that should issue an error if it's finding an older version of CUDA and tell the user to update their path if nececssary.

**Comment by olegded** [comment]
> Sorry for the bother! I've added a check to the cmake script that should issue an error if it's finding an older version of CUDA and tell the user to update their path if nececssary.

Not a problem at all :-)
