### ISSUE TITLE
Problem with a .png format

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#236]
@mmp  I found a issues when the PNG format is select as a output
```shell
Warning: straight-hair.png: 76493 out of gamut pixel channels clamped to [0,1].
```
Any ideas about this?

**Comment by mmp** [comment]
PNG can only store pixel values between 0 and 255. pbrt maps float values in 0-1 to 0-255, which is the usual mapping. If you have pixels with floating point values outside of that range (generally too bright), you get that error. An image format like OpenEXR that stores floats works around that warning.
