### ISSUE TITLE
Confirmed the best result with curves in CPU vs GPU (not a bug...)

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#237]
It is not a bug, just verifying the best results in CPU mode working with curves. Mainly the difference is in the geometry.
![long_hair_test_pbrt4_cpu](https://user-images.githubusercontent.com/421372/161406880-dcbb645c-64ae-41b9-8dae-fa4394691ba2.png)

Exactly the same scene, but rendered in GPU
![long_hair_test_pbrt4_gpu](https://user-images.githubusercontent.com/421372/161406892-18eb5532-5764-4741-944c-c7d0527a539a.png)

Even the render time is a bit better with CPU.
Cheers..

**Comment by shadeops** [comment]
As far as I know this is not a bug but a known limitation with curve support on the GPU.

See #201 for more info.

**Comment by pbrt4bounty** [comment]
Yeah.. is right. Btw.. A few days ago, I started some tests to add the possibility to read .hair files directly from pbrt. This will avoid the step of converting those files with the external utility. It will also avoid having to read large files in .pbrt format
https://github.com/TheBounty/pbrt-v4/commit/aeba4ffbe284f21f2ae9d90d3b83af196015f84d

**Comment by pbrt4bounty** [comment]
Yeah.. The beginnings were not very promising..
![imagen](https://user-images.githubusercontent.com/73945652/161453223-5b34813b-9302-4872-b0ff-dba276fe70b1.png)

..but after some more tests, the code it started working. There are still many things to polish. My code in Python is better than in C, but we can now read .hair files directly from PBRT.
![imagen](https://user-images.githubusercontent.com/73945652/161453289-161c9f0d-2e22-4a72-bb73-480606f1ce4f.png)

@mmp  I have noticed that the Optix SDK also uses the .hair format in its example files, so it may be possible to extend this patch to work with Optix as well. 
Cheers..
Btw... we can close this report because is not really a bug.
