### ISSUE TITLE
pbrt-v4\src\pbrt/util/taggedptr.h(806,37): error C2338: Expected uintptr_t to be 64 bits

### ISSUE THREAD

**Issue by SkybuckFlying** [mmp/pbrt-v4#239]
Visual Studio 2019 C++ compiler produces following errors on the following file:

Error: 
error C2338: Expected uintptr_t to be 64 bits

File: 
E:\SourceCode\pbrt-v4\src\pbrt/util/taggedptr.h

Line:
806

Code problem:
    static_assert(sizeof(uintptr_t) == 8, "Expected uintptr_t to be 64 bits"); // *** PROBLEM ***
    // TaggedPointer Private Members
    static constexpr int tagShift = 57;
    static constexpr int tagBits = 64 - tagShift;
    static constexpr uint64_t tagMask = ((1ull << tagBits) - 1) << tagShift;
    static constexpr uint64_t ptrMask = ~tagMask;
    uintptr_t bits = 0; // *** USED HERE ***
};

This happens when build set to release and win32.

I would like this code to work for win32/32 bit so that some day it can be integrated into 32 bit games like OpenXcom.

Is this fixeable ? If so pls fix it. Rest of code seems to compile OK. pbrt-v3 does compile OK in win32, pbrt-v4 does not, this is a degration of source code usefullness. 

End result is:
3>Done building project "pbrt_exe.vcxproj" -- FAILED.

QUESTION:

What are TaggedPointers used for ?

Since this is a private member perhaps use a different type for bits to solve this issue in win32 mode ?

Can it be solved for win32 ? If it's just for private members I would think so, but if it overwrites 64 bit pointers used in other data structures/fields then this might be a real problem.

I'll try out this experimental fix for vs2019:

	// Skybuck: experimental fix for win32
	unsigned __int64 bits = 0;

**Comment by SkybuckFlying** [comment]
Tried it with a simple test file:

E:\SourceCode\pbrt-v4-build\Release>pbrt SkybuckTestFile.pbrt
pbrt version 4 (built Apr 10 2022 at 06:43:49)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
[ tid 7812 @     0.000s util/math.h:1436 ] FATAL Check failed: inv.has_value()
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x43BA8000 -
(unknown                                 )      0x7648342B - BaseThreadInitThunk
(unknown                                 )      0x777097AF - RtlInitializeExceptionChain
(unknown                                 )      0x777097AF - RtlInitializeExceptionChain

**Comment by SkybuckFlying** [comment]
Test file is:
LookAt 3 4 1.5  # eye
       .5 .5 0  # look at point
       0 0 1    # up vector
Camera "perspective" "float fov" 45

Sampler "halton" "integer pixelsamples" 128
Integrator "path" "integer maxdepth" [1]
Film "image" "string filename" "simple.png"
     "integer xresolution" [400] "integer yresolution" [400]

WorldBegin

# uniform blue-ish illumination from all directions
LightSource "infinite" "rgb L" [.4 .45 .5]

# approximate the sun
LightSource "distant"  "point from" [ -30 40  100 ]
   "blackbody L" [3000 1.5]

AttributeBegin
  Material "glass"
  Shape "sphere" "float radius" 1
AttributeEnd

AttributeBegin
  Texture "checks" "spectrum" "checkerboard"
          "float uscale" [8] "float vscale" [8]
          "rgb tex1" [.1 .1 .1] "rgb tex2" [.8 .8 .8]
  Material "matte" "texture Kd" "checks"
  Translate 0 0 -1
  Shape "trianglemesh"
      "integer indices" [0 1 2 0 2 3]
      "point P" [ -20 -20 0   20 -20 0   20 20 0   -20 20 0 ]
      "float st" [ 0 0   1 0    1 1   0 1 ]
AttributeEnd

WorldEnd

**Comment by SkybuckFlying** [comment]
Maybe test file is bad ? Does anybody have a simple pbrt v4 scene test file ? Like a sphere and a checkerboard will do...

**Comment by SkybuckFlying** [comment]
I tried with V4 scene, crashes as well:

E:\SourceCode\pbrt-v4-build\Release>pbrt "E:\SourceCode\pbrt-v4-scenes\clouds\clouds.pbrt"
pbrt version 4 (built Apr 10 2022 at 06:43:49)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License
See the file LICENSE.txt for the conditions of the license.
[ tid 8872 @     0.000s util/math.h:1436 ] FATAL Check failed: inv.has_value()
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x006C0069 - c
(unknown                                 )      0x7648342B - BaseThreadInitThunk
(unknown                                 )      0x777097AF - RtlInitializeExceptionChain
(unknown                                 )      0x777097AF - RtlInitializeExceptionChain

**Comment by mmp** [comment]
I had admittedly assumed 32-bit targets didn't matter much anymore but I think it should be possible to get them working again..

The good news is that, looking at that code now, I think that `static_assert` is unnecessary. I believe that the rest of the TaggedPointer stuff will work with a 32-bit build (but haven't directly tested that yet.)

With your render of clouds.pbrt, is that with a pbrt built with that `static_assert` removed? Assuming so, then either I'm wrong about tagged pointer or there are other 64-bit assumptions to be fixed. I can try to reproduce this here and see what I can figure out as well.

**Comment by SkybuckFlying** [comment]
Yes static assert was removed, otherwise it won't build.

I made one modifcation back then...:

//    uintptr_t bits = 0;

	// Skybuck: experimental fix for win32
	unsigned __int64 bits = 0;

**Comment by mmp** [comment]
I'm happy to try debugging this but am having trouble getting a 32-bit build to complete with MSVC; can you say a bit about how you configured the build?

**Comment by SkybuckFlying** [comment]
I followed the build instructions for pbrt-v3, I believe it requires cmake tool, it creates a visual studio solution file and then I used visual studio 2019 to build pbrt-v4, if I recall correctly cmake can be configured to create a 32 bit solution file.

**Comment by mmp** [comment]
(Figured it out.) This should be fixed now.
