### ISSUE TITLE
Is MediumInterface limited to one for scene??

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#240]
I am trying to add 2 .nvdb objects to a scene but only one is drawn. Is this a limitation by design or am I doing something wrong? Can PBRT only create a MediumInterface?? Is there a way to render 2 .nvdb?
Cheers..

**Comment by shadeops** [comment]
Mediums whose bounding boxes overlap are not supported. But ones placed separately from another should work.

For example this was done with multiple NanoVDBs.

https://github.com/shadeops/pbrt-v4-volumes/blob/main/scenes/images/matchbulb_filmic.png

**Comment by pbrt4bounty** [comment]
Yeah.. Thanks for sharing the link!
