### ISSUE TITLE
Volume container is more visible when GPU is used(know issue)

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#241]
I don't know if is are a GPU limitation or a bad setup values in my side, but the volume region delimitator is more visible when the GPU is used.
This are the scene rendered with not GPU
![volume_one_pbrt](https://user-images.githubusercontent.com/73945652/163708954-ce3f127e-419c-405a-95c9-72409dee3c10.png)

And this, using a GPU mode
![volume_one_gpu](https://user-images.githubusercontent.com/73945652/163708971-d06df588-b61d-4750-b173-8162d0dcb91f.png)
 I use a 'Infinite' light type with a .hdr file.
Cheers..
Edit: the low 'ray depth' values are intentional to show the problem. Using 5 for 'ray depth' mitigate the issue and with 8 maybe is solved.

**Comment by shadeops** [comment]
This is a side effect of the wavefront integrator implementation. Increasing the max ray depth is the fix.

More info here

https://github.com/mmp/pbrt-v4/issues/151#issuecomment-885022572
