### ISSUE TITLE
Crash in GPU mode using 'Halton' sampler

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#246]
I've found that some light type + 'Halton' sampler combinations cause an access violation in GPU mode. It seems that in GPU mode, Halton only works fine with an Infinite light.
Is easy check this with any Killeroos scene version included in the repo. At least here, is impossible render these scene using Halton sampler + GPU mode. With any other sampler the scene is rendered OK.
Tested here under Windows 10, with a GPU build using CUDA 11.06 + Optix 7.4
Can anyone check this, please?

**Comment by pbrt4bounty** [comment]
There are the message error:
`pbrt version 4 (built Apr 30 2022 at 12:45:48)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.

[ tid 5916 @     0.000s pbrt-v4\src\pbrt\pbrt.cpp:51 ] ERROR Program generated exception -1073741818--terminating execution`

**Comment by mmp** [comment]
I can reproduce this on Windows but not on Linux, which is "interesting". Will try to take a closer look soon.

**Comment by pbrt4bounty** [comment]
I'm vaguely remember some issues with Halton sequences > 50 permutations  in another render engine.
But my memory isn't good :)

**Comment by pbrt4bounty** [comment]
@mmp Seems that 'permutedigits' is the culprit. With 'halton' + 'owen', by example, the render is OK in GPU

**Comment by pbrt4bounty** [comment]
Other test..
'halton' + 'fastowen' causes a crash but with a different message:
```
[ tid 14328 @     0.000s D:\REPOS\pbrt-v4\src\pbrt\util\print.cpp:48 ] FATAL Not enough optional values passed to Printf.
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x0000021F1E958CE0 - ▼☻
(unknown                                 )      0x00007FF848B01B20 - configthreadlocale
(unknown                                 )      0x00007FF84A747020 - BaseThreadInitThunk
(unknown                                 )      0x00007FF84ABE2630 - RtlUserThreadStart
```

**Comment by pbrt4bounty** [comment]
This are the error in the case of 'fastowen':
```diff
--- a/src/pbrt/samplers.cpp
+++ b/src/pbrt/samplers.cpp
@@ -81,7 +81,7 @@ HaltonSampler *HaltonSampler::Create(const ParameterDictionary &parameters,
     else if (s == "permutedigits")
         randomizer = RandomizeStrategy::PermuteDigits;
     else if (s == "fastowen")
-        ErrorExit("%s: \"fastowen\" randomization not supported by Halton sampler.");
+        ErrorExit("%s: randomization not supported by Halton sampler.", s);
     else if (s == "owen")
         randomizer = RandomizeStrategy::Owen;
     else
```

**Comment by pbrt4bounty** [comment]
@mmp OK. Now I remember the case in the other engine: this use only the first 50 prime numbers ( pbrt uses 1000) I did a small test reducing `PrimeTableSize` to 50 and now I can use `halton` + `permutedigits`  + GPU mode without crash under Windows.
What do you think about this?
Cheers..

**Comment by mmp** [comment]
This took a while to track down but should be fixed now--thanks for reporting it!

I suspect that reducing PrimeTableSize ended up masking the actual bug since that would cause the Sampler initialization to finish more quickly, which in turn would mean that the CPU was no longer writing to GPU managed memory.
