### ISSUE TITLE
Concept of 'alpha' texture (more a question, instead of a bug report)

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#247]
Is the 'alpha' texture designed to be used as a 'sprite' and for that reason is it applied to the 'object' instead of the material?
Example of implementation from 'San Miguel' scene:
```
AttributeBegin
    ObjectBegin "Hoja_Verde_A21384"

    AttributeBegin
        Transform [ 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1  ]
        NamedMaterial "Hoja_Verde_A"
        Shape "plymesh"
            "string filename" [ "geometry/enredadera2_00003.ply" ]
            "texture alpha" [ "Map #28" ]
    AttributeEnd
AttributeEnd
```
I have successfully implemented this type of texture in the addon for Blender, but with the current design, I need to apply it to each object individually, or to the base object in the case of instances.
Being able to apply it to the material would greatly facilitate its implementation.
Cheers..
![tendo_dojo_pbrt](https://user-images.githubusercontent.com/73945652/166701503-9a78a229-5697-4522-ae8d-44e8ea2c96e6.png)

**Comment by shadeops** [comment]
I think it is separated from materials so during the intersection pipeline a ray can decide whether to intersect or continue without having to evaluate the material network.

When setting this up in Houdini, I decided to just treat alpha as another slot. So an object ends up having 3 slots,
Material
Alpha
Displacement (this slot is ignored unless a Ply shape, and also not to be confused by the displacement texture input on Materials)
