### ISSUE TITLE
Add support for multimaterials per object

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#255]
I recently added support to the Blender plugin for managing multi-material meshes at export time. The way to implement it is by creating a mesh per material. Although it is working correctly, this way seems inefficient. This has made me wonder if it is a good idea to expand the definition of triangle, adding material index.
Do you think it's a good idea? Is the triangle definition the best place to add this option? Can this add unnecessary complexity?
Do you think @mmp ?
Cheers..

**Comment by mmp** [comment]
Just to leave an answer in the issue... I think this would be useful functionality in general, but it's unfortunately too late to add it to pbrt-v4 (since the book text is set at this point). pbrt-v5, then! :-)
