### ISSUE TITLE
Trying to add libpbrt.lib to OpenXcomExtended project: log.h(45,6): warning C4002: too many arguments for function-like macro invocation 'Log' (compiling source file Battlescape\Map.cpp)

### ISSUE THREAD

**Issue by SkybuckFlying** [mmp/pbrt-v4#258]
Hello,

I am trying to add libpbrt.lib to OpenXcom Extended project/solution for Visual Studio 2019. (I always struggle with lib files and includes/headers/sources and such but I am trying, and I followed Microsoft walkthrough how to try and add it).

https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-static-library-cpp?view=msvc-170

So for the source code folder (\src)  is added to the solution/project in: c/c++ -> general ->additional include directories

In map.cpp the pbrt.h and options.h is included as follows:

#include "pbrt/pbrt.h"
#include "pbrt/options.h"

in method void Map::drawTerrain(Surface *surface) the following code is added at the bottom before surface lock to test if PBRT will be compiled/build into the project.

(Strangely enough I have not yet added the pbrt.lib file... the wallkthrough on microsoft website is a bit fuzy/out of order about that)

```
	// experiment with pbrt
	struct pbrt::PBRTOptions blabla;
	pbrt::InitPBRT( blabla );
	pbrt::CleanupPBRT();

```

When trying to compile with visual studio 2019 and c/c++ 2017 language settings it produces following warning and error messages:

1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(45,6): warning C4002: too many arguments for function-like macro invocation 'Log' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(45,6): error C2059: syntax error: 'if' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(45,6): error C2653: 'Logger': is not a class or namespace name (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(45,6): error C2143: syntax error: missing ';' before '{' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(45,6): error C2447: '{': missing function header (old-style formal list?) (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(45,6): error C2059: syntax error: 'else' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(52,1): warning C4002: too many arguments for function-like macro invocation 'Log' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(51,1): error C2988: unrecognizable template declaration/definition (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(51,1): error C2059: syntax error: 'if' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(51,1): error C2653: 'Logger': is not a class or namespace name (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(52,1): error C2143: syntax error: missing ';' before '{' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(52,1): error C2447: '{': missing function header (old-style formal list?) (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(51,1): error C2059: syntax error: 'else' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(100,1): warning C4002: too many arguments for function-like macro invocation 'Log' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(99,1): error C2988: unrecognizable template declaration/definition (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(99,1): error C2059: syntax error: 'if' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(99,1): error C2653: 'Logger': is not a class or namespace name (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(100,1): error C2143: syntax error: missing ';' before '{' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(100,1): error C2447: '{': missing function header (old-style formal list?) (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(99,1): error C2059: syntax error: 'else' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(104,52): error C2065: 'Args': undeclared identifier (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(105,5): warning C4002: too many arguments for function-like macro invocation 'Log' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(105,5): error C2988: unrecognizable template declaration/definition (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(105,5): error C2059: syntax error: 'if' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(105,5): error C2653: 'Logger': is not a class or namespace name (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(105,5): error C2143: syntax error: missing ';' before '{' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(105,5): error C2447: '{': missing function header (old-style formal list?) (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(105,5): error C2059: syntax error: 'else' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(110,13): error C2182: 'LogFatal': illegal use of type 'void' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(110,22): error C2065: 'LogLevel': undeclared identifier (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(110,31): error C2146: syntax error: missing ')' before identifier 'level' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(111,1): error C2143: syntax error: missing ';' before '{' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(111,1): error C2447: '{': missing function header (old-style formal list?) (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(120,1): error C2988: unrecognizable template declaration/definition (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(120,1): error C2059: syntax error: '}' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(120,1): error C2143: syntax error: missing ';' before '}' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\stats.h(14,1): error C2143: syntax error: missing ';' before '{' (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\stats.h(14,1): error C2447: '{': missing function header (old-style formal list?) (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\math.h(410,17): error C3861: '__builtin_clz': identifier not found (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\math.h(435,17): error C3861: '__builtin_clzll': identifier not found (compiling source file Battlescape\Map.cpp)
1>E:\SourceCode\OpenXComExtended\PBRT\src\Battlescape\Map.cpp(606,71): warning C4804: '-': unsafe use of type 'bool' in operation

I could really use some help with a short description of how to add libpbrt.lib to other projects and how to make it work (include header files and library file and such).

Note: I would like to add the win32 version of PBRT v4.

**Comment by mmp** [comment]
So what is happening at this line of code? 1>E:\SourceCode\pbrt-v4-v2-mod-for-openxcom\src\pbrt\util\log.h(45,6): warning C4002: too many arguments for function-like macro invocation 'Log' (compiling source file Battlescape\Map.cpp)

Most likely, pbrt has `#defined` something that is causing trouble in your code. (It's not very hygienic about making sure not to leak preprocessor defines from its headers...) Here are all of the macros defined in pbrt's headers (other than `#include` guards; I imagine one of them is the problem:
```
gpu/cudagl.h:#define GL_CHECK(call)                                                   \
gpu/cudagl.h:#define GL_CHECK_ERRORS()                                     \
gpu/util.h:#define CUDA_CHECK(EXPR)                                        \
gpu/util.h:#define CU_CHECK(EXPR)                                              \
pbrt.h:#define UNICODE
pbrt.h:#define UNICODE
util/check.h:#define CHECK(x) assert(x)
util/check.h:#define CHECK_IMPL(a, b, op) assert((a)op(b))
util/check.h:#define CHECK_EQ(a, b) CHECK_IMPL(a, b, ==)
util/check.h:#define CHECK_NE(a, b) CHECK_IMPL(a, b, !=)
util/check.h:#define CHECK_GT(a, b) CHECK_IMPL(a, b, >)
util/check.h:#define CHECK_GE(a, b) CHECK_IMPL(a, b, >=)
util/check.h:#define CHECK_LT(a, b) CHECK_IMPL(a, b, <)
util/check.h:#define CHECK_LE(a, b) CHECK_IMPL(a, b, <=)
util/check.h:#define CHECK(x) (!(!(x) && (LOG_FATAL("Check failed: %s", #x), true)))
util/check.h:#define CHECK_EQ(a, b) CHECK_IMPL(a, b, ==)
util/check.h:#define CHECK_NE(a, b) CHECK_IMPL(a, b, !=)
util/check.h:#define CHECK_GT(a, b) CHECK_IMPL(a, b, >)
util/check.h:#define CHECK_GE(a, b) CHECK_IMPL(a, b, >=)
util/check.h:#define CHECK_LT(a, b) CHECK_IMPL(a, b, <)
util/check.h:#define CHECK_LE(a, b) CHECK_IMPL(a, b, <=)
util/check.h:#define CHECK_IMPL(a, b, op)                                                           \
util/check.h:#define DCHECK(x) (CHECK(x))
util/check.h:#define DCHECK_EQ(a, b) CHECK_EQ(a, b)
util/check.h:#define DCHECK_NE(a, b) CHECK_NE(a, b)
util/check.h:#define DCHECK_GT(a, b) CHECK_GT(a, b)
util/check.h:#define DCHECK_GE(a, b) CHECK_GE(a, b)
util/check.h:#define DCHECK_LT(a, b) CHECK_LT(a, b)
util/check.h:#define DCHECK_LE(a, b) CHECK_LE(a, b)
util/check.h:#define EMPTY_CHECK \
util/check.h:#define DCHECK(x) EMPTY_CHECK
util/check.h:#define DCHECK_EQ(a, b) EMPTY_CHECK
util/check.h:#define DCHECK_NE(a, b) EMPTY_CHECK
util/check.h:#define DCHECK_GT(a, b) EMPTY_CHECK
util/check.h:#define DCHECK_GE(a, b) EMPTY_CHECK
util/check.h:#define DCHECK_LT(a, b) EMPTY_CHECK
util/check.h:#define DCHECK_LE(a, b) EMPTY_CHECK
util/check.h:#define CHECK_RARE_TO_STRING(x) #x
util/check.h:#define CHECK_RARE_EXPAND_AND_TO_STRING(x) CHECK_RARE_TO_STRING(x)
util/check.h:#define CHECK_RARE(freq, condition)
util/check.h:#define DCHECK_RARE(freq, condition)
util/check.h:#define CHECK_RARE(freq, condition)                                                     \
util/check.h:#define DCHECK_RARE(freq, condition) CHECK_RARE(freq, condition)
util/check.h:#define DCHECK_RARE(freq, condition)
util/float.h:#define DoubleOneMinusEpsilon 0x1.fffffffffffffp-1
util/float.h:#define FloatOneMinusEpsilon float(0x1.fffffep-1)
util/float.h:#define OneMinusEpsilon DoubleOneMinusEpsilon
util/float.h:#define OneMinusEpsilon FloatOneMinusEpsilon
util/float.h:#define Infinity std::numeric_limits<Float>::infinity()
util/float.h:#define MachineEpsilon std::numeric_limits<Float>::epsilon() * 0.5f
util/log.h:#define TO_STRING(x) TO_STRING2(x)
util/log.h:#define TO_STRING2(x) #x
util/log.h:#define LOG_VERBOSE(...)                               \
util/log.h:#define LOG_ERROR(...)                               \
util/log.h:#define LOG_FATAL(...) \
util/log.h:#define LOG_VERBOSE(...)                             \
util/log.h:#define LOG_ERROR(...)                                   \
util/log.h:#define LOG_FATAL(...) \
util/math.h:#define ShadowEpsilon 0.0001f
util/math.h:#define Pi Float(3.14159265358979323846)
util/math.h:#define InvPi Float(0.31830988618379067154)
util/math.h:#define Inv2Pi Float(0.15915494309189533577)
util/math.h:#define Inv4Pi Float(0.07957747154594766788)
util/math.h:#define PiOver2 Float(1.57079632679489661923)
util/math.h:#define PiOver4 Float(0.78539816339744830961)
util/math.h:#define Sqrt2 Float(1.41421356237309504880)
util/rng.h:#define PCG32_DEFAULT_STATE 0x853c49e6748fea9bULL
util/rng.h:#define PCG32_DEFAULT_STREAM 0xda3e39cb94b95bdbULL
util/rng.h:#define PCG32_MULT 0x5851f42d4c957f2dULL
util/stats.h:#define STAT_COUNTER(title, var)                                       \
util/stats.h:#define STAT_PIXEL_COUNTER(title, var)                                        \
util/stats.h:#define STAT_MEMORY_COUNTER(title, var)                                \
util/stats.h:#define STAT_INT_DISTRIBUTION(title, var)                                         \
util/stats.h:#define STAT_FLOAT_DISTRIBUTION(title, var)                                             \
util/stats.h:#define STAT_PERCENT(title, numVar, denomVar)                             \
util/stats.h:#define STAT_RATIO(title, numVar, denomVar)                               \
util/stats.h:#define STAT_PIXEL_RATIO(title, numVar, denomVar)                                     \
```

**Comment by SkybuckFlying** [comment]
I think I managed to get something working in a console, but a new problem popped-up closing this issue for now.

**Comment by SkybuckFlying** [comment]
Re-opening this issue.

EXT folder was deleted, one line from PBRT.cpp removed related to threading.

Not sure if math demo code from microsoft was clean, but I tried and remove previous attempt, and now the problem with the logger seems to have returned:

Build started...
1>------ Build started: Project: MathClient, Configuration: Debug Win32 ------
1>MathClient.obj : error LNK2019: unresolved external symbol "void __cdecl pbrt::LogFatal(enum pbrt::LogLevel,char const *,int,char const *)" (?LogFatal@pbrt@@YAXW4LogLevel@1@PBDH1@Z) referenced in function "void __cdecl pbrt::LogFatal<char const (&)[4]>(enum pbrt::LogLevel,char const *,int,char const *,char const (&)[4])" (??$LogFatal@AAY03$$CBD@pbrt@@YAXW4LogLevel@0@PBDH1AAY03$$CBD@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2001: unresolved external symbol "void __cdecl pbrt::LogFatal(enum pbrt::LogLevel,char const *,int,char const *)" (?LogFatal@pbrt@@YAXW4LogLevel@1@PBDH1@Z)
1>MathClient.obj : error LNK2019: unresolved external symbol "void __cdecl pbrt::detail::stringPrintfRecursive(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,char const *)" (?stringPrintfRecursive@detail@pbrt@@YAXPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD@Z) referenced in function "void __cdecl pbrt::detail::stringPrintfRecursive<char const (&)[4]>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,char const *,char const (&)[4])" (??$stringPrintfRecursive@AAY03$$CBD$$V@detail@pbrt@@YAXPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBDAAY03$$CBD@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2001: unresolved external symbol "void __cdecl pbrt::detail::stringPrintfRecursive(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,char const *)" (?stringPrintfRecursive@detail@pbrt@@YAXPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD@Z)
1>MathClient.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pbrt::detail::copyToFormatString(char const * *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?copyToFormatString@detail@pbrt@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAPBDPAV34@@Z) referenced in function "void __cdecl pbrt::detail::stringPrintfRecursive<char const (&)[4]>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,char const *,char const (&)[4])" (??$stringPrintfRecursive@AAY03$$CBD$$V@detail@pbrt@@YAXPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBDAAY03$$CBD@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pbrt::detail::copyToFormatString(char const * *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?copyToFormatString@detail@pbrt@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAPBDPAV34@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ShutdownLogging(void)" (?ShutdownLogging@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::InitLogging(enum pbrt::LogLevel,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,bool)" (?InitLogging@pbrt@@YAXW4LogLevel@1@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N2@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: __thiscall pbrt::StatRegisterer::StatRegisterer(void (__cdecl*)(class pbrt::StatsAccumulator &),void (__cdecl*)(class pbrt::Point2<int>,int,class pbrt::PixelStatsAccumulator &))" (??0StatRegisterer@pbrt@@QAE@P6AXAAVStatsAccumulator@1@@ZP6AXV?$Point2@H@1@HAAVPixelStatsAccumulator@1@@Z@Z) referenced in function "void __cdecl pbrt::`dynamic initializer for 'STATS_REGnBufferCacheHits''(void)" (??__ESTATS_REGnBufferCacheHits@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::PrintStats(struct _iobuf *)" (?PrintStats@pbrt@@YAXPAU_iobuf@@@Z) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::StatsWritePixelImages(void)" (?StatsWritePixelImages@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "bool __cdecl pbrt::PrintCheckRare(struct _iobuf *)" (?PrintCheckRare@pbrt@@YA_NPAU_iobuf@@@Z) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ClearStats(void)" (?ClearStats@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ReportThreadStats(void)" (?ReportThreadStats@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: void __thiscall pbrt::StatsAccumulator::ReportMemoryCounter(char const *,__int64)" (?ReportMemoryCounter@StatsAccumulator@pbrt@@QAEXPBD_J@Z) referenced in function "public: __thiscall <lambda_1e5bf6f6f3c890df93debf3f59aa0eb8>::operator()(class pbrt::StatsAccumulator &)const " (??R<lambda_1e5bf6f6f3c890df93debf3f59aa0eb8>@@QBE@AAVStatsAccumulator@pbrt@@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: void __thiscall pbrt::StatsAccumulator::ReportPercentage(char const *,__int64,__int64)" (?ReportPercentage@StatsAccumulator@pbrt@@QAEXPBD_J1@Z) referenced in function "public: __thiscall <lambda_47067199a273e16e91b2fd52abb6bb65>::operator()(class pbrt::StatsAccumulator &)const " (??R<lambda_47067199a273e16e91b2fd52abb6bb65>@@QBE@AAVStatsAccumulator@pbrt@@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "class pstd::pmr::memory_resource * __cdecl pstd::pmr::new_delete_resource(void)" (?new_delete_resource@pmr@pstd@@YAPAVmemory_resource@12@XZ) referenced in function "public: __thiscall pstd::pmr::polymorphic_allocator<enum std::byte>::polymorphic_allocator<enum std::byte>(void)" (??0?$polymorphic_allocator@W4byte@std@@@pmr@pstd@@QAE@XZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl pbrt::RGBToSpectrumTable::Init(class pstd::pmr::polymorphic_allocator<enum std::byte>)" (?Init@RGBToSpectrumTable@pbrt@@SAXV?$polymorphic_allocator@W4byte@std@@@pmr@pstd@@@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl pbrt::ColorEncoding::Init(class pstd::pmr::polymorphic_allocator<enum std::byte>)" (?Init@ColorEncoding@pbrt@@SAXV?$polymorphic_allocator@W4byte@std@@@pmr@pstd@@@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::Spectra::Init(class pstd::pmr::polymorphic_allocator<enum std::byte>)" (?Init@Spectra@pbrt@@YAXV?$polymorphic_allocator@W4byte@std@@@pmr@pstd@@@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::InitBufferCaches(void)" (?InitBufferCaches@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::SuppressErrorMessages(void)" (?SuppressErrorMessages@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ErrorExit(struct pbrt::FileLoc const *,char const *)" (?ErrorExit@pbrt@@YAXPBUFileLoc@1@PBD@Z) referenced in function "void __cdecl pbrt::ErrorExit<>(char const *)" (??$ErrorExit@$$V@pbrt@@YAXPBD@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ParallelInit(int)" (?ParallelInit@pbrt@@YAXH@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ParallelCleanup(void)" (?ParallelCleanup@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "int __cdecl pbrt::AvailableCores(void)" (?AvailableCores@pbrt@@YAHXZ) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ForEachThread(class std::function<void __cdecl(void)>)" (?ForEachThread@pbrt@@YAXV?$function@$$A6AXXZ@std@@@Z) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl pbrt::Triangle::Init(class pstd::pmr::polymorphic_allocator<enum std::byte>)" (?Init@Triangle@pbrt@@SAXV?$polymorphic_allocator@W4byte@std@@@pmr@pstd@@@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl pbrt::BilinearPatch::Init(class pstd::pmr::polymorphic_allocator<enum std::byte>)" (?Init@BilinearPatch@pbrt@@SAXV?$polymorphic_allocator@W4byte@std@@@pmr@pstd@@@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl pbrt::RGBColorSpace::Init(class pstd::pmr::polymorphic_allocator<enum std::byte>)" (?Init@RGBColorSpace@pbrt@@SAXV?$polymorphic_allocator@W4byte@std@@@pmr@pstd@@@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::ConnectToDisplayServer(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?ConnectToDisplayServer@pbrt@@YAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "void __cdecl pbrt::InitPBRT(struct pbrt::PBRTOptions const &)" (?InitPBRT@pbrt@@YAXABUPBRTOptions@1@@Z)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2019: unresolved external symbol "void __cdecl pbrt::DisconnectFromDisplayServer(void)" (?DisconnectFromDisplayServer@pbrt@@YAXXZ) referenced in function "void __cdecl pbrt::CleanupPBRT(void)" (?CleanupPBRT@pbrt@@YAXXZ)
1>PBRTStaticLibrary.lib(pbrt.obj) : error LNK2001: unresolved external symbol "struct pbrt::PBRTOptions * pbrt::Options" (?Options@pbrt@@3PAUPBRTOptions@1@A)
1>E:\SourceCode\StaticLibraryTest\StaticMath\Debug\MathClient.exe : fatal error LNK1120: 30 unresolved externals
1>Done building project "MathClient.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**Comment by SkybuckFlying** [comment]
I give up on this... the complexity is too big and too many link fails.
