### ISSUE TITLE
pbrt_lib error: error C3861: '__builtin_clz': identifier not found

### ISSUE THREAD

**Issue by SkybuckFlying** [mmp/pbrt-v4#259]
I followed this walkthrough from Microsoft:

https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-static-library-cpp?view=msvc-170#CreateLibProject

(I also changed the c++ language to c++ 2017 so it matches PBRT c++ 2017 for math library and math client)

Then I repeated the steps and added the pbrt_lib project (the win32 build)

I also added the \src folder to the additional include directory settings. Should it maybe be \src\pbrt instead ?

Now I am trying to include it in the MathClient test program as follows:

Test program now looks as follows:

```
// MathClient.cpp
// compile with: cl /EHsc MathClient.cpp /link MathLibrary.lib

#include <iostream>
#include "MathLibrary.h"
#include "pbrt/pbrt.h"
#include "pbrt/options.h"

int main()
{
    double a = 7.4;
    int b = 99;

    std::cout << "a + b = " <<
        MathLibrary::Arithmetic::Add(a, b) << std::endl;
    std::cout << "a - b = " <<
        MathLibrary::Arithmetic::Subtract(a, b) << std::endl;
    std::cout << "a * b = " <<
        MathLibrary::Arithmetic::Multiply(a, b) << std::endl;
    std::cout << "a / b = " <<
        MathLibrary::Arithmetic::Divide(a, b) << std::endl;

	// experiment with pbrt
	struct pbrt::PBRTOptions blabla;
	pbrt::InitPBRT( blabla );
	pbrt::CleanupPBRT();

    return 0;
}
```

There is no CUDA compiler installed on this system. I considered it, but the current cuda compiler distribution is very very large, multiple gigabytes and probably requires a newer operating system. My operating system is windows 7 which is really nice, no down time because of windows updates. Visual Studio 2019 is being used. There is no CUDA graphics card inside this laptop.

(
It also rebuilds the pbrt_lib, is there perhaps a way to avoid this and safe time ? for now I guess it's ok so I can try some modifications, I tried commenting these "built in" since they should not be used. The weird thing was the library seemed to build ok, but when the client tried to use the library suddenly these errors popped up. (Kinda strange isn't it ? ;)) 
)

It produces the following errors:

Build started...
1>------ Build started: Project: MathClient, Configuration: Debug Win32 ------
1>MathClient.cpp
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\float.h(43,39): warning C4244: 'initializing': conversion from 'double' to 'const pbrt::Float', possible loss of data
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(44,44): warning C4305: 'initializing': truncation from 'double' to 'const pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(45,47): warning C4305: 'initializing': truncation from 'double' to 'const pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(46,48): warning C4305: 'initializing': truncation from 'double' to 'const pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(47,48): warning C4305: 'initializing': truncation from 'double' to 'const pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(48,49): warning C4305: 'initializing': truncation from 'double' to 'const pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(49,49): warning C4305: 'initializing': truncation from 'double' to 'const pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(50,47): warning C4305: 'initializing': truncation from 'double' to 'const pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(118,24): warning C4244: 'argument': conversion from 'float' to 'uint32_t', possible loss of data
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(118,47): warning C4244: 'argument': conversion from 'float' to 'uint32_t', possible loss of data
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(118,69): warning C4244: 'argument': conversion from 'float' to 'uint32_t', possible loss of data
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(137,12): warning C4244: 'return': conversion from 'uint64_t' to 'uint32_t', possible loss of data
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(270,19): warning C4244: 'return': conversion from 'int' to 'pbrt::Float', possible loss of data
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(368,59): warning C4305: 'initializing': truncation from 'double' to 'pbrt::Float'
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(410,17): error C3861: '__builtin_clz': identifier not found
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\math.h(435,17): error C3861: '__builtin_clzll': identifier not found
1>E:\SourceCode\pbrt-v4-v2\src\pbrt\util\vecmath.h(1777,27): warning C4244: 'return': conversion from 'float' to 'uint16_t', possible loss of data
1>Done building project "MathClient.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**Comment by mmp** [comment]
You are not linking in all of the libraries that pbrt normally uses.
