### ISSUE TITLE
RGB material ?

### ISSUE THREAD

**Issue by SkybuckFlying** [mmp/pbrt-v4#260]
Is it still possible to create a RGB material ? to set red, green, blue, for some kind of material property, like diffuse, matte, specular, that kind of thing ?

Alternative would be to use a red, green, blue texture... kinda silly to have to make "textures" for colors...

**Comment by mmp** [comment]
yes, that is unchanged from pbrt-v3. (I will try to have the pbrt-v4 fileformat doc done soon)
