### ISSUE TITLE
Why does scene go dark if no look at ?

### ISSUE THREAD

**Issue by SkybuckFlying** [mmp/pbrt-v4#262]
```
#LookAt 
# garbage:
#	50 40 1000
#	5 0 3
#	5 1 4
# up vector

```
Scene seems to go dark ?

Camera "orthographic"

**Comment by shadeops** [comment]
Without having a scene it is hard to know what is happening, but I suspect it might have been dark because if you had an object at the origin too the camera would have been inside of it.
