### ISSUE TITLE
Is there any way to get SurfaceInteraction information like "bool Scene::Intersect(const Ray &ray, SurfaceInteraction *isect)"?

### ISSUE THREAD

**Issue by brabbitdousha** [mmp/pbrt-v4#264]
I know I can get the Interaction information of the ```ray(o,d)``` by ```(MediumSampleWorkItem w)```,but I wanna get the Interaction information(like uv..) of ```ray(o,-d)``` at the same time for some personal computation......

It's easy to do in pbrt-v3 using ```bool Scene::Intersect(const Ray &ray, SurfaceInteraction *isect)```
Is there any way to do it now in v4?

**Comment by mmp** [comment]
In pbrt-v4 the `Scene::Intersect` functionality is now provided via the `Integrator::Intersect()` method, defined in `src/pbrt/cpu/integrators.{h,cpp}`. (That is for the CPU based integrators.) For the GPU path no such method is currently available.
