### ISSUE TITLE
Does PBRTv4 have support for "voxel grids" / "voxel volumes" ?

### ISSUE THREAD

**Issue by SkybuckFlying** [mmp/pbrt-v4#265]
Currently, I am trying to render "voxels" with pure PBRT file format. Each voxel is simply represented by a "shape sphere". This prevents me from having to use the more complex meshes/cubes/triangles/points/normals and it probably saves a lot of memory.

I do see that PBRT has some kind of integrators or acceleration structures/method. I have not tried those yet.

I would like some comments from the developers if possible, which method would be best to render voxel grids.

Does PBRT have support for voxel grids ? Would a cube made out of triangles be faster than spheres ? Or would spheres be faster, because spheres are just a point and a distance. I am also thinking of maybe putting a sphere in a box, and then using fast voxel traversal algorithm to circumvent avoid all non-hitting boxes/grid cells, and then maybe doing some kind of simple/cheap/final overlap test from center of sphere to wherever the point is in the box... but must likely a length/square root computation necessary to do it accurately, however it would cut back on the square root computations, for distance between point on ray toward the center of the sphere and to compare it to it's radius. 

Anyway if PBRT does not have "fast voxel traversal algorithm" embedded inside of it, I might be able to handle to provide some source code that could do it, would there be any interest in this ?

Further the question is: what accelerator and/or integrator would be best for my current approach where spheres are being used... which pretty much lie in a grid anyway...

I know my english is not the best, but maybe you get some of it, I will show you a screenshot of what I am busy with.

The graphics below are purely rendered with spheres, the rendering time is quite fast just 1 or 2 seconds, the most time is spent in parsing the PBRT format I guess... I will try and reduce the size of it... cause some spheres overlapping currently.

![OpenXcomFrame194-64-bitFirstCoolScreenshot](https://user-images.githubusercontent.com/34254801/169570129-8476e5fd-3968-4e6d-8c79-860d9e3a31d6.png)

**Comment by mmp** [comment]
I don't understand how you would make a voxel out of a sphere.
Your best option is probably to use 6 bilinear patches, one for each face.
pbrt already includes acceleration structures so there is no need for any additional voxel traversal code.
The choice of integrator is only dependent on which light transport effects you would like to simulate.

**Comment by SkybuckFlying** [comment]
The sphere simply replaces the voxel. Saves me the trouble of having to make a cube.

**Comment by SkybuckFlying** [comment]
Which accelerator would you recommend for the scene in the screenshot ? (These are all spheres!)
