### ISSUE TITLE
Why is one ray per pixel not enough to produce a nice image ?

### ISSUE THREAD

**Issue by SkybuckFlying** [mmp/pbrt-v4#266]
Theoretically I think one ray per pixel should be enough to produce a nice image, but this does not seem to be the case.

One possible cause is this "sampler" technique and "cone" technique and so forth.

Is there a possibility to configure PBRT so it only uses 1 ray per pixel and simply renders whatever that ray hit ?

**Comment by SkybuckFlying** [comment]
Ok I see now from this drawing over here:

https://www.reddit.com/r/raytracing/comments/rv1er1/sample_per_pixel_and_ray_per_pixel_in_ray_and/

Multiple rays can go through the same pixel and hit slightly different part of the objects. I can understand that... but I still believe if only one ray is drawn it might still give a somewhat good impression of what it might look like... as long as the ray goes through the center of the pixel or so...

**Comment by mmp** [comment]
pbrt is a path tracer. Noise at 1spp is expected.

**Comment by SkybuckFlying** [comment]
What causes the noise ?
