### ISSUE TITLE
BufferCache seems designed for an unique use

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#270]
Hi.. I have some issues when I try to embeded pbrt into an application, I think that related how BufferCaches are designed.
The first issue is with this CHECK:  https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/util/buffercache.cpp#L19
All is correct for the first render call, `intBufferCache` is really a null pointer, but not for the second render call, because `intBufferCache` is not deleted or released.

```cpp
namespace pbrt {

// BufferCache Global Definitions
BufferCache<int> *intBufferCache;
BufferCache<Point2f> *point2BufferCache;
BufferCache<Point3f> *point3BufferCache;
BufferCache<Vector3f> *vector3BufferCache;
BufferCache<Normal3f> *normal3BufferCache;

void InitBufferCaches() {
    CHECK(intBufferCache == nullptr);
    intBufferCache = new BufferCache<int>;
    point2BufferCache = new BufferCache<Point2f>;
    point3BufferCache = new BufferCache<Point3f>;
    vector3BufferCache = new BufferCache<Vector3f>;
    normal3BufferCache = new BufferCache<Normal3f>;
}

}  // namespace pbrt
```

I solved this for the CPU mode, with an explicit code to delete and set `intBufferCache` to null pointer:
```cpp
void cleanUpCaches() {
    //
    if (intBufferCache != nullptr) {
        delete intBufferCache;
        intBufferCache = nullptr; // explicit set null to solved the 'assert' issue
    }
    // use delete for the other's. Not any CHECK issue, but we need avoid the memory leak
    if (point2BufferCache != nullptr) delete point2BufferCache; 
    if (point3BufferCache  != nullptr) delete point3BufferCache;
    if (vector3BufferCache != nullptr) delete vector3BufferCache;
    if (normal3BufferCache != nullptr) delete normal3BufferCache;
}
```
But I can't manage to do the same fix for the GPU mode. I have not enough Cuda skills to solve, but I think the problem is there:
https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/pbrt.cpp#L99

@mmp any help are welcome  :)
Cheers..

**Comment by mmp** [comment]
That's one of a number of places in pbrt that more or less assumes that a single frame will be rendered and then the system will exit. If you're modifying the system for other purposes, you could just not delete and null out the buffer caches. 

For the GPU I believe that these allocators are the ones that end up being used for allocating meshes (and in turn for the `BufferCache` allocations. So alternatively you could delete those after rendering and clear out the buffer caches (I think).
