### ISSUE TITLE
Interface material blocks direct lighting (kind of)

### ISSUE THREAD

**Issue by NicNel** [mmp/pbrt-v4#271]
Hi,
I'm trying to create architectural glass like material by mixing reflected and fully transparent materials and noticed that a single interface material on window glass (right image) produces a darker image than a scene without glass mesh (left).
I'm using GPU wavefront integrator

![interface2](https://user-images.githubusercontent.com/100981393/170623573-1a1f160c-b92d-4b44-abc9-9428c9d1c1b1.jpg)

**Comment by mmp** [comment]
Nice scene!

The "interface" material is normally used for marking the boundaries between different types of participating media, though that said, it shouldn't make a difference as far as the lighting. ("thindielectric" is probably the right choice for a glass window, FWIW.)

I would like to fix this. I've tried to reproduce it by hand with a simple scene, without success. Any chance you could provide a small repro case?

**Comment by mmp** [comment]
Scratch that; I have been able to reproduce this with an area light but, intriguingly, not with an infinite light. I believe that the patch below at least mostly fixes the issue but am going to keep looking and see if there are other issues, test the other integrators, etc. That said, I'm interested to hear if this fixes it for you:

```c++
--- a/src/pbrt/wavefront/intersect.h
+++ b/src/pbrt/wavefront/intersect.h
@@ -102,7 +102,7 @@ inline PBRT_CPU_GPU void EnqueueWorkAfterIntersection(
                  r.pixelIndex);
         Ray newRay = intr.SpawnRay(r.ray.d);
         nextRayQueue->PushIndirectRay(newRay, r.depth, r.prevIntrCtx, r.beta, r.inv_w_u,
-                                      r.inv_w_l, r.lambda, r.etaScale, r.specularBounce,
+                                      r.inv_w_l, r.lambda, r.etaScale, true /*specularBounce*/,
                                       r.anyNonSpecularBounces, r.pixelIndex);
         return;
     }
```

**Comment by pbrt4bounty** [comment]
Hi..
I have here a a similar scene. The zip file include 2 .pbrt files, one with not any object in the windows, and the other with a object with 'Dielectric' material applied
[glass_danish_2.zip](https://github.com/mmp/pbrt-v4/files/8790006/glass_danish_2.zip)

Cheers..

**Comment by mmp** [comment]
Ok, I believe that this is fixed.

@NicNel never mind that change I proposed above; that's not the right fix. Please try top of tree and let me know if it's fixed for you there.

@pbrt4bounty with your scene I think the issue is different (and there is no bug): in the case with glass, then with the glass modeled with a single layer of geometry, you effectively have the ray going into a medium with index of refraction 1.5. Because the emitter is in that medium, its radiance is scaled (because radiance changes when light refracts.) You can see this by setting "eta" for "vitrage archi" to something like 1.00001, in which case the two basically match. The better thing to do is probably to use the "thindielectric" material, which is designed for using single sheets of geometry to model glass and such...

(I'm curious where this scene is from since it has many shared elements but your two versions are different.)

**Comment by pbrt4bounty** [comment]
@mmp  The scene came from a LuxCore ( forked from LuxRender, also forked from pbrt-v3) demo scenes here: https://luxcorerender.org/example-scenes/
In my case, is exported to pbrt-v4 format with my addon for Blender
Cheers..

**Comment by NicNel** [comment]
@mmp thank you! @pbrt4bounty Yes, i used a Danish Mood scene from LuxCore render as a base scene and image from [here](https://cdn.shopify.com/s/files/1/0262/3959/8658/products/MENU_Harbour_Dining_Side_Chair_Snaregade_Table_Bank_Pendant_600x.jpg?v=1587486770) as reference. I want to make scene public soon)
The solution from the comment above fixes the issue for me

**Comment by mmp** [comment]
@NicNel to be clear, the diff above (related to `specularBounce`) is not the right fix and may break other things. So don't do that, but do grab the latest version of pbrt-v4.

**Comment by NicNel** [comment]
@mmp, I got it) Now I'll try to update the files and recompile the solution

**Comment by NicNel** [comment]
@mmp Yes! Now it works as expected, thank you. Here is an updated scene with interface material on glass mesh:
![test](https://user-images.githubusercontent.com/100981393/170805608-3e171a8c-4ff3-469b-9cd1-6f76e83b6ead.png)

**Comment by NicNel** [comment]
Maybe this isn't the correct way to do so, but if I mix interface and conductor materials, the result looks as previous:

![test2](https://user-images.githubusercontent.com/100981393/170807213-c8ec6bf5-ff4b-45e9-a552-86d47a3e5d34.png)

**Comment by mmp** [comment]
Yeah, it doesn't really make sense to use the interface material as an element of "mix". As mentioned above, it's really only there to delineate the extent of participating media, so it's unclear what it would be mean for it to be mixed in with another material. I've added a check and an error message to disallow that in scene files.

**Comment by NicNel** [comment]
@mmp nice) I used interface (or none as it's called previously) material to create alpha clipped materials such as thin leafs. Replacing glass material to a reflective surface with high transparency for windows is an old trick to prevent complicated calculations (like dispersion or refractive caustic) and speed up interior rendering. I wanted to check if this helps to reduce rendering time) Is it possible to add material like "mask" material from Mitsuba in pbrt4? Or how can I implement such a type of material?

**Comment by mmp** [comment]
All shapes take an "alpha" texture that can be used to make them semi-transparent like that; something like
```
Shape "trianglemesh" [...] "float alpha" 0.5
```

You can alternatively use `"texture alpha"` for a spatially-varying mask (e.g. for a leaf made out of a quad.) I am (truly) almost done with the updated file format documentation for pbrt-v4 which will hopefully be a good resource for things like this.

**Comment by pbrt4bounty** [comment]
I have an old entry in 'issues' about this 'alpha texture' and explain how this concept is implemented in my addon:
https://github.com/mmp/pbrt-v4/issues/247
I hope this help you

**Comment by NicNel** [comment]
@pbrt4bounty oh, I missed this) @mmp Thank you for pointing it out and for your hard work on the project. 
By the way, I’m also working on a custom blender addon for practicing with python ([repo](https://github.com/NicNel/bpbrt4)) and sometimes find some things unclear, like in this issue. How can I ask about it to not annoy you?)
Can we close this thread now?)

**Comment by mmp** [comment]
@NicNel nice! Feel free to file issues if you see output from pbrt that seems wrong. And I will (finally) have the file format docs (and more updated for pbrt-v4) up on pbrt.org by the end of this weekend, so hopefully that will answer some questions as well.

Let me know when/if it would make sense to add a link to your exporter from the pbrt.org "resources" page. (Basically a question of when you feel it's complete enough to be ready for users..)

Also, if you are able to export any nice scenes to pbrt's format, it would be great to have them in the pbrt-v4-scenes repository (or available elsewhere.)

**Comment by NicNel** [comment]
@mmp Awesome, thanks! 
Actually, I'm already using addon to render common types of scenes like interiors/exteriors. There are some features that are not implemented yet (like animated entities) and some features do not work correctly (in some cases), like volumes and hairs. But for regular scenes it seems that the exporter works normally.
I'll try to clean up the code shortly, block some obvious mistakes, and message you.
As mentioned earlier, I want to make a scene with the table public and add it as an example for testing addon. I have other scenes, rendered with pbrt4, but not sure about licensing for some models, taken from the internet. I'm not published any public materials yet, any advice would be appreciated)
Exterior scene example:
![ext](https://user-images.githubusercontent.com/100981393/172087677-0a5c12e5-a152-4afe-bf43-93c46a8ce85b.jpg)

**Comment by NicNel** [comment]
Greetings!

It's been a long time since the last commit was pushed to the bpbrt4 repository. I think that blender addon is more or less stable now and it would be great if you'll decide to add the link to it on the website.
Now I'm trying to implement disney shader (kind of) for pbrt4. Source [code](https://github.com/NicNel/pbrt-v4) and comparison test images between mitsuba3 principled shader and pbrt4 disney shader available at the [link](https://github.com/NicNel/bpbrt4/tree/experimental/images). Blender addon with pbrt4 disney material node available at the [experimental](https://github.com/NicNel/bpbrt4/tree/experimental) branch.
I'm not 100% sure about the correctness of implementation, there are also some things that need to be fixed, but if it makes sense please take a look)

Best regards, NicNel
