### ISSUE TITLE
How does rgb2spec_opt.cpp work?

### ISSUE THREAD

**Issue by MyBW** [mmp/pbrt-v4#272]
Hi. I'm a rendering engineer. Recnetly,   I'm very interested in the working principle of spectral rendering.  But I can't understand  how rgb2spec_opt.cpp work. I have some knowlage about numerical analysis. Could you share some paper , blog or something else about rgb2spec_opt.cpp?

Thanks.

**Comment by mmp** [comment]
Yep! It implements the optimization described in this [paper by Jakob and Hanika](https://rgl.epfl.ch/publications/Jakob2019Spectral).
