### ISSUE TITLE
Silent MSVC annoying warnings at build time.

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#274]
I added an small commit to my branch that silent at 99% the MSVC warnings. The code is added in the /src/ext folder that is the most effective way to silent this without need to change any code in the dependencies.
Can anyone made some test to confirm that is working in other computer configurations? ( before create a pull request..)
https://github.com/TheBounty/pbrt-v4/commit/56fd6cde93f50f477866316fe0c32e74db7f90d7

Cheers..

**Comment by mmp** [comment]
Nice! It would be wonderful to have those cleaned up! If you go ahead and create a PR I can kick off the github actions builds to run it on other configurations, which should find any issues (though they seem unlikely.)

**Comment by pbrt4bounty** [comment]
Ready!!  https://github.com/mmp/pbrt-v4/pull/275

**Comment by mmp** [comment]
Thanks!
