### ISSUE TITLE
Any ETA for the book?

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#278]
I'm sorry for ask again.. but vacations is around the corner and would be great have the book to read :) (I want the 'physical' book, apart the digital version, of course)
Cheers..

**Comment by shadeops** [comment]
Looks like early next year.

https://mitpress.mit.edu/books/physically-based-rendering-fourth-edition

**Comment by pbrt4bounty** [comment]
I need more patience  :)
I bought version 3 and I loved it. Although my level of English made the task of reading it not easy, having the book and the code helped me a lot to understand the concepts.
Thanks for answer!

**Comment by mmp** [comment]
Yep, good sleuthing--printed books in Feb 2023 (and that is, finally, a solid date.) We should have more to say about the online version and possibly a early preview of parts of it within the next week or so (at which point I'll update the website, etc..)
