### ISSUE TITLE
Realistic Camera, 'aperture' shape error: always find for a file

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#280]
Hi.. I found a problem with Realistic Camera when set the 'aperture' shape. The current code find for a file in the first term and show a message error when the file don't exist, stoping the render:
`Error: C:\tmp\goss\square: no support for reading images with this extension`

https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/cameras.cpp#L1336
A possible solution is added an small code to compare the provided name and, if don't match with a valid shape, search for a file using `ResolveFilename()`
```cpp
std::string apertureName = parameters.GetOneString("aperture", "");
if (apertureName != "star" && apertureName != "pentagon" &&
    apertureName != "gaussian" && apertureName != "square")
    apertureName = ResolveFilename(apertureName);
```
Now is working properly, build under Windows 10
Cheers..

**Comment by shadeops** [comment]
Can you attach an example pbrt scene file?

A scene with
```
Camera "realistic" "string aperture" [ "square" ] "string lensfile" [ ",/pbrt-v4-scenes/lenses/dgauss.50mm.dat" ]
```
Was working for me (if I had a file on disk named "square" not).

**Comment by shadeops** [comment]
Ah was able to reproduce it. I was invoking pbrt in the same directory as the scene so the searchDirectory was empty
https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/util/file.cpp#L70

**Comment by pbrt4bounty** [comment]
This looks great to improve how ResolveFilename works, but I have a question for this specific problem:
 - why call a lookup function for a valid path, when we're explicitly passing a value that doesn't involve looking for a file? To me, it makes more sense to first check that the passed value doesn't require it to resolve to a valid path.

Anyway, good job!

**Comment by shadeops** [comment]
> This brings us to my previous question: not it is better to first check if the passed value is a valid string, and only call ResolveFilename if it is not or is a file, checking extension, by example..??

The idea was to prevent ResolveFilename from core dumping due to realpath() throwing a std::runtime_error when there is a missing file (on Linux). That way the calling location can make a decision about what to do if the file is missing or not.

For example, with #281 if we intentionally provide a bad path to lensfile we get this:
```
Error: dgauss.50mm.dat.blah: unable to open file
Error: Downloads/tmp.pbrt:7:0: Error reading lens specification file "dgauss.50mm.dat.blah".
Error: Downloads/tmp.pbrt:7:0: realistic: unable to create camera.
```

However with master 2701ba6 we instead get 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Internal error in realpath(): No such file or directory
Aborted (core dumped)
```

Ignoring how ResolveFilename works, since there is already a conditional for each aperture type, you can move the ResolveFilename to where the on disk branch is checked, as in #282.

I'm not sure why #281 did not work for you, especially since the error is printing the search path `c:\test` and not `square`.

**Comment by pbrt4bounty** [comment]
```
I'm not sure why https://github.com/mmp/pbrt-v4/pull/281 did not work for you, especially since the error is printing the search path c:\test and not square.
```

Can test yourself using the same cases that I uses above:
 - uses "string aperture" [ "square" ] 
 - move pbrt.exe to 'c:/test/' and call using the absolute path 'c:/test/pbrt.exe c:/test/tmp.pbrt' and check the console
 - move pbrt.exe to 'c:/test/' and call using 'c:/test/pbrt.exe tmp.pbrt' and check the console

**Comment by pbrt4bounty** [comment]
Btw.. I don't says that your code don't work or is not an improvement, I says that don't work in some specific cases like this.
For the record..

**Comment by shadeops** [comment]
I understand your example now, thanks! You are right, #281 alone isn't won't address cases where you might have an actual file on disk called square or star etc.
