### ISSUE TITLE
The name for 'density' and 'temperature' grid are hardcoded.

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#287]
Hi... I discovered just now that the names of the `density` and `temperature` grids are hard coded, this somewhat limits the .nvdb files you can use if the file doesn't use a 'standard' name for these grids. I added a small pull request that fixes this limitation.:  https://github.com/mmp/pbrt-v4/pull/286
I hope it is an interesting contribution to add.
Cheers..

**Comment by mmp** [comment]
Thanks for the PR--merged!
