### ISSUE TITLE
pbrt-4 won't compile on Mac M1

### ISSUE THREAD

**Issue by ChristianWiele** [mmp/pbrt-v4#291]
Hi,

when trying to build v4 on my Mac M1, I get the error "unknown target CPU 'vortex'". v3 works fine, and v4 also builds fine on my Linux machine.

Christian

**Comment by oscarbg** [comment]
+1

**Comment by mmp** [comment]
Can you say more about your version of xcode and OSX and paste your CMakeOutput.log? (FWIW I've been compiling v4 on a M1 for months now.)

This may be related: https://gitlab.kitware.com/cmake/cmake/-/issues/22484

**Comment by ChristianWiele** [comment]
I am on OSX 12.5.1 and Xcode 13.4.1
Attaching the cmake output:
[CMakeOutput.log](https://github.com/mmp/pbrt-v4/files/9430024/CMakeOutput.log)

**Comment by ChristianWiele** [comment]
Just update cmake to 3.24.1, and now it compiles fine. 
Thanks for the support. Closing this issue.
