### ISSUE TITLE
BDPT visualize strategies result issue

### ISSUE THREAD

**Issue by ksgfk** [mmp/pbrt-v4#299]
Hi. I have a problem about enable 'visualizestrategies' in BDPT. 

The output is (I made them as a pyramid):
![gold](https://user-images.githubusercontent.com/37179748/197402149-84cd8289-69b5-43d4-b83b-fede3a3f8b11.png)

Many parts are completely black. I think it's a bug.

The scene is 
[veach-bidir-pbrt.zip](https://github.com/mmp/pbrt-v4/files/9846970/veach-bidir-pbrt.zip)

**Comment by pbrt4bounty** [comment]
Can you ellaborate a bit how you obtain this results. Here, your shared scene is rendered OK.
![veach-bidir](https://user-images.githubusercontent.com/73945652/198844359-866acd64-634e-43f1-a7a8-26c4ff0b01cd.png)
Cheers..

**Comment by ksgfk** [comment]
Sorry, I forgot to turn on the option ‘visualizestrategies’ in the scene file
The current scene file is:
```
Integrator "bdpt"
    "integer maxdepth" [ 5 ]
    "bool visualizestrategies" [ true ]
Transform [ 0.00502469 -0.00467005 -0.999977 -0 -0 0.999989 -0.00467011 -0 -0.999987 -0.0000233837 -0.00500703 -0 -0.0699916 -3.9759 16.2341 1  ]
Sampler "independent"
    "integer pixelsamples" [ 8 ]
PixelFilter "box"
    "float xradius" [ 1 ]
    "float yradius" [ 1 ]
Film "rgb"
    "string filename" [ "veach-bidir.exr" ]
    "integer yresolution" [ 1024 ]
    "integer xresolution" [ 1024 ]
Camera "perspective"
    "float fov" [ 35 ]


WorldBegin

MakeNamedMaterial "Diffuse"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.5 0.5 0.5 ]
MakeNamedMaterial "Glass"
    "string type" [ "dielectric" ]
    "float eta" [ 1.5 ]
    "bool remaproughness" [ false ]
MakeNamedMaterial "Lamp"
    "string type" [ "conductor" ]
    "float vroughness" [ 0.25 ]
    "float uroughness" [ 0.25 ]
    "bool remaproughness" [ false ]
    "rgb k" [ 3.032326 2.056108 1.616293 ]
    "rgb eta" [ 2.865601 2.119182 1.940077 ]
MakeNamedMaterial "Wood"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.32963 0.257976 0.150292 ]
NamedMaterial "Lamp"
Shape "plymesh"
    "string filename" [ "models/Mesh007.ply" ]
NamedMaterial "Diffuse"
Shape "plymesh"
    "string filename" [ "models/Mesh004.ply" ]

AttributeBegin
    AreaLightSource "diffuse"
        "rgb L" [ 523.2578 523.2578 523.2578 ]
    Shape "trianglemesh"
        "point2 uv" [ 0 0 1 0 1 1 0 1 
            ]
        "normal N" [ 1.58516e-7 1 6.92894e-15 1.58516e-7 1 6.92894e-15 1.58516e-7 
                     1 6.92894e-15 1.58516e-7 1 6.92894e-15 ]
        "point3 P" [ -2.75736 6 2.31365 -2.75736 6 2.86515 -2.20586 6 2.86515 -2.20586 
                     6 2.31365 ]
        "integer indices" [ 0 1 2 0 2 3 ]
AttributeEnd

AttributeBegin
    AreaLightSource "diffuse"
        "rgb L" [ 12048.179 8605.842 6196.206 ]
    Shape "trianglemesh"
        "point2 uv" [ 0 0 1 0 1 1 0 1 
            ]
        "normal N" [ 0.070781 -0.429239 0.900413 0.070781 -0.429239 0.900413 0.070781 
                     -0.429239 0.900413 0.070781 -0.429239 0.900413 ]
        "point3 P" [ -2.74778 5.17227 -3.73363 -2.768 5.05027 -3.7902 -2.63386 5.03607 
                     -3.80751 -2.61364 5.15807 -3.75094 ]
        "integer indices" [ 0 1 2 0 2 3 ]
AttributeEnd
NamedMaterial "Lamp"
Shape "plymesh"
    "string filename" [ "models/Mesh001.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh005.ply" ]
NamedMaterial "Diffuse"
Shape "plymesh"
    "string filename" [ "models/Mesh008.ply" ]
NamedMaterial "Glass"
Shape "plymesh"
    "string filename" [ "models/Mesh002.ply" ]
NamedMaterial "Diffuse"
Shape "plymesh"
    "string filename" [ "models/Mesh011.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh003.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh009.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh006.ply" ]
NamedMaterial "Wood"
Shape "plymesh"
    "string filename" [ "models/Mesh000.ply" ]
NamedMaterial "Diffuse"
Shape "plymesh"
    "string filename" [ "models/Mesh010.ply" ]
```
After rendering, the result file `veach-bidir.exr` is OK.
But, other files, named like `bdpt_d00_s00_t02.exr`. They are the results of the sampling strategy.
Most of them are completely black.
![QQ图片20221030012906](https://user-images.githubusercontent.com/37179748/198845188-73e5fbfc-e603-4554-8580-1b5dadd6d792.png)
Here is the size of some results. 9KB is completely black.

**Comment by pbrt4bounty** [comment]
I'm not sure I understand how you get those intermediate files and the importance of the content of some being more or less black. I think what matters is the final render result and this it looks correct. But maybe @mmp can explain better what is happen.

**Comment by ksgfk** [comment]
I think the problem is at [https://github.com/mmp/pbrt-v4/blob/accfbcba62b44d364774954805757fa1dc28760c/src/pbrt/cpu/integrators.cpp#L2273](https://github.com/mmp/pbrt-v4/blob/accfbcba62b44d364774954805757fa1dc28760c/src/pbrt/cpu/integrators.cpp#L2273)
In pbrt3, the variable `pFilmNew` is assigned by `pFilm`. `pFilm` is position on the image
But in pbrt4, `pFilmNew` is only assigned by t=1 [https://github.com/mmp/pbrt-v4/blob/accfbcba62b44d364774954805757fa1dc28760c/src/pbrt/cpu/integrators.cpp#L2328](https://github.com/mmp/pbrt-v4/blob/accfbcba62b44d364774954805757fa1dc28760c/src/pbrt/cpu/integrators.cpp#L2328)
So, only the strategies of t=1, that is connecting light sub path to camera, can output on result files

**Comment by mmp** [comment]
Good diagnosis, @ksgfk, and sorry for the trouble! I've pushed a fix for this (mostly); it doesn't work fully correctly if the lens has a finite aperture, but hopefully that isn't necessary for your requirements.
