### ISSUE TITLE
obj2pbrt needs to be updated for the new materials

### ISSUE THREAD

**Issue by mmp** [mmp/pbrt-v4#3]
The pbrt files it generates currently are invalid for pbrt-v4...

**Comment by povmaniaco** [comment]
Hi @mmp  I can review this issue. I am using a derived version of this code for my own project.
Cheers..

**Comment by povmaniaco** [comment]
Ths first fix is simple change from 'point2 st' to  'point2 uv'..
```diff
diff --git "a/src/pbrt/cmd/obj2pbrt.cpp" "b/src/pbrt/cmd/obj2pbrt.cpp"
index 39cd283..f508626 100644
--- "a/src/pbrt/cmd/obj2pbrt.cpp"
+++ "b/src/pbrt/cmd/obj2pbrt.cpp"
@@ -1591,7 +1591,7 @@ int main(int argc, char *argv[]) {
                 fprintf(f, "]\n");
             }
             if (!st.empty()) {
-                fprintf(f, "  \"point2 st\" [ \n");
+                fprintf(f, "  \"point2 uv\" [ \n");
                 for (Point2f tex : st)
                     fprintf(f, "\t%.10g %.10g\n", tex.x, tex.y);
                 fprintf(f, "]\n");
 ```

**Comment by povmaniaco** [comment]
The other fix are related with the default material use in obj2pbrt ( uber) that are is deprecated.. @mmp what do you think is the best candidate to use now?
Cheers..

**Comment by mmp** [comment]
Generally speaking I agree that coated diffuse covers a lot of it.  The full OBJ material model has all sorts of non-physical functionality (https://en.wikipedia.org/wiki/Wavefront_.obj_file#Material_template_library), which makes it tricky. 

e.g. illum model 3 definitely sounds like coated diffuse. 4 is probably a dielectric interface with 0 roughness, 5 is probably coated diffuse again. 6,7 again a dielectric interface.  I guess it boils down to either coated diffuse if it's reflective and a dielectric interface if it's transmissive.  pbrt's dielectric interface BxDF no longer allows specifying a color, so that stuff will be lost..

**Comment by mmp** [comment]
No worries. Merged just now. Thanks!

**Comment by povmaniaco** [comment]
Nice.. I hope to find a bit time this weekend to continue fixing some more things.

**Comment by mmp** [comment]
This is now moot, given cd47b40.
