### ISSUE TITLE
issues/oddities in DielectricInterfaceBxDF 

### ISSUE THREAD

**Issue by BrianSharpe** [mmp/pbrt-v4#30]
Hi there
I've noticed some oddities in DielectricInterfaceBxDF 

1) 
DielectricInterfaceBxDF::Sample_f() is testing for mfDistrib.EffectivelySpecular() twice.
Once at the start of the function.
And again (redundantly) when it goes to return the BSDFSample in the non-delta part of the function

2)
There appears to be a missing `Sqr(etap)` component at the bottom of DielectricInterfaceBxDF::f()

PBRTv3 had this for microfacet transmission (ie MicrofacetTransmission::f())
```
Float sqrtDenom = Dot(wo, wh) + eta * Dot(wi, wh);
Float factor = (mode == TransportMode::Radiance) ? (1 / eta) : 1;
return (Spectrum(1.f) - F) * T *
           std::abs(distribution->D(wh) * distribution->G(wo, wi) * eta * eta *
                    AbsDot(wi, wh) * AbsDot(wo, wh) * factor * factor /
                    (cosThetaI * cosThetaO * sqrtDenom * sqrtDenom));
```
Noting that `eta*eta` and `factor*factor` components cancel out when in Radiance transport mode.

In PBRTv4, there is this at the bottom of MicrofacetTransmission::f()
```
Float sqrtDenom = Dot(wo, wh) + etap * Dot(wi, wh);
Float factor = (mode == TransportMode::Radiance) ? Sqr(1 / etap) : 1;
return SampledSpectrum((1 - F) * factor *
                                   std::abs(mfDistrib.D(wh) * mfDistrib.G(wo, wi) *
                                            AbsDot(wi, wh) * AbsDot(wo, wh) /
                                            (cosTheta_i * cosTheta_o * Sqr(sqrtDenom))));
```
We can see its missing `etap*etap` comparing to PBRTv3.  

I can see that if factor was changed to the following, then it would match PBRTv3 again.  Was that the intention?
`
Float factor = (mode == TransportMode::Radiance) ? 1 : Sqr(etap);
`

I also see `Sqr(etap)` has been removed from the PDF calculation too, so I'm assuming this has been a conscious decision.  This may not be a bug, just thought I'd raise it as it looked like it could be.

thanks

**Comment by mmp** [comment]
Good eye! For 1, I just pushed a fix to clean that up.

For 2., I believe that the code is correct (but with the caveat that the microfacet transmission code has been the bane of my existence and has repeatedly been buggy in various ways.) The key is the difference between eta in pbrt-v3 and etap in pbrt-v4. In v4, we're trying to more consistently use relative (incident / outgoing) IOR for eta values. Thus, I'm pretty sure that those two different eta values are the reciprocals of each other and that that coupled with cancelling out the eta*eta and then accounting for that in `factor` all works out for those to have the same behavior in the end.

**Comment by BrianSharpe** [comment]
ok cheers!  
cloing the issue now
