### ISSUE TITLE
Imgtool denoise looks for variance channel with wrong name.

### ISSUE THREAD

**Issue by Kerdek** [mmp/pbrt-v4#300]
Recent pbrt-v4 gbuffer outputs contain channels named "Variance.R" etc, but imgtool can't find them because it's looking for a channel named "rgbVariance". I tried to patch this but I'm not sure if it's right because i don't know if the denoise filter looks at all three channels correctly.

Also wishlist item: some file format that just records each sample at the sensor, no bucketing. Resumable renders.

<3

**Comment by Kerdek** [comment]
have a cat
![scene](https://user-images.githubusercontent.com/8801228/197906028-4be04786-efee-4f47-a569-c2780631aada.png)

**Comment by pbrt4bounty** [comment]
After a few bad attempt to create a patch, now is ready.
@mmp , As @Kerdek says, the channel names are different when is created into film.cpp file: https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/film.cpp#L703
and how is called from imgtool.cpp file: https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/cmd/imgtool.cpp#L2427
This pull request fix this difference and avoid the error from denoise about missing 'rgbVariance' channels.
Cheers..

**Comment by mmp** [comment]
Thanks for the PR, @pbrt4bounty !

And, @Kerdek, wishlist items noted!
