### ISSUE TITLE
The mathematical model of "coateddiffuse" material

### ISSUE THREAD

**Issue by fitzzc** [mmp/pbrt-v4#303]
Hello~
I have used  "coateddiffuse" material, tried a few different parameters, and got a good rendered result/image. However, this material is not included in  pbrt-v3 book, and I am really curious about how to describe "coateddiffuse" material in mathematical language.  I would appreciate it if you could give me some guidance or reference about the maths description of this material.

**Comment by pbrt4bounty** [comment]
Hi.. maybe a good point to take a look is here: https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/materials.cpp#L253
Cheers..

**Comment by mmp** [comment]
It's an implementation of Guo et al's 2018 paper, Position-Free Monte Carlo Simulation for Arbitrary Layered BSDFs.

https://shuangz.com/projects/layered-sa18/
