### ISSUE TITLE
[Question] Memory requirements for rendering the kroken scene

### ISSUE THREAD

**Issue by knightcrawler25** [mmp/pbrt-v4#317]
Hey,

I was trying to render the [kroken](https://github.com/mmp/pbrt-v4-scenes/tree/master/kroken/) scene on the CPU with 32 GB of RAM and pbrt peaks out the memory and quietly stops processing the scene after a while ([log.txt](https://github.com/mmp/pbrt-v4/files/10351533/log.txt)). After removing the displacement textures, the scene renders and consumes about 8 GB.

I was wondering what the requirements were for rendering with all the bells and whistles and if its even doable on a 8/16 GB GPU? My RTX 3060 Ti (8 GB) gives up even without the displacement textures :D

**Comment by mmp** [comment]
On the CPU, it looks like it's about 44GB to render it as is, though memory use peaks around 56GB while the BVHs are being built before rendering. On the GPU, it looks like it's about 23GB.

Memory use can be tuned using the `--displacement-edge-scale` command-line option, which adjusts the tessellation rate. With a value of 5, CPU memory usage is about 14GB and it's about 9GB on the GPU.

(There should probably be a FAQ about `--displacement-edge-scale`...)

**Comment by knightcrawler25** [comment]
Ah I didn't realize there was an option to control tessellation. Works perfectly now :) 

Thanks for sharing the stats as well.
