### ISSUE TITLE
`imgtool denoise` not working properly?

### ISSUE THREAD

**Issue by alkanen** [mmp/pbrt-v4#319]
I tried rendering the pbrt-scene `explosive` using a gbuffer film in order to be able to denoise it.  The output from pbrt looks just fine (and noisy of course), but the output from imgtool looks like the attached image.

I modified `explosion.pbrt` to use "gbuffer" rather than "rbg" as film type, and then ran pbrt like this:

`pbrt explosion.pbrt --spp 8192`

followed by a denoising pass:

`imgtool denoise explosion.exr --outfile explosion_gbuffer_8192_denoised.png`

![explosion_gbuffer_8192_denoised](https://user-images.githubusercontent.com/12019207/212050108-9f1cefbd-7fb3-4727-b1d8-56b6109182d5.png)

**Comment by mmp** [comment]
Ah, yes--imgtool denoise expects auxiliary buffers with the per-pixel surface normal, albedo, etc., and those aren't available with volumetrics. More generally, that functionality is somewhat incomplete (evidently!) and wasn't included in the book in the end. I've therefore removed it in b1603296ce47e0c7e688674ea895e4e640cf3502.

**Comment by alkanen** [comment]
Ah, I see.

Perhaps that should be mentioned in the help for the imgtool help text? Just to avoid people like me thinking it's a bug I mean =)

**Comment by alkanen** [comment]
Oh, scrap that last paragraph.  I didn't realise you meant that you'd removed denoise completely from imgtool.
