### ISSUE TITLE
How do you generate a scene using C++ code?

### ISSUE THREAD

**Issue by mmmovania** [mmp/pbrt-v4#320]
I was wondering how one would go about setting up pbrt v4 through code without using the scene file? I tried looking at the documentation and user guide and https://pbrt.org/fileformat-v4 but I only saw pbrt scene file examples. I did find out by peeking into the pbrt v4 code that we can use the BasicScene/BasicSceneBuilder class to help in setting up the code as shown here: https://github.com/mmmovania/PBRTv4_Tests/blob/main/SimpleScene/SimpleScene/AdvancedScene.cpp but shouldnt there be a better way? Asking as I could not find anything in the docs or on the internet.

**Comment by pbrt4bounty** [comment]
Yes.. this way seems not very optimized. I think a best approach are write any kinda of small 'API' interface to export some create scene functions. I can see that the 'api.cc' and 'api.h' files aren't update for this version.
Maybe @mmp can add some comment or tip here about this.. :)

**Comment by pbrt4bounty** [comment]
Meanwhile you have a few options to optimize a bit your code: 
```cpp
void ParamsSetFloat(ParsedParameter& param, std::string name, Float value) {
    //-
    param.name = name;
    param.type = "float";
    param.AddFloat(value);
}
void ParamsSetInt(ParsedParameter& param, std::string name, int value) {
    //
    param.name = name;
    param.type = "integer";
    param.AddInt(value);
}
```
Then you can use some like this to set each param per-type
```cpp
    ParsedParameterVector parsed; // reusable container after 'clear()'
    //Camera params
    std::unique_ptr< ParsedParameter> params(new ParsedParameter(loc)); // smart pointer to forget use 'delete'?
    ParamsSetFloat(*params, "fov", 39.60);
    parsed.push_back(params.get());
    builder.Camera("perspective", parsed, loc);
    parsed.clear();
```
I hope this help you a bit..
Cheers..

**Comment by mmmovania** [comment]
Thanks for your response @pbrt4bounty. Awaiting response from @mmp.

**Comment by raymond-chetty** [comment]
Sort of off topic, but possibly related... It might be worth linking to the user manual and scene description language definition in the README.md for this project.

Project: https://github.com/mmp/pbrt-v4

* https://pbrt.org/users-guide-v4
* https://pbrt.org/fileformat-v4

There is also the appendix
* https://www.pbr-book.org/3ed-2018/Scene_Description_Interface/Scene_Definition

Also,

1. I haven't thoroughly reviewed the book, but it might be worth translating the slide course material, projects etc. into pbrt and maybe add a translator for scene descriptions written in slide. If it hasn't been already.

* https://people.eecs.berkeley.edu/~ug/slide/ 
* https://people.eecs.berkeley.edu/~ug/slide/pipeline/assignments/outline.shtml
* https://people.eecs.berkeley.edu/~ug/slide/pipeline/assignments/assignments.shtml
* https://assimp-docs.readthedocs.io/en/v5.1.0/usage/use_the_lib.html?highlight=pbrt#exporting-models


2. I think there is a broken link in the Disney cloud rendering example. The data looks like it still exists through another route. Here is the link. https://disney-animation.s3.amazonaws.com/uploads/production/data_set_asset/1/asset/Cloud_Readme.pdf


This comment is not necessarily an endorsement of any person place or thing in particular :)

**Comment by mmp** [comment]
@raymond-chetty good suggestion about the README and thanks for the heads up about the Disney cloud link--done.

The scene description interfaces aren't really designed to be used directly so they're a little clunky. You can go ahead and make your own parameter vectors and SceneEntity objects, or you can also create the underlying objects directly (i.e., if you want a sphere, call `new Sphere` and pass the desired arguments to the constructor. That's used in [some of the pbrt unit tests](https://github.com/mmp/pbrt-v4/blob/967aa48d113abc6e774d09fb2f52b28db2fe6a75/src/pbrt/cpu/integrators_test.cpp#L75), for example.
