### ISSUE TITLE
Clarification about media interfaces

### ISSUE THREAD

**Issue by hblasins** [mmp/pbrt-v4#322]
The PBRT-v4 file format description lists a special material of type `interface` that is mean to indicate that a surface is meant to be ignored when calculating ray intersections. However when going over the section on 'Participating Media,' one can read:

> "Depending on the application, it can be useful to use a shape purely to determine the spatial extent of media, but to not want the shape to appear in the scene. In this case, if "none" is specified for the shape's material, it will be ignored in ray intersection calculations (except for allowing the current medium to be updated.)"

Is one syntax preferred over the other, or are both exactly equivalent?

**Comment by shadeops** [comment]
I suspect just a typo, they should do the same thing. If you use "none" you'll just get a deprecation warning telling you to use "interface".

I believe "none" still exists to provide backwards compatibility with older scenes.

**Comment by mmp** [comment]
> I believe "none" still exists to provide backwards compatibility with older scenes.

Indeed! I've just pushed a fix to the website to fix that--may be a little while before all of the caches are updated. Thanks!
