### ISSUE TITLE
Questions about the sampler in wavefront

### ISSUE THREAD

**Issue by TrevorPhilipss** [mmp/pbrt-v4#323]
In ImageTileIntegrator::Render，the sampler is wrapped by ThreadLocal to avoid data race between multiple CPU threads. However, in  WavefrontPathIntegrator::GenerateCameraRays, the sampler is used directly, this part is in ForAllQueued and will eventually be executed by GPUParallelFor or ParallelFor, this seems to cause the data race.

**Comment by mmp** [comment]
Indeed, but note that the sampler is stack allocated there: https://github.com/mmp/pbrt-v4/blob/297ea2e9f3d5322059be2567803d7bbccde98834/src/pbrt/wavefront/camera.cpp#L50.

There are some template shenanigans involved to specialize the generate rays function over all sampler types, the appropriate one is dispatched from the CPU, and then the GPU code can run with the sampler type known and make a copy of the global sampler on its stack. (All that and the motivations are discussed in the book; hopefully it will be more clear when the book is out!)
