### ISSUE TITLE
Underwater Scene

### ISSUE THREAD

**Issue by lucasamparo** [mmp/pbrt-v4#328]
Hi everyone. I did not find a community for this library, so I decided to ask here.

Are there some examples or tutorials for underwater scene rendering?

Thanks.

**Comment by pbrt4bounty** [comment]
Hi.. A simple search in google show a few scenes and tutorials.. like this:
https://www.youtube.com/watch?v=mAJCvx6CHMo
Cheers..

**Comment by pbrt4bounty** [comment]
I think it's difficult that someone has written a tutorial on this type of renders with Pbrt-v4 since the book was published just yesterday and I don't know of a complete implementation of this engine for any DCC's except maybe for Blender.
Cheers..

**Comment by mmp** [comment]
There is no pbrt specific documentation for rendering underwater scenes. In general you will probably want to have some sort of participating media under the water to model the fine particles in the water. Sampling lighting effectively may be tricky with the standard volumetric path tracer; a bidirectional algorithm the the BDPT integrator or perhaps the Metropolis integrator (which is built on top of the BDPT one) may be your best bet.
