### ISSUE TITLE
triangle meshes aren't rendered with the GPU path on Windows

### ISSUE THREAD

**Issue by Reev970** [mmp/pbrt-v4#329]
i tried to render some scenes(on the GPU) , then i got an image is black  (or only the background was rendered ) , there were no models on it.

**Comment by Reev970** [comment]
CUDA 11.4 , OptiX 7.4 , win10 , MSVC2019

**Comment by mmp** [comment]
1. What scene did you try to render?
2. What is the command that you entered?
3. What output did pbrt print on the console?

**Comment by Reev970** [comment]
For example ,

![TungstenRender](https://user-images.githubusercontent.com/128742476/227953061-c3ac275a-fdd4-43a1-80a5-f6b95c0bec46.png)

C:\Pbrt_v4\pbrt-v4\out\build\x64-Debug\Release>pbrt --gpu C:\Pbrt_v4\dragon\scene-v4.pbrt

pbrt version 4 (built Mar 27 2023 at 17:31:39)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++]  (0.7s)

**Comment by Reev970** [comment]
![crown](https://user-images.githubusercontent.com/128742476/227967074-a5afc631-04bf-48f5-9f7a-f866e9c0886b.png)
(From https://github.com/mmp/pbrt-v4-scenes/tree/master/crown/)

![crown](https://user-images.githubusercontent.com/128742476/227967231-535a06fd-dc56-453d-ae68-c8ff9332fd85.png)

**Comment by pbrt4bounty** [comment]
Hi.. Are you try to render in CPU mode? I never use the debug mode here.. :)

**Comment by Reev970** [comment]
> Hi.. Can you to try to render in CPU mode? By other side, I never use the debug mode here.. :)

when rendering on the CPU , the image is correct , there should be something wrong with my GPU mode (but the [simple example scene](https://pbrt.org/fileformat-v4) has a normal result)

**Comment by Reev970** [comment]
> Yes, most surely. It would be easier to help you if you get a debug file and share it here. C:\Pbrt_v4\pbrt-v4\out\build\x64-Debug\Release>pbrt --log-level "verbose" --log-file C:/Pbrt_v4/error.txt --gpu C:\Pbrt_v4\dragon\scene-v4.pbrt Cheers..

here is the log file , [error.txt](https://github.com/mmp/pbrt-v4/files/11101253/error.tx

**Comment by mmp** [comment]
> ![crown](https://user-images.githubusercontent.com/128742476/227967074-a5afc631-04bf-48f5-9f7a-f866e9c0886b.png) (From https://github.com/mmp/pbrt-v4-scenes/tree/master/crown/)
> 
> ![crown](https://user-images.githubusercontent.com/128742476/227967231-535a06fd-dc56-453d-ae68-c8ff9332fd85.png)

What are these two images showing?

Everything looks reasonable in the log file that you posted. Can you provide a full repro case, including the scene, etc?

**Comment by Reev970** [comment]
> What are these two images showing?
The first one is correct , the second one is what i rendered. 

> Can you provide a full repro case, including the scene, etc?
Sorry...i don't know how to provide a right repro case.

Cmake output
`1> CMake generation started for configuration: 'x64-Debug'.
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 16 2019" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Release" -DCMAKE_INSTALL_PREFIX:PATH="C:\Pbrt_v4\pbrt-v4\out\install\x64-Debug" -DPBRT_OPTIX7_PATH:PATH="C:/ProgramData/NVIDIA Corporation/OptiX SDK 7.4.0" -DPBRT_GPU_SHADER_MODEL:STRING="sm_86"  "C:\Pbrt_v4\pbrt-v4" 2>&1"
1> Working directory: C:\Pbrt_v4\pbrt-v4\out\build\x64-Debug
1> [CMake] -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
1> [CMake] -- OpenEXR at commit: 5cfb5dab6dfada731586b0281bdb15ee75e26782
1> [CMake] -- OpenVDB at commit: 414bed84c2fc22e188eac7b611aa85c7edd7a5a9
1> [CMake] -- Ptex at commit: 4cd8e9a6db2b06e478dfbbd8c26eb6df97f84483
1> [CMake] -- double-conversion at commit: cc1f75a114aca8d2af69f73a5a959aecbab0e87a
1> [CMake] -- filesystem at commit: c5f9de30142453eb3c6fe991e82dfc2583373116
1> [CMake] -- glfw at commit: 4cb36872a5fe448c205d0b46f0e8c8b57530cfe0
1> [CMake] -- libdeflate at commit: 1fd0bea6ca2073c68493632dafc4b1ddda1bcbc3
1> [CMake] -- lodepng at commit: 8c6a9e30576f07bf470ad6f09458a2dcd7a6a84a
1> [CMake] -- qoi at commit: 028c75fd26e5e0758c7c711216c00404994c1ad3
1> [CMake] -- stb at commit: af1a5bc352164740c1cc1354942b1c6b72eacb8a
1> [CMake] -- utf8proc at commit: 2484e2ed5e1d9c19edcccf392a7d9920ad90dfaf
1> [CMake] -- zlib at commit: 54d591eabf9fe0e84c725638f8d5d8d202a093fa
1> [CMake] -- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
1> [CMake] CMake Deprecation Warning at src/ext/zlib/CMakeLists.txt:1 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 2.8.12 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Could NOT find Imath (missing: Imath_DIR)
1> [CMake] -- Could NOT find OpenEXR: Found unsuitable version "1.6.1", but required is at least "2.3" (found ILMBASE_INCLUDE_PATH-NOTFOUND)
1> [CMake] -- OpenEXR not found; building it from scratch.
1> [CMake] -- Configure ILMBASE Version: 2.5.3 Lib API: 25.0.2
1> [CMake] -- WARNING pkg-config generation disabled
1> [CMake] -- Configure OpenEXR Version: 2.5.3 Lib API: 25.0.2
1> [CMake] -- clang-format not found.
1> [CMake] CMake Deprecation Warning at src/ext/ptex/CMakeLists.txt:1 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 2.8.12 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
1> [CMake] -- Including Win32 support
1> [CMake] -- Unable to find -lprofiler
1> [CMake] -- Found CUDA: 11.4.48
1> [CMake] -- Specified CUDA Architecture: sm_86
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: C:/Pbrt_v4/pbrt-v4/out/build/x64-Debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted toolchain configurations.
1> Extracted includes paths.
1> CMake generation finished.
`

Scene
[dragon.zip](https://github.com/mmp/pbrt-v4/files/11103748/dragon.zip)
`Integrator "path"
    "integer maxdepth" [ 17 ]
Transform [ 0.678116 -0.167853 -0.715531 -0 -0 0.973571 -0.228385 -0 -0.734955 -0.154871 -0.660194 -0 -0.554465 -6.29907 82.2988 1  ]
Sampler "sobol"
    "integer pixelsamples" [ 64 ]
PixelFilter "triangle"
    "float xradius" [ 1 ]
    "float yradius" [ 1 ]
Film "rgb"
    "string filename" [ "dragon.png" ]
    "integer yresolution" [ 720 ]
    "integer xresolution" [ 1280 ]
Camera "perspective"
    "float fov" [ 20.114292 ]


WorldBegin

MakeNamedMaterial "GroundInner"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.456263 0.456263 0.456263 ]
MakeNamedMaterial "GroundOuter"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.456263 0.456263 0.456263 ]
MakeNamedMaterial "Cloth"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.456263 0.456263 0.456263 ]
MakeNamedMaterial "Dragon"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.79311 0.79311 0.79311 ]
MakeNamedMaterial "Blade"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.79311 0.79311 0.79311 ]
MakeNamedMaterial "Sword"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.79311 0.79311 0.79311 ]
MakeNamedMaterial "Deco"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.79311 0.79311 0.79311 ]
MakeNamedMaterial "Diamond"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.79311 0.79311 0.79311 ]
MakeNamedMaterial "Deco2"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0.79311 0.79311 0.79311 ]
NamedMaterial "GroundOuter"
Shape "plymesh"
    "string filename" [ "models/Mesh011.ply" ]
NamedMaterial "Cloth"
Shape "plymesh"
    "string filename" [ "models/Mesh010.ply" ]
NamedMaterial "GroundOuter"
Shape "plymesh"
    "string filename" [ "models/Mesh005.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh006.ply" ]
NamedMaterial "GroundInner"
Shape "plymesh"
    "string filename" [ "models/Mesh012.ply" ]
NamedMaterial "GroundOuter"
Shape "plymesh"
    "string filename" [ "models/Mesh007.ply" ]
NamedMaterial "Dragon"
Shape "plymesh"
    "string filename" [ "models/Mesh008.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh013.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh014.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh015.ply" ]
NamedMaterial "Blade"
Shape "plymesh"
    "string filename" [ "models/Mesh004.ply" ]
NamedMaterial "Sword"
Shape "plymesh"
    "string filename" [ "models/Mesh009.ply" ]
NamedMaterial "Deco"
Shape "plymesh"
    "string filename" [ "models/Mesh003.ply" ]
NamedMaterial "Diamond"
Shape "plymesh"
    "string filename" [ "models/Mesh002.ply" ]
NamedMaterial "Deco2"
Shape "plymesh"
    "string filename" [ "models/Mesh001.ply" ]
Shape "plymesh"
    "string filename" [ "models/Mesh000.ply" ]
LightSource "distant"
    "rgb L" [ 8 8 8 ]
    "point3 to" [ 0 0 0 ]
    "point3 from" [ -0.18862 0.692312 0.69651 ]
`

**Comment by Reev970** [comment]
I also rendered this [scene](https://github.com/mmp/pbrt-v4-scenes/tree/master/disney-cloud) just now , the GPU mode worked fine.

![disney-cloud-720p](https://user-images.githubusercontent.com/128742476/228632232-7750b606-f01a-41b7-9d0b-0c4575eb3b3f.png)

This makes me confused , maybe what cause this problem are the model files ...i guess...

**Comment by pbrt4bounty** [comment]
As Matt said, everything in the log file looks correct. 
 - can you confirm that the 'dragon' and 'crown' scenes renders correctly in CPU mode? 
 - if you are compiling in 'Debug' mode, could you try compiling in 'Release' mode and render the scene again? 
 - could you share your executable (pbrt.exe would suffice) so that we can replicate the problem here?
In my case, I have compiled the code under Linux and Windows and in both cases, the GPU mode runs perfectly
Best regards..

**Comment by Reev970** [comment]
> * can you confirm that the 'dragon' and 'crown' scenes renders correctly in CPU mode?

I can confirm.

> * if you are compiling in 'Debug' mode, could you try compiling in 'Release' mode and render the scene again?

The compiling mode is already 'Release'.

> * could you share your executable (pbrt.exe would suffice) so that we can replicate the problem here?
 
[pbrt.exe ](https://mega.nz/file/rdBDxYQK#K_V5AXZtoBjePwO3Zm1nsuw0iEkwYFy7MK-egSdFNqA) , is this?

**Comment by pbrt4bounty** [comment]
`The compiling mode is already 'Release'.`
You pasted code says "Working directory: C:\Pbrt_v4\pbrt-v4\out\build\x64-Debug" this confused me.
Anyway, here, your binary work perfectly. So, no idea what is your computer configuration, your drivers version or somewhat  that produce the error. I'm sorry, but I can't help you.
Cheers..

**Comment by Reev970** [comment]
Fortunately, at least some scenes are fine , just the scenes which include PLY-Format files arise problems , i don't know why.

Anyway , thank your help.

**Comment by baiqiletter** [comment]
I got the same problem and solved it by completely remove and reinstall nvidia driver and cuda.

When the problem occurred, multiple version of cuda (11.7 and 12.1) were installed on my laptop, and the driver was the newest. After cleanly remove old ones and only install cuda 11.7 and its corresponding display driver (517), the result image gets correct without recompiling.

I don't know why this happened but it just works for me. Hope it helps.

**Comment by mmp** [comment]
This is quite strange! I'd like to chase it down since it's affecting multiple people but unfortunately it all works fine for me locally.

Could you try running with `--nthreads 1` and also try a debug build of pbrt? Hearing how things go with each of those might give a clue.

**Comment by pbrt4bounty** [comment]
As I have already commented in the other thread, (https://github.com/mmp/pbrt-v4/issues/331) apparently the problem is not compiling with cuda 12.1, at least here, the problem occurs with the drivers that Cuda 12.1 installs by default.

**Comment by mmp** [comment]
To confirm that the issue is related PLY files (and not all sorts of triangles), could someone try rendering this scene on the GPU?

```
# Cornell Box Scene
# Normal view
LookAt 0 56 308
    0 35 0
    0 1 0
# Zoom in on mirror ball
#LookAt 0 56 308  -23 17 50  0 1 0
#Camera "perspective" "float fov" [10]
# Zoom in on glass ball
#LookAt 0 56 308  23 17 85 0 1 0
#Camera "perspective" "float fov" [10]
#Integrator "whitted"
#Integrator "path"
#Integrator "photonmap" "float maxdist" [10.0]
Camera "perspective"
    "float fov" [ 30 ]
Film "rgb"
    "integer yresolution" [ 384 ]
    "integer xresolution" [ 512 ]


WorldBegin


AttributeBegin
    Translate 0 84.99 85
    AreaLightSource "diffuse"
        "rgb L" [ 20 20 20 ]
    Material "diffuse"
        "rgb reflectance" [ 0 0 0 ]
    Shape "trianglemesh"
        "point3 P" [ -17 0 -17 17 0 -17 17 0 17 -17 0 17 ]
        "integer indices" [ 0 1 2 2 3 0 ]
AttributeEnd

AttributeBegin
    Material "dielectric"
        "float eta" [ 1.5 ]
    Translate 23 17 85
    Shape "sphere"
        "float radius" [ 17 ]
AttributeEnd

AttributeBegin
    Material "conductor"
        "spectrum k" [ "metal-Ag-k" ]
        "spectrum eta" [ "metal-Ag-eta" ]
        "float roughness" [ 0 ]
    Translate -23 17 50
    Shape "sphere"
        "float radius" [ 17 ]
AttributeEnd

AttributeBegin
    # ceiling
    #floor
    # back wall
    # behind camera wall
    # left wall
    # right wall
    Material "diffuse"
        "rgb reflectance" [ 0.85 0.85 0.85 ]
    Shape "trianglemesh"
        "point3 P" [ -50 85 0 50 85 0 50 85 350 -50 85 350 ]
        "integer indices" [ 0 1 2 2 3 0 ]
    Shape "trianglemesh"
        "point3 P" [ -50 0 0 -50 0 350 50 0 350 50 0 0 ]
        "integer indices" [ 0 1 2 2 3 0 ]
    Shape "trianglemesh"
        "point3 P" [ -50 85 0 -50 0 0 50 0 0 50 85 0 ]
        "integer indices" [ 0 1 2 2 3 0 ]
    Shape "trianglemesh"
        "point3 P" [ -50 85 350 50 85 350 50 0 350 -50 0 350 ]
        "integer indices" [ 0 1 2 2 3 0 ]
    Material "diffuse"
        "rgb reflectance" [ 0.9 0.6 0.6 ]
    Shape "trianglemesh"
        "point3 P" [ -50 0 0 -50 85 0 -50 85 350 -50 0 350 ]
        "integer indices" [ 0 1 2 2 3 0 ]
    Material "diffuse"
        "rgb reflectance" [ 0.6 0.6 0.9 ]
    Shape "trianglemesh"
        "point3 P" [ 50 0 350 50 85 350 50 85 0 50 0 0 ]
        "integer indices" [ 0 1 2 2 3 0 ]
AttributeEnd
```

**Comment by pbrt4bounty** [comment]
I added a output file to the scene and render with this command line:
`pbrt.exe --log-level "verbose" --log-file c:/apps/pbrt4/debug.txt --nthreads 1 --gpu --gpu-device 0 --spp 4`
Rendered using a local build with:
 - MSVC 2022 + Cuda 12.1 + Optix 7.7 + 531.41 NVidia drivers
 
 rendered using a RTX 3060 12 gb  generates a black image
[pbrt4.zip](https://github.com/mmp/pbrt-v4/files/11138858/pbrt4.zip)

**Comment by aclysma** [comment]
Trying to find where CPU/GPU behavior diverge, I added a printf...

```
                // Trace rays and estimate radiance up to maximum ray depth
                for (int wavefrontDepth = 0; true; ++wavefrontDepth) {
                    // Reset queues before tracing rays
                    RayQueue *nextQueue = NextRayQueue(wavefrontDepth);
                    Do(
                       "Reset queues before tracing rays", PBRT_CPU_GPU_LAMBDA() {
                           printf("GenerateRaySamples %d\n", nextQueue->Size());

                           nextQueue->Reset();
```



`pbrt.exe --gpu --interactive ../../pbrt-v4-scenes/cornell_matt.pbrt`

```
GenerateRaySamples 0
GenerateRaySamples 196608
GenerateRaySamples 16324
GenerateRaySamples 8741
GenerateRaySamples 940
GenerateRaySamples 129
GenerateRaySamples 40
GenerateRaySamples 196608
GenerateRaySamples 16332
GenerateRaySamples 8731
GenerateRaySamples 940
GenerateRaySamples 132
GenerateRaySamples 46
GenerateRaySamples 196608
GenerateRaySamples 16307
GenerateRaySamples 8667
GenerateRaySamples 857
GenerateRaySamples 113
GenerateRaySamples 31
...
```

`pbrt.exe --wavefront --interactive ../../pbrt-v4-scenes/cornell_matt.pbrt`

```
GenerateRaySamples 0
GenerateRaySamples 196608
GenerateRaySamples 194986
GenerateRaySamples 153094
GenerateRaySamples 134119
GenerateRaySamples 117429
GenerateRaySamples 102571
GenerateRaySamples 196608
GenerateRaySamples 194984
GenerateRaySamples 153270
GenerateRaySamples 134283
GenerateRaySamples 117185
GenerateRaySamples 102208
GenerateRaySamples 196608
GenerateRaySamples 194982
GenerateRaySamples 153295
...
```

This is as far as I got this morning. Hopefully it's useful.

(Thanks for helping with this, and congratulations with the book. It's fantastic, thank you!)

**Comment by mmp** [comment]
Huh--very interesting! The lines with 196608 correspond to each fresh batch of camera rays; under the theory that the problem was that the triangle BVH wasn't being built in the first place, I would have expected 0 for all of the subsequent bounces until the next batch of camera rays. So it's quite interesting that rays are still active but not hitting anything.

Actually, one other experiment: try `#define`ing `PBRT_DBG_LOGGING` at the top of `pbrt.h` and then recompile. Then render just a single sample at single pixel, e.g. `--pixel 100,100 --spp 1`. Then it might be interesting to see where GPU and CPU `--wavefront` diverge.

**Comment by pbrt4bounty** [comment]
Tested here, following your above tips..
[cpu_vs_gpu_log.txt](https://github.com/mmp/pbrt-v4/files/11140533/cpu_vs_gpu_log.txt)
I hope this help you.
Cheers..

**Comment by aclysma** [comment]
I think it would also be interesting to see the queue depths between the steps in the pipeline, that's roughly what I was pursuing before I had to stop this morning.

Also, I did try some experiments forcing the ray intersection to always miss, trying to get the same behavior out of cpu/gpu. However, on CPU side I vaguely recall it was showing 0 samples aside from the camera ray batches (probably what you were expecting to see) and I didn't see a change on the GPU side. However, I didn't have time to make completely certain of these results so please take it with a grain of salt. I was curious where those rays were coming from when using GPU and was trying to disable code to identify the source of them (and determine why they don't seem to be generated when using CPU)

**Comment by mmp** [comment]
Hopefully the change I just pushed will fix this. (Apparently using unified/managed memory for vertex/index buffers given to optix isn't supposed to work.)

**Comment by mmp** [comment]
Yaay!

And a PR to fix that macro expansion would be fantastic. (Interestingly it doesn't seem to be an issue with the CI windows GPU builds on github.)

**Comment by mmp** [comment]
@aclysma if you have a second, could you try rolling back to before that fix and running with this environment variable set: `OPTIX_FORCE_DEPRECATED_LAUNCHER=1`? (The OptiX folks are curious about whether a recent change on their end is related to this.)

**Comment by aclysma** [comment]
I PR'ed #332. I can check on that environment variable tonight.

**Comment by pbrt4bounty** [comment]
Confirmed, this path https://github.com/mmp/pbrt-v4/commit/a2bd4c8850d06e4e5a5440677b90fc304a292e5d fix the issue here.

**Comment by mmp** [comment]
@pbrt4bounty Fantastic--thanks for the confirmation!

**Comment by aclysma** [comment]
@mmp I reverted back and reproduced the problem on cuda 12.1/optix 7.7. Then I set OPTIX_FORCE_DEPRECATED_LAUNCHER=1 and the problem no longer reproduced.

**Comment by mmp** [comment]
Great-thanks for checking that!
