### ISSUE TITLE
Thank you to the book distributor's( not a bug)

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#330]
Thank you Amazon for your honesty... I pre-purchased the book for $120, and now that the final price has been lowered, Amazon graciously refunds me the difference in price.
Impatient to receive and read it!
Cheers..!

**Comment by webanck** [comment]
Same here, thanks!

**Comment by pbrt4bounty** [comment]
Finally Tuesday the 11th arrives here(Spain) :)

**Comment by knightcrawler25** [comment]
Happy that my copy finally arrived :)

![20230411_115708-min](https://user-images.githubusercontent.com/11459803/231658881-a19f4e24-5530-4d1a-a2d3-aee502eb53ad.jpg)

@mmp 

There appear to be paperback versions of the book being sold for $60. Doesn't look legit though:

- https://www.amazon.com/Physically-Based-Rendering-Mary-Mashego/dp/B0BZF9RJ2D
- https://www.barnesandnoble.com/w/physically-based-rendering-mary-mashego/1143284957

**Comment by mmp** [comment]
Fun to see those pictures!

@knightcrawler25 thanks for letting me know about that. I'll send the publisher a note and see if there is anything to be done. It looks like it isn't a full copy of the book, even:

![image](https://user-images.githubusercontent.com/102567/231822684-49a66c79-c210-48f2-bca7-0476cf17471b.png)
![image](https://user-images.githubusercontent.com/102567/231822756-625aadfa-99b2-4aed-a405-4e30d266ed4a.png)

**Comment by alan-ramsay** [comment]
![20230416_174240](https://user-images.githubusercontent.com/63861280/235328439-c728b9b2-2897-4067-abb6-42fcee2e7221.jpg)
Mine also received with excitement, after first attempt lost in post!
