### ISSUE TITLE
Fix the EXR multilayer channels nomenclature in G-buffer mode

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#355]
Recently I have some issues loading the rendered files using G-buffer into Blender that can't load the image because some channel names. Following the tips from the Blender devs I changed some names:
'Nsx', 'Nsy', and 'Nsz' to "Ns.X", "Ns.Y", and "Ns.Z"
This respect the nomenclature for this EXR format in a few viewer applications( Tev, DJV..) that show this chanel as 'Ns(X,Y,Z)'
The unique question before create a pull request are if Pbrt-4 need this separate channels or can manage the new way.
If I remember correctly, this aligns with an earlier change we made to 'Variance' channel.
What do you think, @mmp ?

**Comment by pbrt4bounty** [comment]
Apparently the problem loading the files was on the Blender side and they have already fixed it. In any case, I am going to leave this report open for a few more days, in case someone wants to contribute their opinion.
Cheers..!

**Comment by mmp** [comment]
I don't see any problem with changing the naming from the pbrt side, if a better naming scheme will work better in other programs. (I don't think that the naming is discussed in the book and I assume it wouldn't be too disruptive to existing users of the current names.)

**Comment by pbrt4bounty** [comment]
Thanks Matt. Basically, this are the difference:
Current naming..
![imagen](https://github.com/mmp/pbrt-v4/assets/73945652/b6031a80-d391-4b82-aec1-5b699e9ccbd2)
New naming.. "P.X", "P.Y", "P.Z", "N.X", "N.Y", "N.Z", "Ns.X", "Ns.Y", "Ns.Z",
![imagen](https://github.com/mmp/pbrt-v4/assets/73945652/f042ae7f-f95a-4976-9033-893ac4c992a6)

I'll create a pull request in the next hours..
Cheers..!
