### ISSUE TITLE
The result of pbrt_v4 gpu operation at Pavilon-night is noisy

### ISSUE THREAD

**Issue by mu116699** [mmp/pbrt-v4#357]
The result of gpu operation at night is noisy, using Pavilon-night in pbrt v3.pbrt upgraded version v4 of pbrt, Sampler "halton" "integer pixelsamples" [512] No matter I reduce it by 256, Or upgrade to 1024, 2048, can not eliminate the noise in the generated picture, pbrt v3 CPU generated night results without noise, in pbrt v4, whether the CPU, GPU on the night of the rendering results contain noise, whether can give an optimized program. I uploaded the test results below, thank you.

The pictures given below are:pbrt_V3_night_cpu12700_2 23hr、pbrt_V4_night_cpu12700_23 1min、pbrt_v4_night_rtx3070_11 2s_Sampler_256、pbrt_v4_night_rtx3070_23 2s_Sampler_512、pbrt_v4_night_rtx3070_46 5s_Sampler_1024、pbrt_v4_night_rtx3070_87 8s_Sampler_2048

![pbrt_V3_night_cpu12700_2 23hr](https://github.com/mmp/pbrt-v4/assets/29351821/bde8afc7-be93-4380-897a-f17283ef9fb0)
![pbrt_V4_night_cpu12700_23 1min](https://github.com/mmp/pbrt-v4/assets/29351821/8a836b6d-7016-4583-927c-99de9dc605e5)
![pbrt_v4_night_rtx3070_11 2s_Sampler_256](https://github.com/mmp/pbrt-v4/assets/29351821/3947cea7-d5e6-4725-8457-fcda502f3d21)
![pbrt_v4_night_rtx3070_23 2s_Sampler_512](https://github.com/mmp/pbrt-v4/assets/29351821/a2eac9a8-a5d3-4b6e-bc5e-61d402d44445)
![pbrt_v4_night_rtx3070_46 5s_Sampler_1024](https://github.com/mmp/pbrt-v4/assets/29351821/e0c3f9f2-5460-469a-842d-5fa148f89ef3)
![pbrt_v4_night_rtx3070_87 8s_Sampler_2048](https://github.com/mmp/pbrt-v4/assets/29351821/2aaf3986-bc5c-4d9a-8eca-9b1b3a531379)

**Comment by rainbow-app** [comment]
You may try to debug it yourself a bit. For example:

* What integrator is used for v3 cpu, and v4 cpu?
* For GPU? (am I right that for GPU you can only use "path"?)
* Are all other settings really the same (except spp) between different cases?
* Try to simplify the scene, e.g. remove some lights, or volume scattering. This may help to narrow down the location of the problem. Such simplification may also help with previous item (to make sure that settings are the same).

Pbrt should output something useful in the logs, try --v 2 option. If it doesn't, try to insert some debug output yourself somewhere in the code.

Also:
* You could be a bit more descriptive about spp for CPU, both v3 and v4. (at least *I* didn't understand how many spps were used).
* You could use markdown features like a bullet list to make it easier for readers to understand you.

**Comment by mmp** [comment]
`pavilion-night.pbrt` uses the BDPT integrator, which isn't supported on the GPU (it always uses the equivalent of "volpath".) This is a tricky scene for regular path tracing due to all of the glass windows; the light sources can't be sampled directly, so volpath has to get lucky to find lights seen through glass. While BDPT is fairly effective at that, since it traces paths from the lights...

Could you try specifying "volpath" as the integrator, rendering on the CPU, and see if you get similar results to the GPU?

**Comment by Vutshi** [comment]
Hi @mmp 
Is the reason behind the difference in rendering results between BDPT integrator v3 and v4 apparent? 

Best

**Comment by mmp** [comment]
@Vutshi yes. See my comment on July 5: https://github.com/mmp/pbrt-v4/issues/357#issuecomment-1621424704
