### ISSUE TITLE
SubsurfaceMaterial::ToString() is missing the normalMap

### ISSUE THREAD

**Issue by llemarie-git** [mmp/pbrt-v4#358]
In materials.cpp, the function SubsurfaceMaterial::ToString() uses `normalMap: %s` in the format string, but does not have the `normalMap->ToString()` argument like the other material types. This causes a runtime crash when calling ToString() on a subsurface material (such as in the head.pbrt model). Other materials are fine.
The fix should be to either add the missing normalMap argument to StringPrintf(), or to remove it from the format string.

**Comment by mmp** [comment]
Fixed now--thanks!
