### ISSUE TITLE
-- Unable to find -lprofiler

### ISSUE THREAD

**Issue by disini** [mmp/pbrt-v4#370]
Hi guys,

I try to compile the code on ubuntu 22.04.2, after some errors and warnings solved, it still have a tip like this.
`-- Unable to find -lprofiler`
does anyone know what the "-lprofiler" is ? I searched on bing and google and github ,etc., but nothing about this "-lprofiler" was found.

Thanks so much!

**Comment by mmp** [comment]
It's part of gperftools: https://gperftools.github.io/gperftools/cpuprofile.html. If it's found, then you can use that (IMHO fairly nice) profiler. pbrt links with it if it's found but it's no problem if it isn't; it should still all build and run fin without it. On ubuntu I believe that it's in `libgoogle-perftools-dev`.

**Comment by disini** [comment]
> 

Thanks so much sir! I'll try it again!
