### ISSUE TITLE
Warning: image doesn't have Albedo.{R,G,B} channels. Denoising quality may suffer. Warning: output/bistro_vespa.exr: image doesn't have Ns.X, Ns.Y, Ns.Z channels. Denoising quality may suffer.

### ISSUE THREAD

**Issue by disini** [mmp/pbrt-v4#376]
Hello,

I rendered a picture with the command :

`./pbrt --gpu --spp 100 --display-server localhost:14158 /media/liusheng/Projects/project/game_engines/pbrt/github/mmp/pbrt-v4-scenes/2023/pbrt-v4-scenes/bistro/bistro_vespa.pbrt`

and it's log :

```
pbrt version 4 (built Jul 27 2023 at 10:58:03)
Copyright (c)1998-2021 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Warning: Sobol samplers with non power-of-two sample counts (100) are suboptimal.
Rendering: [++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++]  (92.7s)   
```

then I tried to use the imgtool to denoise the exr file the renderer output, with :

`imgtool denoise-optix output/bistro_vespa.exr --outfile output/bistro_vespa_denoised.exr` 

it finished the denoising work and gave a cleaner picture, but with 2 warnings.

```
Warning: output/bistro_vespa.exr: image doesn't have Albedo.{R,G,B} channels. Denoising quality may suffer.
Warning: output/bistro_vespa.exr: image doesn't have Ns.X, Ns.Y, Ns.Z channels. Denoising quality may suffer.
```

so I want to know is there any parameters I forgot to input when render the scene? 
or is it the correct rendered result for this program? 
I mean does the pbrt program not add those information(Albedo.{R,G,B} , Ns.X, Ns.Y, Ns.Z channels.) to the out put files ? 

Thank you sir !

**Comment by pbrt4bounty** [comment]
You need to select 'gbuffer' mode into Film parameters https://pbrt.org/fileformat-v4
I don't know if are a good idea to use this issue report for questions tha you can solve reading the guide
Only my 2 cts :)

**Comment by disini** [comment]
> You need to select 'gbuffer' mode into Film parameters https://pbrt.org/fileformat-v4 I don't know if are a good idea to use this issue report for questions that you can solve reading the guide Only my 2 cts :)

OK I will read the guide later, Thanks so much for your help!
