### ISSUE TITLE
Increasing iterations for Hair BSDF

### ISSUE THREAD

**Issue by Opioid** [mmp/pbrt-v4#379]
I have a question about increasing the value of pMax in the Hair BSDF, especially with regards to sin2kAlpha/cos2kAlpha. Those arrays are sized accordingly, and all values are filled in a loop. But as far as I can tell only the indices 0 through 2 are used later, regardless of pMax. Is this a mistake, or am I not seeing something.

EDIT:
I noticed that in pbrt those arrays have a constant size, despite the BSDF being almost the same.

In my experiments increasing pMax makes almost no difference, even for very bright hair, because the AP values get very small after just a few iterations. But this is with my own implementation, so there might be bugs. In the book the example on blonde hair is quite remarkable.

**Comment by mmp** [comment]
As explained in [section 9.9.4](https://www.pbr-book.org/4ed/Reflection_Models/Scattering_from_Hair#AbsorptioninFibers) the Ap() function folds the attenuation for pMax-1 -> infinity scatterings into the last entry of the returned array. Then in `HairBxDF::f()` there's a loop of `p` from 0 to `pMax` that uses elements of `Ap` and then right after that this line uses the last element `fsum += Mp(cosTheta_i, cosTheta_o, sinTheta_i, sinTheta_o, v[pMax]) * ap[pMax] / (2 * Pi);`

Note that the blonde hair example in [figure 9.55](https://www.pbr-book.org/4ed/Reflection_Models/Scattering_from_Hair#fig:hair-multiple-scattering) is about the number of bounces of light calculated using path tracing between different hairs, not the amount of scattering events within a single hair.
