### ISSUE TITLE
GBufferFilm

### ISSUE THREAD

**Issue by UHFT** [mmp/pbrt-v4#38]
Sorry, perhaps, it is not the right place to ask but there is no place to ask.

There is a new feature ("A new GBufferFilm that provides position, normal, albedo, etc., at each pixel is now available.") which I'd like to test for denoising. But pbrt4 returns "Unknown directive: GBufferFilm".

Could you give me a simple example of how to output position, normal, albedo?

Thanks,

**Comment by mmp** [comment]
Sorry for the lack of documentation..  Just do:
```
Film "gbuffer" "string filename" "foo.exr" "integer xresolution" 1234 # etc...
```

You'll get a "deep" EXR file, where all of that additional stuff is in additional image channels.

**Comment by UHFT** [comment]
Thanks for your quick response.

It seems the Albedo channel in EXR file seems strange.  
It should not be affected by the number of pixel samples. (I expected the original Kd reflectance)



![Screenshot 2020-09-10 at 23 10 01](https://user-images.githubusercontent.com/61891448/92814558-462cda80-f3bb-11ea-8d72-9db3f16e966e.jpg)
[](URL)


"""
Integrator "path"
    "integer maxdepth" [ 3 ]
Sampler "halton"
    "integer pixelsamples" [ 2 ]
PixelFilter "box"
    "float xradius" [ 0.5 ]
    "float yradius" [ 0.5 ]
    
Film "gbuffer"
    "string filename" [ "cornell-box.exr" ]
    "integer yresolution" [ 512 ]
    "integer xresolution" [ 512 ]

Camera "perspective"
    "float fov" [ 45 ]

WorldBegin
AttributeBegin
    AreaLightSource "diffuse"
        "rgb L" [ 10 10 10 ]
    NamedMaterial "Light"
    Shape "trianglemesh"
        "point2 uv" [ 0 0 1 0 1 1 0 1 
            ]
        "normal N" [ -8.74228e-8 -1 1.86006e-7 -8.74228e-8 -1 1.86006e-7 -8.74228e-8 
                     -1 1.86006e-7 -8.74228e-8 -1 1.86006e-7 ]
        "point3 P" [ -0.24 1.98 -0.22 0.23 1.98 -0.22 0.23 1.98 0.16 -0.24 1.98 0.16 ]
        "integer indices" [ 0 1 2 0 2 3 ]
AttributeEnd
MakeNamedMaterial "LeftWall"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 1 0 0 ]
MakeNamedMaterial "RightWall"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0 1 0 ]
MakeNamedMaterial "Floor"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 1 1 1 ]
MakeNamedMaterial "Ceiling"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 1 1 1 ]
MakeNamedMaterial "BackWall"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 1 1 1 ]
MakeNamedMaterial "ShortBox"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 1 1 1 ]
MakeNamedMaterial "TallBox"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 1 1 1 ]
MakeNamedMaterial "Light"
    "string type" [ "diffuse" ]
    "rgb reflectance" [ 0 0 0 ]
NamedMaterial "Floor"
Shape "trianglemesh"
    "point2 uv" [ 0 0 1 0 1 1 0 1 
        ]
    "normal N" [ 4.37114e-8 1 1.91069e-15 4.37114e-8 1 1.91069e-15 4.37114e-8 1 1.91069e-15 
                 4.37114e-8 1 1.91069e-15 ]
    "point3 P" [ -1 1.74846e-7 -1 -1 1.74846e-7 1 1 -1.74846e-7 1 1 -1.74846e-7 -1 ]
    "integer indices" [ 0 1 2 0 2 3 ]
NamedMaterial "Ceiling"
Shape "trianglemesh"
    "point2 uv" [ 0 0 1 0 1 1 0 1 
        ]
    "normal N" [ -8.74228e-8 -1 -4.37114e-8 -8.74228e-8 -1 -4.37114e-8 -8.74228e-8 
                 -1 -4.37114e-8 -8.74228e-8 -1 -4.37114e-8 ]
    "point3 P" [ 1 2 1 -1 2 1 -1 2 -1 1 2 -1 ]
    "integer indices" [ 0 1 2 0 2 3 ]
NamedMaterial "BackWall"
Shape "trianglemesh"
    "point2 uv" [ 0 0 1 0 1 1 0 1 
        ]
    "normal N" [ 8.74228e-8 -4.37114e-8 -1 8.74228e-8 -4.37114e-8 -1 8.74228e-8 -4.37114e-8 
                 -1 8.74228e-8 -4.37114e-8 -1 ]
    "point3 P" [ -1 0 -1 -1 2 -1 1 2 -1 1 0 -1 ]
    "integer indices" [ 0 1 2 0 2 3 ]
NamedMaterial "RightWall"
Shape "trianglemesh"
    "point2 uv" [ 0 0 1 0 1 1 0 1 
        ]
    "normal N" [ 1 -4.37114e-8 1.31134e-7 1 -4.37114e-8 1.31134e-7 1 -4.37114e-8 
                 1.31134e-7 1 -4.37114e-8 1.31134e-7 ]
    "point3 P" [ 1 0 -1 1 2 -1 1 2 1 1 0 1 ]
    "integer indices" [ 0 1 2 0 2 3 ]
NamedMaterial "LeftWall"
Shape "trianglemesh"
    "point2 uv" [ 0 0 1 0 1 1 0 1 
        ]
    "normal N" [ -1 -4.37114e-8 -4.37114e-8 -1 -4.37114e-8 -4.37114e-8 -1 -4.37114e-8 
                 -4.37114e-8 -1 -4.37114e-8 -4.37114e-8 ]
    "point3 P" [ -1 0 1 -1 2 1 -1 2 -1 -1 0 -1 ]
    "integer indices" [ 0 1 2 0 2 3 ]
"""

**Comment by mmp** [comment]
Ah, the joys of spectral rendering. It is expected that there will be some noise at low sampling rates here since at each pixel sample, pbrt picks 4 random wavelengths and does all of its computations at those wavelengths. Then, when the image is output, the RGB spectral matching functions are used to compute back to RGB. So, there's some inherent Monte Carlo noise in that round-trip from the original RGB colors. This is moderately annoying, but I think worth it for the advantages of doing the spectral stuff properly.
