### ISSUE TITLE
Normals: Tangent space to world space transforms errors

### ISSUE THREAD

**Issue by TiernoGs** [mmp/pbrt-v4#381]
Hello @mmp,

I recently stumbled accross a bug when using normal maps.
Apparently, when using instances (or even different objects) that share the same uvs, normals applied through a normal map follows the active rotation of the object. This shouldn't be the case as source direction is unique for infinite lights.

Here is the scene that gives me an error: [scene.zip](https://github.com/mmp/pbrt-v4/files/12500092/scene.zip)
Command: `pbrt.exe scene.pbrt --spp 4 --log-level verbose --seed 0 --nthreads 8 --disableWavelengthJitter`

The pbrt render:

![render](https://github.com/mmp/pbrt-v4/assets/50023513/8199b2e6-b4aa-405e-8116-4c94162a7608)

And the expected result when using Blender Cycles:

![blender](https://github.com/mmp/pbrt-v4/assets/50023513/660107d1-4aaf-4d35-a04b-dcb26e91949e)

In my opinion, it doesn't come from the reading of the normal map texture but either from the transform in the surface intersection shading geometry setup or the tangent to world space transformation.

Maybe this is also related to the issue with normals on gpu #377 ?

Thanks

**Comment by pbrt4bounty** [comment]
I can tested on Blender since I have a full operative plugin. BTW.. in Blender, Z  is up

**Comment by TiernoGs** [comment]
Hello, thank you for your reply, the updated line works just fine now :)
No need to look deeper into the light orientation, the blender cycles render was a way to highlight the normal map bug.
I'm closing the issue, thanks !

**Comment by mmp** [comment]
Interestingly, this fixes a number of errors in other scenes that use normal mapping; compare the curb, bistro glass doors, and menu to the left of the doors.

![old](https://github.com/mmp/pbrt-v4/assets/102567/606187a7-0c4f-4486-b9c8-fe8e38fbea02)
![new](https://github.com/mmp/pbrt-v4/assets/102567/8a7f749c-e54b-4584-94aa-21d3054c66c2)
