### ISSUE TITLE
Aspherical elements in camera

### ISSUE THREAD

**Issue by panwangjun** [mmp/pbrt-v4#382]
How to add aspherical lens in camera?

**Comment by pbrt4bounty** [comment]
Hi..  you meant add spherical lens or directly use a Spherical camera??
![imagen](https://github.com/mmp/pbrt-v4/assets/73945652/cca32eda-2108-40df-bee3-01c074802afb)
![imagen](https://github.com/mmp/pbrt-v4/assets/73945652/9d18a096-ea84-46d2-97ab-f35d0ddd010b)

Example scene..
[Spherical_Camera.zip](https://github.com/mmp/pbrt-v4/files/12599261/Spherical_Camera.zip)

**Comment by pbrt4bounty** [comment]
To add lens, you can create a  'Realistic' camera type and add a predefined lenses file, as is explained in the guide: https://pbrt.org/fileformat-v4
![imagen](https://github.com/mmp/pbrt-v4/assets/73945652/ba48fa62-8fc0-48c0-a037-862460994e37)

**Comment by mmp** [comment]
For aspherical lens elements, you would need to:
- extend the lens system specification syntax to allow specifying them (corresponding to some geometric representation)
- modify the code to trace rays through lenses to handle the new lens shape
- fix all of the places in the `RealisticCamera` that make implicit assumptions that the lens system is symmetric about the axis, of which there are many (exit pupil computations, etc...)

In general, you should thoroughly understand the current `RealisticCamera` implementation, at which point hopefully it will be evident what needs to be done.
