### ISSUE TITLE
Function Film.ToOutputRGB seems to output negative values in the photon mapper.

### ISSUE THREAD

**Issue by MaherRayes** [mmp/pbrt-v4#398]
I'm trying to output indirect illumination separately on the photon mapper. However printing `pixel.tau / (np * Pi * Sqr(pixel.radius))` gives negative values for some of the RGB channels. I tried to trace the value back and it seem like `RGB Phi_i = film.ToOutputRGB(pixel.vp.beta * Phi, photonLambda)` is returning negative values.

Is this expected behavior? The final images still look correct to me so I'm a bit confused.

**Comment by mmp** [comment]
This is to be expected (if surprising). For almost all RGB color spaces, there are spectra (generally of very saturated colors) that are outside of the color space; in turn, this can lead to negative RGB coefficients.
