### ISSUE TITLE
TeX comments in IDE

### ISSUE THREAD

**Issue by lobneroO** [mmp/pbrt-v4#408]
Throughout the code, TeX style comments have been used. E.g. in the lights.cpp

```// Compute $\cos\,\theta'$ and test against $\cos\,\theta_\roman{e}$```

Did you intend for users to read them as is, or do you know of any IDEs / Plugins that actually support these?

I had a look at [VS TeX Comments 2022](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1305558.VsTeXCommentsExtension2022), but that does not render everything ("\roman") correctly and is awkward with its line breaks.

**Comment by mmp** [comment]
I don't know of any IDEs that support those. Those are all generated automatically from the book source (which is written in TeX).
