### ISSUE TITLE
Equation 14.24 seems missing from the online version of the pbrt-v4 book

### ISSUE THREAD

**Issue by rsirefelt** [mmp/pbrt-v4#410]
Don't know if this is the correct forum but it seems that equation 14.24 does not show up on the online version of pbrt-v4:

https://www.pbr-book.org/4ed/Light_Transport_II_Volume_Rendering/Volume_Scattering_Integrators#eq:volpath-two-sample-mis-estimator

**Comment by mmp** [comment]
Thanks for reporting this! This will be fixed in the next push of the online edition (in a few hours.)
