### ISSUE TITLE
A question about CUDA constant memory initialization.

### ISSUE THREAD

**Issue by HuazyYang** [mmp/pbrt-v4#430]
In file spectrum.cpp:2596-2602, I read `xGPU`, `yGPU`, `zGPU` uploading logic where `xGPU` does not allocate any device memory. Does this make sense for cudaMemcpyToSymbol if device memory address is not allocated but the API call succeed?  
```
#ifdef PBRT_BUILD_GPU_RENDERER
    if (Options->useGPU) {
        CUDA_CHECK(cudaMemcpyToSymbol(xGPU, &x, sizeof(x)));
        CUDA_CHECK(cudaMemcpyToSymbol(yGPU, &y, sizeof(y)));
        CUDA_CHECK(cudaMemcpyToSymbol(zGPU, &z, sizeof(z)));
    }
#endif
```

**Comment by mmp** [comment]
(And just to close the loop for anyone else wondering about this: the key is that the Allocator passed to the Init() function there allocates memory on the GPU when GPU rendering is enabled.)
