### ISSUE TITLE
windows VS2017 camke error

### ISSUE THREAD

**Issue by MyBW** [mmp/pbrt-v4#44]
when I use cmake to generate project with vs2017, I get one error . It shows that src/pbrt/util/shuffle.h can not find.(517 line in the CMakeLists.txt) I can not find it also . So I delete this line in the CMakeLists.txt.  The I generate the VS project . 
But when I compile the pbrt_lib , I get a lot of errors like that:

>E:\pbrt\pbrt-v4\src\pbrt/util/vecmath.h(295)  error C2977: “pbrt::Vector3<pbrt::Interval<pbrt::Float>>” : too many template arguments
>E:\pbrt\pbrt-v4\src\pbrt/util/vecmath.h(519): see declaration of 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>'
So where is wrong?

**Comment by webanck** [comment]
It shouls be fixed by the last commit.

**Comment by MyBW** [comment]
I change to vs2019 . Then the problem is fixed.But the CmakeLists.txt is not right with the line.

**Comment by mmp** [comment]
Closing this out for now as unsupported (pending a PR from someone...)

I have added a check to the CMakeLists.txt file that will print a helpful error if MSVC 2017 is used (10def1adaa098ccb6).
