### ISSUE TITLE
Interface material visibly appears on gpu integrators

### ISSUE THREAD

**Issue by Sindarin27** [mmp/pbrt-v4#445]
When rendering an object with the `interface` material, it is expected that this object does not impact the rendered image.

When rendering with the `volpath` integrator on the CPU, the rendered image looks as expected, with or without the sphere of material `interface`: 
![image](https://github.com/user-attachments/assets/02eab373-07a2-4a21-89a3-fb9d24af823f)

When rendering on the GPU using `--gpu` or `--wavefront` (on an NVIDIA GeForce RTX 3050Ti), the same sphere is visible as a shadow: 
![image](https://github.com/user-attachments/assets/9b3f5c32-aed3-4140-b3a8-dd148fe88993)

The same shadow is visible when specifying a MediumInterface within the object, making media bounded by an interface always appear darker on the GPU.

Scene available here: https://pastebin.com/arz47sa6

**Comment by shadeops** [comment]
Try increasing the 'maxdepth' of the Volume Integrator.

One difference between the wavefront integrator and cpu volume integrator is that the wavefront includes interface intersections as part of the ray depth while the CPU one does not.

Try setting it to 10 or 15 and see if sphere artifact goes away.

**Comment by Sindarin27** [comment]
Increasing the `maxdepth` value above the default of 5 indeed takes care of the artifact. Thank you for the help.
