### ISSUE TITLE
Wrong indexing in nanovdb2pbrt converter script

### ISSUE THREAD

**Issue by SuikaSibyl** [mmp/pbrt-v4#452]
Hello! I notice the nanovdb2pbrt.cpp gets a critical fault.

Basically, the current indexing (say, x0 to x1) start from 0 to nx.
However, technically, nanovdb's index usually start from some negative index.
The start and end point is described in floatGrid->indexBBox().

If you simply read from 0 to nx, the volume is likely to be truncated.

I tried to adapt the converter to my own renderer and debugging for a long time here.
Hope it helps.

**Comment by mmp** [comment]
So you're staying that instead of the current code:
```c++
    int nx = floatGrid->indexBBox().dim()[0];
    // ...
    int x0 = 0, x1 = nx;
```
it should be something like
```c++
   int x0 = floatGrid->indexBBox().min()[0], x1 = floatGrid->indexBBox().max()[0];
   // ...
```
?

Do you have a nanodvb file where the current code crashes for testing?

**Comment by SuikaSibyl** [comment]
Yes, that's what I would suggest.

For nanovdb example, just:
https://github.com/shadeops/pbrt-v4-volumes

At least I tried Ground Explosion & Teapot Cloud.
I think both of them will be truncated if you start from 0

**Comment by mmp** [comment]
Confirmed and fixed. Thanks for reporting!
