### ISSUE TITLE
Save Alpha Channel with Transparent Backgound

### ISSUE THREAD

**Issue by Gaozhongpai** [mmp/pbrt-v4#457]
Can we save the alpha channel (i.e., RGBA) with a transparent background?

**Comment by mmp** [comment]
There's no current functionality to do that. It probably wouldn't be too hard if you only care about alpha for rays that hit/don't hit geometry. If you want partial alpha for volumetrics, you'd have to update the VolPathIntegrator to compute the full transmittance for camera rays; currently it doesn't keep ray-marching to compute transmittance (or check for geometry behind the volumetric) if there's a scattering event inside the volumetric.
