### ISSUE TITLE
Undesired side effect on Motion Blur... or expected?

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#461]
I have detected that the rendering result goes from darker to brighter with each step in which the difference in MotionBlur between the open shutter and the closed shutter grows.
0.0 to 0.25
![imagen](https://github.com/user-attachments/assets/b3fa5c6f-cf88-493f-a9c6-7c6275c37bb6)
0.0 to 0.5
![imagen](https://github.com/user-attachments/assets/947f0b13-2271-4b6e-80fe-4c19b2d36af9)
0.0 to 0.75
![imagen](https://github.com/user-attachments/assets/59aca20b-b6ce-4b4c-a2ce-780da98ad26c)

@mmp  ??

**Comment by mmp** [comment]
Yes, that is working as intended: a camera measures energy (power * time), so if the shutter is open longer, it measures more. Adjusting the film "iso" (as in a real camera) can harmonize that.
