### ISSUE TITLE
Single Build for Multiple GPU Architectures

### ISSUE THREAD

**Issue by jpwalters** [mmp/pbrt-v4#465]
We have 3 different GPUs (sm_61, sm_86 and sm_89) that we build for when we compile and currently we do 3 separate builds.  Ideally I would like to just do a single build that would run on any of our 3 GPUs.

How could I build once and run any of our three GPUs with the same executables?

**Comment by pbrt4bounty** [comment]
In theory,  sm_61 can work on all the other GPUs.

**Comment by jpwalters** [comment]
Thank you very much you are correct compiling for sm_61 does seem to work on all our GPUs.
