### ISSUE TITLE
Build for Windows on Linux

### ISSUE THREAD

**Issue by jpwalters** [mmp/pbrt-v4#466]
I'm trying to build pbrt for windows on a linux machine. 

How can I build pbrt for windows on ubuntu?

**Comment by jpwalters** [comment]
Here's the command I'm using to attempt the windows build on linux.  Clearly this is just the pre-build step.

`
cmake .. -DCMAKE_BUILD_TYPE=Release -DPBRT_GPU_SHADER_MODEL=sm_61 -DPBRT_OPTIX7_PATH=../optix -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-12.4 -DCUDA_CUDART_LIBRARY=/usr/local/cuda-12.4/lib64/libcudart.12.so -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_CXX_COMPILER_FORCED=True -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
`

Here's the error I'm getting.
`
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CUDA (missing: CUDA_CUDART_LIBRARY) (found version "12.4")
`

When I build for linux on the same machine of course if builds successfully and finds cuda without issue.

`
cmake .. -DCMAKE_BUILD_TYPE=Release -DPBRT_GPU_SHADER_MODEL=sm_61 -DPBRT_OPTIX7_PATH=../optix
`

Any ideas why the windows build is failing to find the cuda rt library?

**Comment by INDIAN2020** [comment]
In my opinion, not included WINE in your machine.
Wine: Wine is a free and open-source compatibility layer that allows you to run Windows applications on Linux. You can download Wine from the official website https://www.winehq.org/ and follow the installation instructions.
For reference: https://itsfoss.com/install-wine-ubuntu/

**Comment by jpwalters** [comment]
Yes, possibly WINE might work however I haven't tried.  I think to go down this route I'd have to install the microsoft build tool chain on linux.  Not sure how problematic that would be or not.

I did find some documentation from nvidia that said they currently don't support cross compiling for windows on a linux.  

For now I'm dropping this pursuit and will close this ticket.
