### ISSUE TITLE
Issues with CMake(3.18.3) wit Visual Studio 2017 on Windows 10

### ISSUE THREAD

**Issue by UHFT** [mmp/pbrt-v4#47]
I had no issue with PBRT v3 to compile but I've got some errors with PBRT v4.

I've cleanly installed CMake(3.18.3) and Visual Studio Community 2017 on Windows 10.
Then I cloned the project files 'git clone --recursive https://github.com/mmp/pbrt-v4.git' in shell.

Somehow, there are a few errors in CMake-gui step as follow:
`
$ cmake ../../pbrt-v4/
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
-- The CXX compiler identification is MSVC 19.16.27043.0
-- The C compiler identification is MSVC 19.16.27043.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.28.0.windows.1")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Configure ILMBASE Version: 2.5.3 Lib API: 25.0.2
CMake Warning (dev) at src/ext/openexr/IlmBase/config/IlmBaseSetup.cmake:56 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_SHARED_LIBS'.
Call Stack (most recent call first):
  src/ext/openexr/IlmBase/CMakeLists.txt:35 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file ucontext.h
-- Looking for include file ucontext.h - not found
-- WARNING pkg-config generation disabled
-- Configure OpenEXR Version: 2.5.3 Lib API: 25.0.2
-- Found ZLIB: zlibstatic
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN - Failed
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX - Failed
-- clang-format not found.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Unable to find -lprofiler
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- CUDA not found
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Failed
-- Performing Test HAVE_MMAP
-- Performing Test HAVE_MMAP - Failed
-- Performing Test HAS_INTRIN_H
-- Performing Test HAS_INTRIN_H - Success
-- Performing Test HAVE_DECLSPEC_NOINLINE
-- Performing Test HAVE_DECLSPEC_NOINLINE - Success
-- Performing Test HAVE_ATTRIBUTE_NOINLINE
-- Performing Test HAVE_ATTRIBUTE_NOINLINE - Failed
-- Performing Test HAVE__ALIGNED_MALLOC
-- Performing Test HAVE__ALIGNED_MALLOC - Success
-- Performing Test HAVE_POSIX_MEMALIGN
-- Performing Test HAVE_POSIX_MEMALIGN - Failed
-- Performing Test INT64_IS_OWN_TYPE
-- Performing Test INT64_IS_OWN_TYPE - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: C:/project/pbrt-v4/build
`

Then VS 2017 can build some projects only. 

`
7>C:\project\pbrt-v4\src\ext\openexr\OpenEXR\IlmImf\ImfBoxAttribute.cpp(56): error C2491: 'Imf_2_5::TypedAttribute<Imath_2_5::Box2i>::staticTypeName': definition of dllimport function not allowed
7>C:\project\pbrt-v4\src\ext\openexr\OpenEXR\IlmImf\ImfBoxAttribute.cpp(67): error C2491: 'Imf_2_5::TypedAttribute<Imath_2_5::Box2i>::writeValueTo': definition of dllimport function not allowed

7>ImfChannelListAttribute.cpp
7>C:\project\pbrt-v4\src\ext\openexr\OpenEXR\IlmImf\ImfChannelListAttribute.cpp(70): error C2491: 'Imf_2_5::TypedAttribute<Imf_2_5::ChannelList>::staticTypeName': definition of dllimport function not allowed
7>C:\project\pbrt-v4\src\ext\openexr\OpenEXR\IlmImf\ImfChannelListAttribute.cpp(104): error C2491: 'Imf_2_5::TypedAttribute<Imf_2_5::ChannelList>::writeValueTo': definition of dllimport function not allowed

7>ImfOpaqueAttribute.cpp
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(295): error C2977: 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>': too many template arguments
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(519): note: see declaration of 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(492): note: see reference to class template instantiation 'pbrt::Tuple3<pbrt::Vector3<pbrt::Interval<pbrt::Float>>,T>' being compiled
8>        with
8>        [
8>            T=pbrt::Interval<pbrt::Float>
8>        ]

8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(519): note: see reference to class template instantiation 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>' being compiled
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(295): error C2977: 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>': too many template arguments
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(519): note: see declaration of 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(324): error C2977: 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>': too many template arguments
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(519): note: see declaration of 'pbrt::Vector3<pbrt::Interval<pbrt::Float>>'

8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(295): error C2977: 'pbrt::Vector3<pbrt::Float>': too many template arguments
8>C:\project\pbrt-v4\src\pbrt/pbrt.h(106): note: see declaration of 'pbrt::Vector3<pbrt::Float>'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(324): error C2977: 'pbrt::Vector3<pbrt::Float>': too many template arguments
8>C:\project\pbrt-v4\src\pbrt/pbrt.h(106): note: see declaration of 'pbrt::Vector3<pbrt::Float>'

8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(492): error C3210: 'Tuple3<pbrt::Vector3<float>,float>': a member using-declaration can only be applied to a base class member
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(493): error C3210: 'Tuple3<pbrt::Vector3<float>,float>': a member using-declaration can only be applied to a base class member
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(494): error C3210: 'Tuple3<pbrt::Vector3<float>,float>': a member using-declaration can only be applied to a base class member
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(555): error C2326: 'pbrt::Vector3f pbrt::Vector3fi::Error(void) const': function cannot access 'pbrt::Vector3fi::x'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(555): error C2326: 'pbrt::Vector3f pbrt::Vector3fi::Error(void) const': function cannot access 'pbrt::Vector3fi::y'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(555): error C2326: 'pbrt::Vector3f pbrt::Vector3fi::Error(void) const': function cannot access 'pbrt::Vector3fi::z'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(557): error C2326: 'bool pbrt::Vector3fi::IsExact(void) const': function cannot access 'pbrt::Vector3fi::x'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(557): error C2326: 'bool pbrt::Vector3fi::IsExact(void) const': function cannot access 'pbrt::Vector3fi::y'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(557): error C2326: 'bool pbrt::Vector3fi::IsExact(void) const': function cannot access 'pbrt::Vector3fi::z'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(295): error C2977: 'pbrt::Point3<pbrt::FloatInterval>': too many template arguments
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(703): note: see declaration of 'pbrt::Point3<pbrt::FloatInterval>'
8>C:\project\pbrt-v4\src\pbrt/util/vecmath.h(630): note: see reference to class template instantiation 'pbrt::Tuple3<pbrt::Point3<pbrt::FloatInterval>,T>' being compiled
...
=== Build: 26 succeeded, 8 failed, 0 up-to-date, 6 skipped ===
`

I've tried to compile on another machine with the same setting but had the same issues.

Could you guide me on how to resolve this issue?

**Comment by UHFT** [comment]
I have to disable(untick) BUILD_SHARED_LIBS during CMake-gui step which resolves some issues but still have compile errors.

This seems the same as issue #44.  After installing VS 2019 then it works fine.

Can you make VS2017 version also work?

**Comment by mmp** [comment]
I'd happily merge a PR that added support for VS2017, but am unlikely to have time to dig into that myself in the foreseeable future.

**Comment by mmp** [comment]
In the meantime, I've added a MSVC version check in the cmakelists.txt file that prints an error if an earlier version than MSVC2019 is used..

**Comment by wumo** [comment]
I got the same error about compiling openexr on MSVC2019.

**Comment by zq317157782** [comment]
I got the same error about "too many template arguments" too, on MSVC2019
