### ISSUE TITLE
CUDA running error

### ISSUE THREAD

**Issue by UHFT** [mmp/pbrt-v4#48]
After successfully compile pbrt v4 with CUDA & Optix, there is running error as below:

$ pbrt.exe --display-server 127.0.0.1:14158  v4_cornellbox_uplight_PT_spp0064_d03.pbrt --spp 1024 --gpu
pbrt version 4 (built Oct  1 2020 at 23:15:32)
Copyright (c)1998-2020 Matt Pharr, Wenzel Jakob, and Greg Humphreys.
The source code to pbrt (but *not* the book contents) is covered by the Apache 2.0 License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [                                                                                                                                                                      ]  (0.1s|?s)  [ 4912.000
20201001.232927 C:/Work/PBRT/pbrt-v4/src/pbrt/gpu/pathintegrator.cpp:313 ] FATAL CUDA error: unspecified launch failure
(unknown                                 )      0x0000000000000000 - ☺
(unknown                                 )      0x0000000000000000 - ☺
(unknown                                 )      0x0000000000000000 - ☺
(unknown                                 )      0x0000000000000000 - ☺
(unknown                                 )      0x0000000000000000 - ☺
(unknown                                 )      0x0000000000000000 - ☺
(unknown                                 )      0x00007FFFA8991430 - configthreadlocale
(unknown                                 )      0x00007FFFAAEC6FC0 - BaseThreadInitThunk
(unknown                                 )      0x00007FFFAB19CEA0 - RtlUserThreadStart

Any idea what is wrong?  

It was compiled with these setting:
CMake: 3.17.5
CUDA: 11.0
Optix SDK: 7.1
Nvidia Driver Version: 456.43
Graphics card: NVIDIA GTX 2080 Ti
OS: Windows 10

**Comment by neverfelly** [comment]
#41 The same error as mine

**Comment by mmp** [comment]
Unfortunately I don't have the bandwidth to debug Windows GPU support at the moment and am unlikely to be able to for a few months. I have therefore updated the build so that building with GPU support on Windows is prohibited for now. Needless to say, PRs to fix this would be highly welcome. :-)

**Comment by mmp** [comment]
I believe that Windows is working well now, with the last fix in 597fc75a9ff6e20dad5dd3b5982935ceb915a11e. I would be interested to hear if it works for you as well. (And sorry for taking so long to chase this down!).

**Comment by mmp** [comment]
(I'm going to close this under the assumption that all is now well with the Windows GPU path.)
