### ISSUE TITLE
Float/Spectrum eta parameter conflict in Dielectric and ThinDielectric

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#51]
There is currently a bit of a conflict when using a spectrum texture for eta with the Dielectric or ThinDielectric Materials.

Take the following snippet as an example:
```
Texture "texture_checkerboard1" "spectrum" "checkerboard"
MakeNamedMaterial "material_dieletric1" "string type" "dielectric" "texture eta" [ "texture_checkerboard1" ]
```
When rendering you'll encounter the following error -
`Couldn't find float texture named "texture_checkerboard1" for parameter "eta"`

Currently the two materials in question should support eta as either a float or spectrum texture according to
https://github.com/mmp/pbrt-v4/blob/7c59035d485dbbc239f1215b1c6fa9e72a471bc2/src/pbrt/materials.cpp#L39-L41

However, the GetFloatTextureOrNull method has the following -
https://github.com/mmp/pbrt-v4/blob/7c59035d485dbbc239f1215b1c6fa9e72a471bc2/src/pbrt/paramdict.cpp#L881-L887

As currently written, since a texture has been specified but is not found in textures->floatTextureMap an ErrorExit is called despite the texture existing within textures->spectrumGeneralTextureMap

I suppose an easy fix would be to just rename spectrum eta to spectrum eta_s. Otherwise some plumbing is required.

**Comment by shadeops** [comment]
This might be addressed with the changes in https://github.com/mmp/pbrt-v4/commit/cc4098f95f5f8743ebb485df1cd7e844036c40e9

Will verify.

**Comment by mmp** [comment]
If by addressed you mean "obsoleted", I think you're right. :-)

(IMHO it doesn't make sense to be able to texture the index of refraction anyway-if anything, it would be varying as a function of 3D position. Though I suppose that's true of subsurface scattering and those parameters are often textured on the surface...)

**Comment by shadeops** [comment]
Sounds like a closable issue to me! 

:D
