### ISSUE TITLE
Bilinear Mesh AreaLight Artifacts

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#59]
Hello,

When using a bilinear mesh as a area light source I'm seeing some artifacts on the back side of the light. (When rendering single sided)

Here is an example of the back side of the light-
![back_side](https://user-images.githubusercontent.com/2104033/95539617-af484380-09a3-11eb-8942-897b40439b39.jpg)

And here is the front side of the light-
![lit_side](https://user-images.githubusercontent.com/2104033/95539641-bec78c80-09a3-11eb-9473-90cad0f5b7d1.jpg)

Simple scene to reproduce:
```
Film "rgb" 
    "integer xresolution" [ 800 ]
    "integer yresolution" [ 600 ]
    "string filename" [ "simple.exr" ]

PixelFilter "gaussian" 
    "float yradius" [ 2 ]
    "float xradius" [ 2 ]

Sampler "pmj02bn"
    "integer pixelsamples" [ 16 ]

Integrator "volpath"
    "integer maxdepth" [ 5 ]

Accelerator "bvh"

LookAt  0 20 -50
        0 5 0
        0 1 0

Camera "perspective"
        "float fov" [ 45 ]
        "float screenwindow" [ -1 1 -0.75 0.75 ]

WorldBegin

AttributeBegin
    AreaLightSource "diffuse"
        "float scale" [ 10 ]
        "bool twosided" [ false ]
    Translate 0 10 0
    Scale 5 5 1
    # Uncomment to see lit side of mesh
    # Rotate 180 0 1 0
    Shape "bilinearmesh" "point3 P" [ -1 -1 0
                                     1 -1 0
                                     -1 1 0
                                     1 1 0 ]
AttributeEnd

MakeNamedMaterial "matte" "string type" "diffuse"
    "rgb reflectance" [ 0.5 0.5 0.5 ]

# Ground
AttributeBegin
    NamedMaterial "matte"
    Rotate 90 1 0 0 
    Shape "disk" "float radius" [ 100 ]
AttributeEnd
```

**Comment by mmp** [comment]
Nice one--thanks as always for the bug report and the simple test case!

The issue turned out to be that the light had a diffuse BSDF so those speckles happened when the point used for light sampling happened to be just barely on the back side of the light source due to floating-point error and so then it seemed that there was some direct lighting... Anyway, this should be fixed now.
