### ISSUE TITLE
Area Light Samples and UV Coords

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#60]
Howdy,

I suspect this might be more of a TODO than a bug, but figured I should create an issue for any other intrepid early access users.

## Summary
Currently only the (0,0) uv is used when looking up textures for Area Light samples. As an example, if your light has a texture applied, the texture could be all blue, except for the (0,0) pixel, which is red. When the texture is sampled, only the red pixel will be looked up resulting in a interesting rendering like -

![uv_light](https://user-images.githubusercontent.com/2104033/95665659-64474100-0b07-11eb-9160-56387e4b6051.jpg)

## Details
When an AreaLight generates a light sample it requests a ShapeSample from the shape
https://github.com/mmp/pbrt-v4/blob/33308ca68681f26a657e87ae75f61375fe0c4019/src/pbrt/lights.h#L523-L525

And then later the Area Light uses the Interaction defined by the ShapeSample to fetch the uv coords.
https://github.com/mmp/pbrt-v4/blob/33308ca68681f26a657e87ae75f61375fe0c4019/src/pbrt/lights.h#L533

However currently, all the ShapeSamples returned do not provide uv coordinates as is the case here with the sphere shape.
https://github.com/mmp/pbrt-v4/blob/33308ca68681f26a657e87ae75f61375fe0c4019/src/pbrt/shapes.h#L359-L360

## Sample
Attached is the pbrt scene file and texture used to render the above.
[issue_60.zip](https://github.com/mmp/pbrt-v4/files/5360403/issue_60.zip)

**Comment by mmp** [comment]
This is actually a bug and not a TODO--thanks for noting it. I believe that it is correctly piped through for bilinear patches, but not for any of the other shapes. I'll try to fix it soon.

**Comment by mmp** [comment]
![Fixed](https://user-images.githubusercontent.com/102567/115784966-ae8d6280-a373-11eb-8a0e-8bdd2c07c327.png)

Thanks again for reporting this! Getting this all working also led to finding a bug (fixed in d86222e6b002380f3657744f747aacd07893f874), which is always nice.
