### ISSUE TITLE
Plans to update scene description documentation?

### ISSUE THREAD

**Issue by povmaniaco** [mmp/pbrt-v4#74]
I'm sorry.. this is more of a question than a bug report
I know there is a utility to update the scenes from version 3 and make them compatible with the current version, but I wonder if there are any plans to update the documentation on the scene format published here: [scene description..](https://pbrt.org/fileformat-v3.html)
I have plans to create ( at least..) a basic export / integration in Blender.
Thanks for all the work spreading the basic principles of rendering.

**Comment by shadeops** [comment]
While I don't want to speak for the pbrt team, I suspect the scene description page will be updated once pbrt-v4 reaches closer to release. The scene description itself and parameters are still changing frequently as work progresses.

As a stop gap you can use https://github.com/shadeops/pbrt_v3-to-v4_migration, its meant to be a "diff" of sorts between the pbrt-v3 scene description and where pbrt-v4 is currently at.

Also, if you are looking into exporters for Blender it might be worth checking out https://github.com/mmp/pbrt-v4/issues/39

**Comment by povmaniaco** [comment]
:O I think I'm late for the party.. Anyway, thanks for the links..

**Comment by mmp** [comment]
Yep, indeed, we'll get to that... eventually, but definitely not until all of the details have settled down, and possibly not until after the book text is basically done. @shadeops's document is a great resource in the meantime!
