### ISSUE TITLE
CHECK_RARE Feedback

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#75]
More of a question than an issue

I've come across a few of these over the past few weeks -

```
pbrt-v4/src/pbrt/bxdfs.h 321: CHECK_RARE failed: 
Dot(wo, wh) <= 0 @ 1.22068677e-05 failures was 12.206868x over limit 9.99999997e-07
(819211 samples, sigma est 1.49005981e-11)
Error: CHECK_RARE failures
```
https://github.com/mmp/pbrt-v4/blob/a792d6428e874fd3ce144b60dd359db3ecb46d7a/src/pbrt/bxdfs.h#L321

Do you want these reported? With sample scenes?

Or are they more on the FYI side of things?

**Comment by mmp** [comment]
Please do report those; a `CHECK_RARE` failing is, IMHO, more or less equivalent to an assertion failing even though it doesn't happen until after rendering.

If it's a small failure, like that one (~10x off), then no worries about a test case. Most of those thresholds are fairly ad-hoc. If it's way off (CHECK_RARE expecting something to be one in a million and you have a scene where it happens one in a hundred), then a test scene would be great.

The push now should help.
