### ISSUE TITLE
MLT Integrator Crashes with 0 value pdfs in AliasTable

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#77]
Howdy,

I've been getting occasional crashes with the MLT integrator where some of the pdf values in the bin are 0, which causes the DCHECK_GT to fail.
https://github.com/mmp/pbrt-v4/blob/167985a38daf8f473675aec0a6fff3a16fe62a37/src/pbrt/util/sampling.cpp#L640

In attempt to debug this I found a simple way to cause a crash by having no light samples hit anything during the bootstrap. Which in this case causes a NaN here -
https://github.com/mmp/pbrt-v4/blob/167985a38daf8f473675aec0a6fff3a16fe62a37/src/pbrt/util/sampling.cpp#L582

```
#9  0x00000000009fd532 in pbrt::AliasTable::Sample (this=0x7fffffffbe00, u=0.264874816, pdfOut=0x0, uRemapped=0x0)
    at /mnt/storage/job/pbrt-v4/src/pbrt/util/sampling.cpp:640
#10 0x0000000000b517fc in pbrt::MLTIntegrator::<lambda(int)>::operator()(int) const (__closure=0x3ca1050, i=15)
    at /mnt/storage/job/pbrt-v4/src/pbrt/cpu/integrators.cpp:2634
```

While this contrived scene isn't exactly the initial problem I was trying to debug I figured it was worth reporting because crashes == :cry: 

Example scene. Camera and area light, camera can't see the area light.

```
Film "rgb" "integer xresolution" [ 400 ] 
           "integer yresolution" [ 300 ]
           "string filename" [ "pbrt.exr" ]

PixelFilter "gaussian" "float yradius" [ 2 ]
                       "float xradius" [ 2 ]

Sampler "pmj02bn" "integer pixelsamples" [ 16 ]

Integrator "mlt" "integer maxdepth" [ 5 ]

Accelerator "bvh"

Transform [ 1 0 0 0 0 1 0 0 0 0 -1 0 0 0 0 1 ]
Camera "perspective" "float fov" [ 45 ]
                     "float screenwindow" [ -1 1 -0.5625 0.5625 ]

WorldBegin  # {

AttributeBegin  # {
    Translate 0 2 0
    Rotate 90 1 0 0
    AreaLightSource "diffuse" "bool twosided" [ true ] "float scale" [ 1 ]
    AttributeBegin  # {
        Material "none"
        ReverseOrientation
        Scale 1 1 -1
        Shape "sphere" "float radius" [ 0.5 ]
    AttributeEnd    # }
AttributeEnd    # }
```

**Comment by mmp** [comment]
Thanks for reporting this! It should be fixed now.
