### ISSUE TITLE
./bathroom/bathroomv4.pbrt:136:0: fourier: material type unknown

### ISSUE THREAD

**Issue by safes** [mmp/pbrt-v4#80]
can't known the material type "fourier"

**Comment by pbrt4bounty** [comment]
I think now this material type is deprecated and look the code in parsedscene.cpp is changed for 'measured'
parsedscene.cpp line 1324
```cpp
} 
else if (*name == "fourier")
        Warning(&loc, "\"fourier\" material is no longer supported. (But there "
                      "is \"measured\"!)");
```

**Comment by mmp** [comment]
As noted in the [readme](https://github.com/mmp/pbrt-v4/blob/master/README.md), many changes have been made to the input file format and so pbrt-v4 doesn't support pbrt-v3 scene files.
