### ISSUE TITLE
Compilation hangs when using a higher spectrum samples

### ISSUE THREAD

**Issue by Zhenyi-Liu** [mmp/pbrt-v4#81]
I was trying to use different values for NSpectrumSamples in Spectrum.h file, however, I found that a higher value results in a longer compilation time. 

I did some test on a 16 cores machine using `time make -j32`:
```
Nsamples = 8:
	real	1m52.647s
	user	11m47.697s
	sys	0m35.898s

Nsamples = 16:
	real	2m15.745s
	user	12m36.680s
	sys	0m36.398s
```
However, if I set a value higher than 16, it seems that it can never finish...
The problem only occurs when I compile the code using GPU, and no problem for CPU only compilation.

**Comment by mmp** [comment]
Very interesting--thanks for reporting this!

I can reproduce this as well. It looks like this is a CUDA compiler bug; I've submitted a repro case in a bug report in the internal NVIDIA bug database. I'll report back once there is more informaiton.

**Comment by Zhenyi-Liu** [comment]
> Very interesting--thanks for reporting this!
> 
> I can reproduce this as well. It looks like this is a CUDA compiler bug; I've submitted a repro case in a bug report in the internal NVIDIA bug database. I'll report back once there is more informaiton.

Hi Matt, 

Is there any luck on this issue? 

Thanks. 
Zhenyi

**Comment by mmp** [comment]
Hi, Zhenyi--

Yes! Indeed, that input was causing an infinite loop in the compiler. The bug has been fixed and so I expect that it will be in the next compiler release (or at worst, the one after that, depending on what the release schedule is.) Many thanks for reporting this!

**Comment by Zhenyi-Liu** [comment]
> Hi, Zhenyi--
> 
> Yes! Indeed, that input was causing an infinite loop in the compiler. The bug has been fixed and so I expect that it will be in the next compiler release (or at worst, the one after that, depending on what the release schedule is.) Many thanks for reporting this!

Hi Matt,

I check the latest CDUA release, it seems the issue has not been fixed yet? 
Thanks a lot if you could have a quick look.

**Comment by mmp** [comment]
Confirmed this is still broken with CUDA 11.2 (and 11.3 hits an internal error with pbrt, unfortunately.) :-( I will look into this.

**Comment by Zhenyi-Liu** [comment]
CUDA 11.4 fixed this issue! Hooray！:)

**Comment by mmp** [comment]
Yay!
