### ISSUE TITLE
Medium spectrum regression in 5e84482

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#83]
# Overview
When using bidirectional path tracing (bdpt / mlt) in 97152416d homogeneous mediums seem to evaluate with a constant spectrum. The volpath integrator behaves as expected. After running a git bisect this appears to have been introduced in 5e84482,  _Rework MediumHandle::SampleTmaj() interface_.
### volpath
![volpath](https://user-images.githubusercontent.com/2104033/99035158-d9a59780-2533-11eb-845e-e18523f7b75a.jpg)
### bdpt
![bdpt](https://user-images.githubusercontent.com/2104033/99035165-dd391e80-2533-11eb-98b7-0b8b29a215e6.jpg)

### bdpt on 06a7d099
This is a render using bdpt on the commit before 5e84482
![bdpt_06a7d0](https://user-images.githubusercontent.com/2104033/99035400-70725400-2534-11eb-8815-b0ef56dfd2eb.jpg)

### Example Scene
```
Film "rgb" 
    "integer xresolution" [ 400 ]
    "integer yresolution" [ 300 ]
#    "string filename" [ "volpath.exr" ]
    "string filename" [ "bdpt.exr" ]

PixelFilter "gaussian" 
    "float yradius" [ 2 ]
    "float xradius" [ 2 ]

Sampler "pmj02bn"
    "integer pixelsamples" [ 256 ]

#Integrator "volpath"
Integrator "bdpt"
    "integer maxdepth" [ 5 ]

Accelerator "bvh"

LookAt  0 20 -50
        0 5 0
        0 1 0

Camera "perspective"
        "float fov" [ 45 ]
        "float screenwindow" [ -1 1 -0.75 0.75 ]

WorldBegin

LightSource "infinite" "float scale" [ 1 ]

MakeNamedMaterial "matte" "string type" "diffuse"
    "rgb reflectance" [ 0.5 0.5 0.5 ]

# Ground
AttributeBegin
    NamedMaterial "matte"
    Rotate 90 1 0 0 
    Shape "disk" "float radius" [ 100 ]
AttributeEnd

MakeNamedMedium "red_medium" 
	"string type" "homogeneous"
	"rgb sigma_a" [ 0 0.5 0.5 ]
	"rgb sigma_s" [ 0 0 0 ]
	"float scale" [ 2 ]

# Red Glass
AttributeBegin
    Translate 0 10 0
	Material "dielectric"
	MediumInterface "red_medium" ""
    Shape "sphere" "float radius" [ 5 ]
AttributeEnd
```

**Comment by mmp** [comment]
Thanks for reporting this! I have good news and bad news..

The good news is that 1667b8b4248e981f1d1064098db594b2871223e2, just pushed, includes a few fixes to the PDF computations in the BDPT integrator that fix this.

The bad news is that the BDPT integrator is not very sophisticated about how it handles chromatic media at the moment, which in turn means that it has pretty high variance for a scene like this with highly saturated chromatic media. (Volpath is much better in this regard.) I hope that BDPT will be polished up in this regard before the final release, but TBD if it will make it under the wire...
