### ISSUE TITLE
Alternative to dipolesubsurface integrator

### ISSUE THREAD

**Issue by varun19299** [mmp/pbrt-v4#88]
Hi,

I was converting an older .pbrt file from PBRT-v2 to v4 manually. Since `dipolesubsurface` was removed in Pbrt-v2, what's the closest integrator I can replace it with?

Particularly, is there an integrator which accepts a points file list, similar to `dipolesubsurface`

The pbrt file:

```
Sampler "lowdiscrepancy" "integer pixelsamples" [16]
PixelFilter "box"
SurfaceIntegrator "dipolesubsurface" "string pointsfile" ["../../../subsurface.samples"]
Film "image" "string filename" ["output.exr"] "integer xresolution" [1024] "integer yresolution" [768]
Camera "perspective" "float fov" [60] 

WorldBegin
AttributeBegin
Translate 0.110900 0.000000 0.029716
Rotate  -30.000000 0.000000 1.000000 0.000000
LightSource "projection" "rgb I" [1 1 1] "string mapname" ["pattern.exr"] "float fov" [60]
AttributeEnd
Material "kdsubsurface" "color Kd" [0.3 0.3 0.3] "float meanfreepath" [fpinput]
AttributeBegin
Translate 0.005879 -0.124951 0.292944
Rotate  -15.000000 0.000000 1.000000 0.000000
Include "model.pbrt"
AttributeEnd
WorldEnd
```

**Comment by mmp** [comment]
Your best bet is the "volpath" integrator, which is the only one that supports subsurface scattering. As of pbrt-v3 there is no more precomputation of irradiance at points on the surface, however--that is now sampled stochastically, which works much better.
