### ISSUE TITLE
Is the coordinate system for projector lights different?

### ISSUE THREAD

**Issue by varun19299** [mmp/pbrt-v4#94]
Hi, I'm trying out a simple structured light scene. 

* There seems to be a discrepancy between `LookAt` & `CoordSysTransform "camera"`.
* Projector seems to be placed on Z axis instead of X.

Without projector:
![image](https://user-images.githubusercontent.com/21169383/101986846-80599100-3cb6-11eb-8c73-ac78c6297d8c.png)

Collocating via `CoordSysTransform "camera"`:
      ![image](https://user-images.githubusercontent.com/21169383/101986824-5a33f100-3cb6-11eb-97e3-f678f3b96433.png)

But co-locating with `LookAt` doesn't work:
![image](https://user-images.githubusercontent.com/21169383/101986847-818abe00-3cb6-11eb-971a-2f3222d30394.png)

Here's the projector's attribute set:
```
AttributeBegin
    #CoordSysTransform "camera"
    LookAt 4 0 0 # eye
        0 0 0 # look
        0 0 1 # up 
    #Rotate 90 0 1 0
    LightSource "projection"
        "float fov" [ 45 ]
        "string filename" [ "pattern.sub" ]
        "float scale" [ 20 ]
AttributeEnd
```

I tried playing around with the projector's rotation, turning by 90 along y-axis resulted in the following:
![image](https://user-images.githubusercontent.com/21169383/101988394-46d95380-3cbf-11eb-9e8c-554a5f68798f.png)

Seem's like the projector is located overhead at (0,0,4). and not (4,0,0). I believe the camera follows a left handed system, particularly this:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/21169383/101988624-b8fe6800-3cc0-11eb-87a0-e2b8475e65ec.png">

I moved the sphere along the axes to confirm the same.

Finally, the full PBRT file: https://gist.github.com/varun19299/d585f2b29667d8d6274535e802104ddc.

### Use Case

I'm simulating structured light and using co-located projector + camera as a sanity check. 

The `LookAt` command seems very convenient compared to Translate + Rotate, since it makes it much easier to set a given baseline + angle. `CoordSysTransform "camera"` isn't a good alternative, since I don't always want a colocated projector + camera.

I'd appreciate any help in this direction :)

**Comment by mmp** [comment]
I haven't confirmed, but I suspect that the issue is that when a camera is created, the current transformation specifies the world-to-camera transformation (https://pbrt.org/fileformat-v3.html#cameras), but when a shape is created, the current transformation gives the object-to-world transformation.

**Comment by varun19299** [comment]
Is this true for even a light source?

**Comment by varun19299** [comment]
Shifting to the camera coordinates via `CameraSysTransform "camera"` and then specifying the projector relative to the camera works fine.

(just need to compute `T_{wc}`, camera-to-world matrix, and invert).

Haven't been able to get LookAt working in the world reference coordinates.
