### ISSUE TITLE
Updated book schedule ?

### ISSUE THREAD

**Issue by jromang** [mmp/pbrt-v4#98]
The readme.md file says "We hope to have an online version of the book posted late in 2020 and printed books available in Spring 2021." As the book is not online, perhaps this should be updated ? (Yes I I look forward to read the paper book, and I'm too impatient ;) )

**Comment by povmaniaco** [comment]
Same here ( about impatient..) I bought the version 3 in e-book format, but for this version, I also want to have the physical book.
Cheers..

**Comment by shadeops** [comment]
Here is an update from last week to the PBRT Google Group.

https://groups.google.com/d/msgid/pbrt/8fc9de9d-861d-4d9c-8be3-e950854fee9dn%40googlegroups.com

**Comment by mmp** [comment]
Sorry about that. :-) Fixed now!

**Comment by jromang** [comment]
Thanks for the info and the fix !
